// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
    "context"
    
    `dpcms/internal/database/model`
    "gorm.io/gorm"
    "gorm.io/gorm/clause"
    "gorm.io/gorm/schema"
    
    "gorm.io/gen"
    "gorm.io/gen/field"
    
    "gorm.io/plugin/dbresolver"
)

func newTokenBlacklist(db *gorm.DB, opts ...gen.DOOption) tokenBlacklist {
	_tokenBlacklist := tokenBlacklist{}

	_tokenBlacklist.tokenBlacklistDo.UseDB(db, opts...)
	_tokenBlacklist.tokenBlacklistDo.UseModel(&model.TokenBlacklist{})

	tableName := _tokenBlacklist.tokenBlacklistDo.TableName()
	_tokenBlacklist.ALL = field.NewAsterisk(tableName)
	_tokenBlacklist.ID = field.NewInt64(tableName, "id")
	_tokenBlacklist.CreatedAt = field.NewTime(tableName, "created_at")
	_tokenBlacklist.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tokenBlacklist.DeletedAt = field.NewField(tableName, "deleted_at")
	_tokenBlacklist.UserId = field.NewInt64(tableName, "user_id")
	_tokenBlacklist.UUID = field.NewString(tableName, "'uuid'")

	_tokenBlacklist.fillFieldMap()

	return _tokenBlacklist
}

type tokenBlacklist struct {
	tokenBlacklistDo tokenBlacklistDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	UserId    field.Int64
	UUID      field.String

	fieldMap map[string]field.Expr
}

func (t tokenBlacklist) Table(newTableName string) *tokenBlacklist {
	t.tokenBlacklistDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tokenBlacklist) As(alias string) *tokenBlacklist {
	t.tokenBlacklistDo.DO = *(t.tokenBlacklistDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tokenBlacklist) updateTableName(table string) *tokenBlacklist {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.UserId = field.NewInt64(table, "user_id")
	t.UUID = field.NewString(table, "'uuid'")

	t.fillFieldMap()

	return t
}

func (t *tokenBlacklist) WithContext(ctx context.Context) *tokenBlacklistDo {
	return t.tokenBlacklistDo.WithContext(ctx)
}

func (t tokenBlacklist) TableName() string { return t.tokenBlacklistDo.TableName() }

func (t tokenBlacklist) Alias() string { return t.tokenBlacklistDo.Alias() }

func (t tokenBlacklist) Columns(cols ...field.Expr) gen.Columns {
	return t.tokenBlacklistDo.Columns(cols...)
}

func (t *tokenBlacklist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tokenBlacklist) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["user_id"] = t.UserId
	t.fieldMap["'uuid'"] = t.UUID
}

func (t tokenBlacklist) clone(db *gorm.DB) tokenBlacklist {
	t.tokenBlacklistDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tokenBlacklist) replaceDB(db *gorm.DB) tokenBlacklist {
	t.tokenBlacklistDo.ReplaceDB(db)
	return t
}

type tokenBlacklistDo struct{ gen.DO }

func (t tokenBlacklistDo) Debug() *tokenBlacklistDo {
	return t.withDO(t.DO.Debug())
}

func (t tokenBlacklistDo) WithContext(ctx context.Context) *tokenBlacklistDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tokenBlacklistDo) ReadDB() *tokenBlacklistDo {
	return t.Clauses(dbresolver.Read)
}

func (t tokenBlacklistDo) WriteDB() *tokenBlacklistDo {
	return t.Clauses(dbresolver.Write)
}

func (t tokenBlacklistDo) Session(config *gorm.Session) *tokenBlacklistDo {
	return t.withDO(t.DO.Session(config))
}

func (t tokenBlacklistDo) Clauses(conds ...clause.Expression) *tokenBlacklistDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tokenBlacklistDo) Returning(value interface{}, columns ...string) *tokenBlacklistDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tokenBlacklistDo) Not(conds ...gen.Condition) *tokenBlacklistDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tokenBlacklistDo) Or(conds ...gen.Condition) *tokenBlacklistDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tokenBlacklistDo) Select(conds ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tokenBlacklistDo) Where(conds ...gen.Condition) *tokenBlacklistDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tokenBlacklistDo) Order(conds ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tokenBlacklistDo) Distinct(cols ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tokenBlacklistDo) Omit(cols ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tokenBlacklistDo) Join(table schema.Tabler, on ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tokenBlacklistDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tokenBlacklistDo) RightJoin(table schema.Tabler, on ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tokenBlacklistDo) Group(cols ...field.Expr) *tokenBlacklistDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tokenBlacklistDo) Having(conds ...gen.Condition) *tokenBlacklistDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tokenBlacklistDo) Limit(limit int) *tokenBlacklistDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tokenBlacklistDo) Offset(offset int) *tokenBlacklistDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tokenBlacklistDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tokenBlacklistDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tokenBlacklistDo) Unscoped() *tokenBlacklistDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tokenBlacklistDo) Create(values ...*model.TokenBlacklist) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tokenBlacklistDo) CreateInBatches(values []*model.TokenBlacklist, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tokenBlacklistDo) Save(values ...*model.TokenBlacklist) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tokenBlacklistDo) First() (*model.TokenBlacklist, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenBlacklist), nil
	}
}

func (t tokenBlacklistDo) Take() (*model.TokenBlacklist, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenBlacklist), nil
	}
}

func (t tokenBlacklistDo) Last() (*model.TokenBlacklist, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenBlacklist), nil
	}
}

func (t tokenBlacklistDo) Find() ([]*model.TokenBlacklist, error) {
	result, err := t.DO.Find()
	return result.([]*model.TokenBlacklist), err
}

func (t tokenBlacklistDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TokenBlacklist, err error) {
	buf := make([]*model.TokenBlacklist, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tokenBlacklistDo) FindInBatches(result *[]*model.TokenBlacklist, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tokenBlacklistDo) Attrs(attrs ...field.AssignExpr) *tokenBlacklistDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tokenBlacklistDo) Assign(attrs ...field.AssignExpr) *tokenBlacklistDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tokenBlacklistDo) Joins(fields ...field.RelationField) *tokenBlacklistDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tokenBlacklistDo) Preload(fields ...field.RelationField) *tokenBlacklistDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tokenBlacklistDo) FirstOrInit() (*model.TokenBlacklist, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenBlacklist), nil
	}
}

func (t tokenBlacklistDo) FirstOrCreate() (*model.TokenBlacklist, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TokenBlacklist), nil
	}
}

func (t tokenBlacklistDo) FindByPage(offset int, limit int) (result []*model.TokenBlacklist, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tokenBlacklistDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tokenBlacklistDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tokenBlacklistDo) Delete(models ...*model.TokenBlacklist) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tokenBlacklistDo) withDO(do gen.Dao) *tokenBlacklistDo {
	t.DO = *do.(*gen.DO)
	return t
}
