// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newArticle(db *gorm.DB, opts ...gen.DOOption) article {
	_article := article{}

	_article.articleDo.UseDB(db, opts...)
	_article.articleDo.UseModel(&model.Article{})

	tableName := _article.articleDo.TableName()
	_article.ALL = field.NewAsterisk(tableName)
	_article.ID = field.NewUint64(tableName, "id")
	_article.CreatedAt = field.NewTime(tableName, "created_at")
	_article.UpdatedAt = field.NewTime(tableName, "updated_at")
	_article.DeletedAt = field.NewField(tableName, "deleted_at")
	_article.Url = field.NewString(tableName, "url")
	_article.CategoryID = field.NewUint64(tableName, "category_id")
	_article.UserID = field.NewUint64(tableName, "user_id")
	_article.Flag = field.NewInt16(tableName, "flag")
	_article.Title = field.NewString(tableName, "title")
	_article.Description = field.NewString(tableName, "description")
	_article.ClickCount = field.NewUint64(tableName, "click_count")
	_article.Status = field.NewInt8(tableName, "status")
	_article.Target = field.NewField(tableName, "target")
	_article.ContentModelId = field.NewUint64(tableName, "content_model_id")
	_article.Content = articleHasOneContent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Content", "model.ArticleContent"),
	}

	_article.Extra = articleHasOneExtra{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Extra", "model.ArticleContentModel"),
	}

	_article.Keywords = articleHasManyKeywords{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Keywords", "model.ArticleKeywords"),
	}

	_article.fillFieldMap()

	return _article
}

type article struct {
	articleDo articleDo

	ALL            field.Asterisk
	ID             field.Uint64
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field
	Url            field.String
	CategoryID     field.Uint64
	UserID         field.Uint64
	Flag           field.Int16
	Title          field.String
	Description    field.String
	ClickCount     field.Uint64
	Status         field.Int8
	Target         field.Field
	ContentModelId field.Uint64
	Content        articleHasOneContent

	Extra articleHasOneExtra

	Keywords articleHasManyKeywords

	fieldMap map[string]field.Expr
}

func (a article) Table(newTableName string) *article {
	a.articleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a article) As(alias string) *article {
	a.articleDo.DO = *(a.articleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *article) updateTableName(table string) *article {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Url = field.NewString(table, "url")
	a.CategoryID = field.NewUint64(table, "category_id")
	a.UserID = field.NewUint64(table, "user_id")
	a.Flag = field.NewInt16(table, "flag")
	a.Title = field.NewString(table, "title")
	a.Description = field.NewString(table, "description")
	a.ClickCount = field.NewUint64(table, "click_count")
	a.Status = field.NewInt8(table, "status")
	a.Target = field.NewField(table, "target")
	a.ContentModelId = field.NewUint64(table, "content_model_id")

	a.fillFieldMap()

	return a
}

func (a *article) WithContext(ctx context.Context) *articleDo { return a.articleDo.WithContext(ctx) }

func (a article) TableName() string { return a.articleDo.TableName() }

func (a article) Alias() string { return a.articleDo.Alias() }

func (a article) Columns(cols ...field.Expr) gen.Columns { return a.articleDo.Columns(cols...) }

func (a *article) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *article) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 17)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["url"] = a.Url
	a.fieldMap["category_id"] = a.CategoryID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["flag"] = a.Flag
	a.fieldMap["title"] = a.Title
	a.fieldMap["description"] = a.Description
	a.fieldMap["click_count"] = a.ClickCount
	a.fieldMap["status"] = a.Status
	a.fieldMap["target"] = a.Target
	a.fieldMap["content_model_id"] = a.ContentModelId

}

func (a article) clone(db *gorm.DB) article {
	a.articleDo.ReplaceConnPool(db.Statement.ConnPool)
	a.Content.db = db.Session(&gorm.Session{Initialized: true})
	a.Content.db.Statement.ConnPool = db.Statement.ConnPool
	a.Extra.db = db.Session(&gorm.Session{Initialized: true})
	a.Extra.db.Statement.ConnPool = db.Statement.ConnPool
	a.Keywords.db = db.Session(&gorm.Session{Initialized: true})
	a.Keywords.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a article) replaceDB(db *gorm.DB) article {
	a.articleDo.ReplaceDB(db)
	a.Content.db = db.Session(&gorm.Session{})
	a.Extra.db = db.Session(&gorm.Session{})
	a.Keywords.db = db.Session(&gorm.Session{})
	return a
}

type articleHasOneContent struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasOneContent) Where(conds ...field.Expr) *articleHasOneContent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasOneContent) WithContext(ctx context.Context) *articleHasOneContent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasOneContent) Session(session *gorm.Session) *articleHasOneContent {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasOneContent) Model(m *model.Article) *articleHasOneContentTx {
	return &articleHasOneContentTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasOneContent) Unscoped() *articleHasOneContent {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasOneContentTx struct{ tx *gorm.Association }

func (a articleHasOneContentTx) Find() (result *model.ArticleContent, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasOneContentTx) Append(values ...*model.ArticleContent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasOneContentTx) Replace(values ...*model.ArticleContent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasOneContentTx) Delete(values ...*model.ArticleContent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasOneContentTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasOneContentTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasOneContentTx) Unscoped() *articleHasOneContentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleHasOneExtra struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasOneExtra) Where(conds ...field.Expr) *articleHasOneExtra {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasOneExtra) WithContext(ctx context.Context) *articleHasOneExtra {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasOneExtra) Session(session *gorm.Session) *articleHasOneExtra {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasOneExtra) Model(m *model.Article) *articleHasOneExtraTx {
	return &articleHasOneExtraTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasOneExtra) Unscoped() *articleHasOneExtra {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasOneExtraTx struct{ tx *gorm.Association }

func (a articleHasOneExtraTx) Find() (result *model.ArticleContentModel, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasOneExtraTx) Append(values ...*model.ArticleContentModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasOneExtraTx) Replace(values ...*model.ArticleContentModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasOneExtraTx) Delete(values ...*model.ArticleContentModel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasOneExtraTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasOneExtraTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasOneExtraTx) Unscoped() *articleHasOneExtraTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleHasManyKeywords struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasManyKeywords) Where(conds ...field.Expr) *articleHasManyKeywords {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasManyKeywords) WithContext(ctx context.Context) *articleHasManyKeywords {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasManyKeywords) Session(session *gorm.Session) *articleHasManyKeywords {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasManyKeywords) Model(m *model.Article) *articleHasManyKeywordsTx {
	return &articleHasManyKeywordsTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasManyKeywords) Unscoped() *articleHasManyKeywords {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasManyKeywordsTx struct{ tx *gorm.Association }

func (a articleHasManyKeywordsTx) Find() (result []*model.ArticleKeywords, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasManyKeywordsTx) Append(values ...*model.ArticleKeywords) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasManyKeywordsTx) Replace(values ...*model.ArticleKeywords) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasManyKeywordsTx) Delete(values ...*model.ArticleKeywords) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasManyKeywordsTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasManyKeywordsTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasManyKeywordsTx) Unscoped() *articleHasManyKeywordsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleDo struct{ gen.DO }

func (a articleDo) Debug() *articleDo {
	return a.withDO(a.DO.Debug())
}

func (a articleDo) WithContext(ctx context.Context) *articleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleDo) ReadDB() *articleDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleDo) WriteDB() *articleDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleDo) Session(config *gorm.Session) *articleDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleDo) Clauses(conds ...clause.Expression) *articleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleDo) Returning(value interface{}, columns ...string) *articleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleDo) Not(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleDo) Or(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleDo) Select(conds ...field.Expr) *articleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleDo) Where(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleDo) Order(conds ...field.Expr) *articleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleDo) Distinct(cols ...field.Expr) *articleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleDo) Omit(cols ...field.Expr) *articleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleDo) Join(table schema.Tabler, on ...field.Expr) *articleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleDo) Group(cols ...field.Expr) *articleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleDo) Having(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleDo) Limit(limit int) *articleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleDo) Offset(offset int) *articleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleDo) Unscoped() *articleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleDo) Create(values ...*model.Article) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleDo) CreateInBatches(values []*model.Article, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleDo) Save(values ...*model.Article) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleDo) First() (*model.Article, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) Take() (*model.Article, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) Last() (*model.Article, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) Find() ([]*model.Article, error) {
	result, err := a.DO.Find()
	return result.([]*model.Article), err
}

func (a articleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Article, err error) {
	buf := make([]*model.Article, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleDo) FindInBatches(result *[]*model.Article, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleDo) Attrs(attrs ...field.AssignExpr) *articleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleDo) Assign(attrs ...field.AssignExpr) *articleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleDo) Joins(fields ...field.RelationField) *articleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleDo) Preload(fields ...field.RelationField) *articleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleDo) FirstOrInit() (*model.Article, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) FirstOrCreate() (*model.Article, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) FindByPage(offset int, limit int) (result []*model.Article, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleDo) Delete(models ...*model.Article) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleDo) withDO(do gen.Dao) *articleDo {
	a.DO = *do.(*gen.DO)
	return a
}
