// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persistence/model"
)

func newArticle(db *gorm.DB, opts ...gen.DOOption) article {
	_article := article{}

	_article.articleDo.UseDB(db, opts...)
	_article.articleDo.UseModel(&model.Article{})

	tableName := _article.articleDo.TableName()
	_article.ALL = field.NewAsterisk(tableName)
	_article.ID = field.NewUint64(tableName, "id")
	_article.CreatedAt = field.NewTime(tableName, "created_at")
	_article.UpdatedAt = field.NewTime(tableName, "updated_at")
	_article.DeletedAt = field.NewField(tableName, "deleted_at")
	_article.Url = field.NewString(tableName, "url")
	_article.CategoryID = field.NewUint64(tableName, "category_id")
	_article.AuthorID = field.NewUint64(tableName, "author_id")
	_article.Flag = field.NewInt16(tableName, "flag")
	_article.Title = field.NewString(tableName, "title")
	_article.Description = field.NewString(tableName, "description")
	_article.ClickCount = field.NewUint64(tableName, "click_count")
	_article.Status = field.NewInt8(tableName, "status")
	_article.Target = field.NewField(tableName, "target")
	_article.ModelID = field.NewUint64(tableName, "model_id")
	_article.SubmitAt = field.NewTime(tableName, "submit_at")
	_article.PublishAt = field.NewTime(tableName, "publish_at")
	_article.OfflineAt = field.NewTime(tableName, "offline_at")
	_article.RejectAt = field.NewTime(tableName, "reject_at")
	_article.Category = articleHasOneCategory{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Category", "model.Category"),
		SEO: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Category.SEO", "model.CategorySeo"),
		},
	}

	_article.Author = articleHasOneAuthor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Author", "model.UserProfile"),
	}

	_article.Content = articleHasOneContent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Content", "model.ArticleContent"),
	}

	_article.ModelData = articleHasOneModelData{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ModelData", "model.ArticleModelJsonData"),
	}

	_article.Keywords = articleHasManyKeywords{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Keywords", "model.ArticleKeywords"),
	}

	_article.ModelSchema = articleHasManyModelSchema{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ModelSchema", "model.ArticleModelSchema"),
	}

	_article.fillFieldMap()

	return _article
}

type article struct {
	articleDo articleDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Url         field.String // '自定义内容URL'
	CategoryID  field.Uint64 // '文章份额里'
	AuthorID    field.Uint64 // '文章作者'
	Flag        field.Int16  // '文章flag，使用时转二进制'
	Title       field.String // '文章标题'
	Description field.String // '文章简介'
	ClickCount  field.Uint64 // '点击数'
	Status      field.Int8   // '文章状态'
	Target      field.Field  // '外链类文章URL'
	ModelID     field.Uint64 // '内容模型'
	SubmitAt    field.Time   // '提交时间'
	PublishAt   field.Time   // '发布时间'
	OfflineAt   field.Time   // '下线时间'
	RejectAt    field.Time
	Category    articleHasOneCategory

	Author articleHasOneAuthor

	Content articleHasOneContent

	ModelData articleHasOneModelData

	Keywords articleHasManyKeywords

	ModelSchema articleHasManyModelSchema

	fieldMap map[string]field.Expr
}

func (a article) Table(newTableName string) *article {
	a.articleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a article) As(alias string) *article {
	a.articleDo.DO = *(a.articleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *article) updateTableName(table string) *article {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Url = field.NewString(table, "url")
	a.CategoryID = field.NewUint64(table, "category_id")
	a.AuthorID = field.NewUint64(table, "author_id")
	a.Flag = field.NewInt16(table, "flag")
	a.Title = field.NewString(table, "title")
	a.Description = field.NewString(table, "description")
	a.ClickCount = field.NewUint64(table, "click_count")
	a.Status = field.NewInt8(table, "status")
	a.Target = field.NewField(table, "target")
	a.ModelID = field.NewUint64(table, "model_id")
	a.SubmitAt = field.NewTime(table, "submit_at")
	a.PublishAt = field.NewTime(table, "publish_at")
	a.OfflineAt = field.NewTime(table, "offline_at")
	a.RejectAt = field.NewTime(table, "reject_at")

	a.fillFieldMap()

	return a
}

func (a *article) WithContext(ctx context.Context) *articleDo { return a.articleDo.WithContext(ctx) }

func (a article) TableName() string { return a.articleDo.TableName() }

func (a article) Alias() string { return a.articleDo.Alias() }

func (a article) Columns(cols ...field.Expr) gen.Columns { return a.articleDo.Columns(cols...) }

func (a *article) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *article) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 24)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["url"] = a.Url
	a.fieldMap["category_id"] = a.CategoryID
	a.fieldMap["author_id"] = a.AuthorID
	a.fieldMap["flag"] = a.Flag
	a.fieldMap["title"] = a.Title
	a.fieldMap["description"] = a.Description
	a.fieldMap["click_count"] = a.ClickCount
	a.fieldMap["status"] = a.Status
	a.fieldMap["target"] = a.Target
	a.fieldMap["model_id"] = a.ModelID
	a.fieldMap["submit_at"] = a.SubmitAt
	a.fieldMap["publish_at"] = a.PublishAt
	a.fieldMap["offline_at"] = a.OfflineAt
	a.fieldMap["reject_at"] = a.RejectAt

}

func (a article) clone(db *gorm.DB) article {
	a.articleDo.ReplaceConnPool(db.Statement.ConnPool)
	a.Category.db = db.Session(&gorm.Session{Initialized: true})
	a.Category.db.Statement.ConnPool = db.Statement.ConnPool
	a.Author.db = db.Session(&gorm.Session{Initialized: true})
	a.Author.db.Statement.ConnPool = db.Statement.ConnPool
	a.Content.db = db.Session(&gorm.Session{Initialized: true})
	a.Content.db.Statement.ConnPool = db.Statement.ConnPool
	a.ModelData.db = db.Session(&gorm.Session{Initialized: true})
	a.ModelData.db.Statement.ConnPool = db.Statement.ConnPool
	a.Keywords.db = db.Session(&gorm.Session{Initialized: true})
	a.Keywords.db.Statement.ConnPool = db.Statement.ConnPool
	a.ModelSchema.db = db.Session(&gorm.Session{Initialized: true})
	a.ModelSchema.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a article) replaceDB(db *gorm.DB) article {
	a.articleDo.ReplaceDB(db)
	a.Category.db = db.Session(&gorm.Session{})
	a.Author.db = db.Session(&gorm.Session{})
	a.Content.db = db.Session(&gorm.Session{})
	a.ModelData.db = db.Session(&gorm.Session{})
	a.Keywords.db = db.Session(&gorm.Session{})
	a.ModelSchema.db = db.Session(&gorm.Session{})
	return a
}

type articleHasOneCategory struct {
	db *gorm.DB

	field.RelationField

	SEO struct {
		field.RelationField
	}
}

func (a articleHasOneCategory) Where(conds ...field.Expr) *articleHasOneCategory {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasOneCategory) WithContext(ctx context.Context) *articleHasOneCategory {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasOneCategory) Session(session *gorm.Session) *articleHasOneCategory {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasOneCategory) Model(m *model.Article) *articleHasOneCategoryTx {
	return &articleHasOneCategoryTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasOneCategory) Unscoped() *articleHasOneCategory {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasOneCategoryTx struct{ tx *gorm.Association }

func (a articleHasOneCategoryTx) Find() (result *model.Category, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasOneCategoryTx) Append(values ...*model.Category) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasOneCategoryTx) Replace(values ...*model.Category) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasOneCategoryTx) Delete(values ...*model.Category) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasOneCategoryTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasOneCategoryTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasOneCategoryTx) Unscoped() *articleHasOneCategoryTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleHasOneAuthor struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasOneAuthor) Where(conds ...field.Expr) *articleHasOneAuthor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasOneAuthor) WithContext(ctx context.Context) *articleHasOneAuthor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasOneAuthor) Session(session *gorm.Session) *articleHasOneAuthor {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasOneAuthor) Model(m *model.Article) *articleHasOneAuthorTx {
	return &articleHasOneAuthorTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasOneAuthor) Unscoped() *articleHasOneAuthor {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasOneAuthorTx struct{ tx *gorm.Association }

func (a articleHasOneAuthorTx) Find() (result *model.UserProfile, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasOneAuthorTx) Append(values ...*model.UserProfile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasOneAuthorTx) Replace(values ...*model.UserProfile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasOneAuthorTx) Delete(values ...*model.UserProfile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasOneAuthorTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasOneAuthorTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasOneAuthorTx) Unscoped() *articleHasOneAuthorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleHasOneContent struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasOneContent) Where(conds ...field.Expr) *articleHasOneContent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasOneContent) WithContext(ctx context.Context) *articleHasOneContent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasOneContent) Session(session *gorm.Session) *articleHasOneContent {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasOneContent) Model(m *model.Article) *articleHasOneContentTx {
	return &articleHasOneContentTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasOneContent) Unscoped() *articleHasOneContent {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasOneContentTx struct{ tx *gorm.Association }

func (a articleHasOneContentTx) Find() (result *model.ArticleContent, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasOneContentTx) Append(values ...*model.ArticleContent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasOneContentTx) Replace(values ...*model.ArticleContent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasOneContentTx) Delete(values ...*model.ArticleContent) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasOneContentTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasOneContentTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasOneContentTx) Unscoped() *articleHasOneContentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleHasOneModelData struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasOneModelData) Where(conds ...field.Expr) *articleHasOneModelData {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasOneModelData) WithContext(ctx context.Context) *articleHasOneModelData {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasOneModelData) Session(session *gorm.Session) *articleHasOneModelData {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasOneModelData) Model(m *model.Article) *articleHasOneModelDataTx {
	return &articleHasOneModelDataTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasOneModelData) Unscoped() *articleHasOneModelData {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasOneModelDataTx struct{ tx *gorm.Association }

func (a articleHasOneModelDataTx) Find() (result *model.ArticleModelJsonData, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasOneModelDataTx) Append(values ...*model.ArticleModelJsonData) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasOneModelDataTx) Replace(values ...*model.ArticleModelJsonData) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasOneModelDataTx) Delete(values ...*model.ArticleModelJsonData) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasOneModelDataTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasOneModelDataTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasOneModelDataTx) Unscoped() *articleHasOneModelDataTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleHasManyKeywords struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasManyKeywords) Where(conds ...field.Expr) *articleHasManyKeywords {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasManyKeywords) WithContext(ctx context.Context) *articleHasManyKeywords {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasManyKeywords) Session(session *gorm.Session) *articleHasManyKeywords {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasManyKeywords) Model(m *model.Article) *articleHasManyKeywordsTx {
	return &articleHasManyKeywordsTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasManyKeywords) Unscoped() *articleHasManyKeywords {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasManyKeywordsTx struct{ tx *gorm.Association }

func (a articleHasManyKeywordsTx) Find() (result []*model.ArticleKeywords, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasManyKeywordsTx) Append(values ...*model.ArticleKeywords) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasManyKeywordsTx) Replace(values ...*model.ArticleKeywords) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasManyKeywordsTx) Delete(values ...*model.ArticleKeywords) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasManyKeywordsTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasManyKeywordsTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasManyKeywordsTx) Unscoped() *articleHasManyKeywordsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleHasManyModelSchema struct {
	db *gorm.DB

	field.RelationField
}

func (a articleHasManyModelSchema) Where(conds ...field.Expr) *articleHasManyModelSchema {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleHasManyModelSchema) WithContext(ctx context.Context) *articleHasManyModelSchema {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleHasManyModelSchema) Session(session *gorm.Session) *articleHasManyModelSchema {
	a.db = a.db.Session(session)
	return &a
}

func (a articleHasManyModelSchema) Model(m *model.Article) *articleHasManyModelSchemaTx {
	return &articleHasManyModelSchemaTx{a.db.Model(m).Association(a.Name())}
}

func (a articleHasManyModelSchema) Unscoped() *articleHasManyModelSchema {
	a.db = a.db.Unscoped()
	return &a
}

type articleHasManyModelSchemaTx struct{ tx *gorm.Association }

func (a articleHasManyModelSchemaTx) Find() (result []*model.ArticleModelSchema, err error) {
	return result, a.tx.Find(&result)
}

func (a articleHasManyModelSchemaTx) Append(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleHasManyModelSchemaTx) Replace(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleHasManyModelSchemaTx) Delete(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleHasManyModelSchemaTx) Clear() error {
	return a.tx.Clear()
}

func (a articleHasManyModelSchemaTx) Count() int64 {
	return a.tx.Count()
}

func (a articleHasManyModelSchemaTx) Unscoped() *articleHasManyModelSchemaTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleDo struct{ gen.DO }

func (a articleDo) Debug() *articleDo {
	return a.withDO(a.DO.Debug())
}

func (a articleDo) WithContext(ctx context.Context) *articleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleDo) ReadDB() *articleDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleDo) WriteDB() *articleDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleDo) Session(config *gorm.Session) *articleDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleDo) Clauses(conds ...clause.Expression) *articleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleDo) Returning(value interface{}, columns ...string) *articleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleDo) Not(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleDo) Or(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleDo) Select(conds ...field.Expr) *articleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleDo) Where(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleDo) Order(conds ...field.Expr) *articleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleDo) Distinct(cols ...field.Expr) *articleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleDo) Omit(cols ...field.Expr) *articleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleDo) Join(table schema.Tabler, on ...field.Expr) *articleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleDo) Group(cols ...field.Expr) *articleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleDo) Having(conds ...gen.Condition) *articleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleDo) Limit(limit int) *articleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleDo) Offset(offset int) *articleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleDo) Unscoped() *articleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleDo) Create(values ...*model.Article) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleDo) CreateInBatches(values []*model.Article, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleDo) Save(values ...*model.Article) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleDo) First() (*model.Article, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) Take() (*model.Article, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) Last() (*model.Article, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) Find() ([]*model.Article, error) {
	result, err := a.DO.Find()
	return result.([]*model.Article), err
}

func (a articleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Article, err error) {
	buf := make([]*model.Article, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleDo) FindInBatches(result *[]*model.Article, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleDo) Attrs(attrs ...field.AssignExpr) *articleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleDo) Assign(attrs ...field.AssignExpr) *articleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleDo) Joins(fields ...field.RelationField) *articleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleDo) Preload(fields ...field.RelationField) *articleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleDo) FirstOrInit() (*model.Article, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) FirstOrCreate() (*model.Article, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Article), nil
	}
}

func (a articleDo) FindByPage(offset int, limit int) (result []*model.Article, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleDo) Delete(models ...*model.Article) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleDo) withDO(do gen.Dao) *articleDo {
	a.DO = *do.(*gen.DO)
	return a
}
