// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newArticleContentModel(db *gorm.DB, opts ...gen.DOOption) articleContentModel {
	_articleContentModel := articleContentModel{}

	_articleContentModel.articleContentModelDo.UseDB(db, opts...)
	_articleContentModel.articleContentModelDo.UseModel(&model.ArticleModelRelationship{})

	tableName := _articleContentModel.articleContentModelDo.TableName()
	_articleContentModel.ALL = field.NewAsterisk(tableName)
	_articleContentModel.ID = field.NewUint64(tableName, "id")
	_articleContentModel.ArticleId = field.NewUint64(tableName, "article_id")
	_articleContentModel.ContentModelId = field.NewUint64(tableName, "content_model_id")
	_articleContentModel.Data = field.NewString(tableName, "data")

	_articleContentModel.fillFieldMap()

	return _articleContentModel
}

type articleContentModel struct {
	articleContentModelDo articleContentModelDo

	ALL            field.Asterisk
	ID             field.Uint64
	ArticleId      field.Uint64
	ContentModelId field.Uint64
	Data           field.String

	fieldMap map[string]field.Expr
}

func (a articleContentModel) Table(newTableName string) *articleContentModel {
	a.articleContentModelDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleContentModel) As(alias string) *articleContentModel {
	a.articleContentModelDo.DO = *(a.articleContentModelDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleContentModel) updateTableName(table string) *articleContentModel {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.ArticleId = field.NewUint64(table, "article_id")
	a.ContentModelId = field.NewUint64(table, "content_model_id")
	a.Data = field.NewString(table, "data")

	a.fillFieldMap()

	return a
}

func (a *articleContentModel) WithContext(ctx context.Context) *articleContentModelDo {
	return a.articleContentModelDo.WithContext(ctx)
}

func (a articleContentModel) TableName() string { return a.articleContentModelDo.TableName() }

func (a articleContentModel) Alias() string { return a.articleContentModelDo.Alias() }

func (a articleContentModel) Columns(cols ...field.Expr) gen.Columns {
	return a.articleContentModelDo.Columns(cols...)
}

func (a *articleContentModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleContentModel) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["id"] = a.ID
	a.fieldMap["article_id"] = a.ArticleId
	a.fieldMap["content_model_id"] = a.ContentModelId
	a.fieldMap["data"] = a.Data
}

func (a articleContentModel) clone(db *gorm.DB) articleContentModel {
	a.articleContentModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleContentModel) replaceDB(db *gorm.DB) articleContentModel {
	a.articleContentModelDo.ReplaceDB(db)
	return a
}

type articleContentModelDo struct{ gen.DO }

func (a articleContentModelDo) Debug() *articleContentModelDo {
	return a.withDO(a.DO.Debug())
}

func (a articleContentModelDo) WithContext(ctx context.Context) *articleContentModelDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleContentModelDo) ReadDB() *articleContentModelDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleContentModelDo) WriteDB() *articleContentModelDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleContentModelDo) Session(config *gorm.Session) *articleContentModelDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleContentModelDo) Clauses(conds ...clause.Expression) *articleContentModelDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleContentModelDo) Returning(value interface{}, columns ...string) *articleContentModelDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleContentModelDo) Not(conds ...gen.Condition) *articleContentModelDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleContentModelDo) Or(conds ...gen.Condition) *articleContentModelDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleContentModelDo) Select(conds ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleContentModelDo) Where(conds ...gen.Condition) *articleContentModelDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleContentModelDo) Order(conds ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleContentModelDo) Distinct(cols ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleContentModelDo) Omit(cols ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleContentModelDo) Join(table schema.Tabler, on ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleContentModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleContentModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleContentModelDo) Group(cols ...field.Expr) *articleContentModelDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleContentModelDo) Having(conds ...gen.Condition) *articleContentModelDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleContentModelDo) Limit(limit int) *articleContentModelDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleContentModelDo) Offset(offset int) *articleContentModelDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleContentModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleContentModelDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleContentModelDo) Unscoped() *articleContentModelDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleContentModelDo) Create(values ...*model.ArticleModelRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleContentModelDo) CreateInBatches(values []*model.ArticleModelRelationship, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleContentModelDo) Save(values ...*model.ArticleModelRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleContentModelDo) First() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleContentModelDo) Take() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleContentModelDo) Last() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleContentModelDo) Find() ([]*model.ArticleModelRelationship, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleModelRelationship), err
}

func (a articleContentModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModelRelationship, err error) {
	buf := make([]*model.ArticleModelRelationship, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleContentModelDo) FindInBatches(result *[]*model.ArticleModelRelationship, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleContentModelDo) Attrs(attrs ...field.AssignExpr) *articleContentModelDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleContentModelDo) Assign(attrs ...field.AssignExpr) *articleContentModelDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleContentModelDo) Joins(fields ...field.RelationField) *articleContentModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleContentModelDo) Preload(fields ...field.RelationField) *articleContentModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleContentModelDo) FirstOrInit() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleContentModelDo) FirstOrCreate() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleContentModelDo) FindByPage(offset int, limit int) (result []*model.ArticleModelRelationship, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleContentModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleContentModelDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleContentModelDo) Delete(models ...*model.ArticleModelRelationship) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleContentModelDo) withDO(do gen.Dao) *articleContentModelDo {
	a.DO = *do.(*gen.DO)
	return a
}
