// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newArticleModelData(db *gorm.DB, opts ...gen.DOOption) articleModelData {
	_articleModelData := articleModelData{}

	_articleModelData.articleModelDataDo.UseDB(db, opts...)
	_articleModelData.articleModelDataDo.UseModel(&model.ArticleModelData{})

	tableName := _articleModelData.articleModelDataDo.TableName()
	_articleModelData.ALL = field.NewAsterisk(tableName)
	_articleModelData.ID = field.NewUint64(tableName, "id")
	_articleModelData.CreatedAt = field.NewTime(tableName, "created_at")
	_articleModelData.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleModelData.DeletedAt = field.NewField(tableName, "deleted_at")
	_articleModelData.ModelId = field.NewUint64(tableName, "model_id")
	_articleModelData.ArticleId = field.NewUint64(tableName, "article_id")
	_articleModelData.FieldName = field.NewString(tableName, "field_name")
	_articleModelData.FieldKey = field.NewString(tableName, "field_key")
	_articleModelData.Type = field.NewInt16(tableName, "type")
	_articleModelData.ValueString = field.NewField(tableName, "value_string")
	_articleModelData.ValueBool = field.NewField(tableName, "value_bool")
	_articleModelData.ValueNumber = field.NewField(tableName, "value_number")
	_articleModelData.ValueTime = field.NewField(tableName, "value_time")

	_articleModelData.fillFieldMap()

	return _articleModelData
}

type articleModelData struct {
	articleModelDataDo articleModelDataDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	ModelId     field.Uint64
	ArticleId   field.Uint64
	FieldName   field.String
	FieldKey    field.String
	Type        field.Int16
	ValueString field.Field
	ValueBool   field.Field
	ValueNumber field.Field
	ValueTime   field.Field

	fieldMap map[string]field.Expr
}

func (a articleModelData) Table(newTableName string) *articleModelData {
	a.articleModelDataDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleModelData) As(alias string) *articleModelData {
	a.articleModelDataDo.DO = *(a.articleModelDataDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleModelData) updateTableName(table string) *articleModelData {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.ModelId = field.NewUint64(table, "model_id")
	a.ArticleId = field.NewUint64(table, "article_id")
	a.FieldName = field.NewString(table, "field_name")
	a.FieldKey = field.NewString(table, "field_key")
	a.Type = field.NewInt16(table, "type")
	a.ValueString = field.NewField(table, "value_string")
	a.ValueBool = field.NewField(table, "value_bool")
	a.ValueNumber = field.NewField(table, "value_number")
	a.ValueTime = field.NewField(table, "value_time")

	a.fillFieldMap()

	return a
}

func (a *articleModelData) WithContext(ctx context.Context) *articleModelDataDo {
	return a.articleModelDataDo.WithContext(ctx)
}

func (a articleModelData) TableName() string { return a.articleModelDataDo.TableName() }

func (a articleModelData) Alias() string { return a.articleModelDataDo.Alias() }

func (a articleModelData) Columns(cols ...field.Expr) gen.Columns {
	return a.articleModelDataDo.Columns(cols...)
}

func (a *articleModelData) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleModelData) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["model_id"] = a.ModelId
	a.fieldMap["article_id"] = a.ArticleId
	a.fieldMap["field_name"] = a.FieldName
	a.fieldMap["field_key"] = a.FieldKey
	a.fieldMap["type"] = a.Type
	a.fieldMap["value_string"] = a.ValueString
	a.fieldMap["value_bool"] = a.ValueBool
	a.fieldMap["value_number"] = a.ValueNumber
	a.fieldMap["value_time"] = a.ValueTime
}

func (a articleModelData) clone(db *gorm.DB) articleModelData {
	a.articleModelDataDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleModelData) replaceDB(db *gorm.DB) articleModelData {
	a.articleModelDataDo.ReplaceDB(db)
	return a
}

type articleModelDataDo struct{ gen.DO }

func (a articleModelDataDo) Debug() *articleModelDataDo {
	return a.withDO(a.DO.Debug())
}

func (a articleModelDataDo) WithContext(ctx context.Context) *articleModelDataDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleModelDataDo) ReadDB() *articleModelDataDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleModelDataDo) WriteDB() *articleModelDataDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleModelDataDo) Session(config *gorm.Session) *articleModelDataDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleModelDataDo) Clauses(conds ...clause.Expression) *articleModelDataDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleModelDataDo) Returning(value interface{}, columns ...string) *articleModelDataDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleModelDataDo) Not(conds ...gen.Condition) *articleModelDataDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleModelDataDo) Or(conds ...gen.Condition) *articleModelDataDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleModelDataDo) Select(conds ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleModelDataDo) Where(conds ...gen.Condition) *articleModelDataDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleModelDataDo) Order(conds ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleModelDataDo) Distinct(cols ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleModelDataDo) Omit(cols ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleModelDataDo) Join(table schema.Tabler, on ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleModelDataDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleModelDataDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleModelDataDo) Group(cols ...field.Expr) *articleModelDataDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleModelDataDo) Having(conds ...gen.Condition) *articleModelDataDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleModelDataDo) Limit(limit int) *articleModelDataDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleModelDataDo) Offset(offset int) *articleModelDataDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleModelDataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleModelDataDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleModelDataDo) Unscoped() *articleModelDataDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleModelDataDo) Create(values ...*model.ArticleModelData) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleModelDataDo) CreateInBatches(values []*model.ArticleModelData, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleModelDataDo) Save(values ...*model.ArticleModelData) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleModelDataDo) First() (*model.ArticleModelData, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (a articleModelDataDo) Take() (*model.ArticleModelData, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (a articleModelDataDo) Last() (*model.ArticleModelData, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (a articleModelDataDo) Find() ([]*model.ArticleModelData, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleModelData), err
}

func (a articleModelDataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModelData, err error) {
	buf := make([]*model.ArticleModelData, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleModelDataDo) FindInBatches(result *[]*model.ArticleModelData, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleModelDataDo) Attrs(attrs ...field.AssignExpr) *articleModelDataDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleModelDataDo) Assign(attrs ...field.AssignExpr) *articleModelDataDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleModelDataDo) Joins(fields ...field.RelationField) *articleModelDataDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleModelDataDo) Preload(fields ...field.RelationField) *articleModelDataDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleModelDataDo) FirstOrInit() (*model.ArticleModelData, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (a articleModelDataDo) FirstOrCreate() (*model.ArticleModelData, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (a articleModelDataDo) FindByPage(offset int, limit int) (result []*model.ArticleModelData, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleModelDataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleModelDataDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleModelDataDo) Delete(models ...*model.ArticleModelData) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleModelDataDo) withDO(do gen.Dao) *articleModelDataDo {
	a.DO = *do.(*gen.DO)
	return a
}
