// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persistence/model"
)

func newArticleModel(db *gorm.DB, opts ...gen.DOOption) articleModel {
	_articleModel := articleModel{}

	_articleModel.articleModelDo.UseDB(db, opts...)
	_articleModel.articleModelDo.UseModel(&model.ArticleModel{})

	tableName := _articleModel.articleModelDo.TableName()
	_articleModel.ALL = field.NewAsterisk(tableName)
	_articleModel.ID = field.NewUint64(tableName, "id")
	_articleModel.CreatedAt = field.NewTime(tableName, "created_at")
	_articleModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleModel.DeletedAt = field.NewField(tableName, "deleted_at")
	_articleModel.Name = field.NewString(tableName, "name")
	_articleModel.Description = field.NewString(tableName, "description")
	_articleModel.Schema = articleModelHasManySchema{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Schema", "model.ArticleModelSchema"),
	}

	_articleModel.fillFieldMap()

	return _articleModel
}

type articleModel struct {
	articleModelDo articleModelDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Name        field.String // '模型名称'
	Description field.String // '模型说明'
	Schema      articleModelHasManySchema

	fieldMap map[string]field.Expr
}

func (a articleModel) Table(newTableName string) *articleModel {
	a.articleModelDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleModel) As(alias string) *articleModel {
	a.articleModelDo.DO = *(a.articleModelDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleModel) updateTableName(table string) *articleModel {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Name = field.NewString(table, "name")
	a.Description = field.NewString(table, "description")

	a.fillFieldMap()

	return a
}

func (a *articleModel) WithContext(ctx context.Context) *articleModelDo {
	return a.articleModelDo.WithContext(ctx)
}

func (a articleModel) TableName() string { return a.articleModelDo.TableName() }

func (a articleModel) Alias() string { return a.articleModelDo.Alias() }

func (a articleModel) Columns(cols ...field.Expr) gen.Columns {
	return a.articleModelDo.Columns(cols...)
}

func (a *articleModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleModel) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["name"] = a.Name
	a.fieldMap["description"] = a.Description

}

func (a articleModel) clone(db *gorm.DB) articleModel {
	a.articleModelDo.ReplaceConnPool(db.Statement.ConnPool)
	a.Schema.db = db.Session(&gorm.Session{Initialized: true})
	a.Schema.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a articleModel) replaceDB(db *gorm.DB) articleModel {
	a.articleModelDo.ReplaceDB(db)
	a.Schema.db = db.Session(&gorm.Session{})
	return a
}

type articleModelHasManySchema struct {
	db *gorm.DB

	field.RelationField
}

func (a articleModelHasManySchema) Where(conds ...field.Expr) *articleModelHasManySchema {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a articleModelHasManySchema) WithContext(ctx context.Context) *articleModelHasManySchema {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a articleModelHasManySchema) Session(session *gorm.Session) *articleModelHasManySchema {
	a.db = a.db.Session(session)
	return &a
}

func (a articleModelHasManySchema) Model(m *model.ArticleModel) *articleModelHasManySchemaTx {
	return &articleModelHasManySchemaTx{a.db.Model(m).Association(a.Name())}
}

func (a articleModelHasManySchema) Unscoped() *articleModelHasManySchema {
	a.db = a.db.Unscoped()
	return &a
}

type articleModelHasManySchemaTx struct{ tx *gorm.Association }

func (a articleModelHasManySchemaTx) Find() (result []*model.ArticleModelSchema, err error) {
	return result, a.tx.Find(&result)
}

func (a articleModelHasManySchemaTx) Append(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a articleModelHasManySchemaTx) Replace(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a articleModelHasManySchemaTx) Delete(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a articleModelHasManySchemaTx) Clear() error {
	return a.tx.Clear()
}

func (a articleModelHasManySchemaTx) Count() int64 {
	return a.tx.Count()
}

func (a articleModelHasManySchemaTx) Unscoped() *articleModelHasManySchemaTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type articleModelDo struct{ gen.DO }

func (a articleModelDo) Debug() *articleModelDo {
	return a.withDO(a.DO.Debug())
}

func (a articleModelDo) WithContext(ctx context.Context) *articleModelDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleModelDo) ReadDB() *articleModelDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleModelDo) WriteDB() *articleModelDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleModelDo) Session(config *gorm.Session) *articleModelDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleModelDo) Clauses(conds ...clause.Expression) *articleModelDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleModelDo) Returning(value interface{}, columns ...string) *articleModelDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleModelDo) Not(conds ...gen.Condition) *articleModelDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleModelDo) Or(conds ...gen.Condition) *articleModelDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleModelDo) Select(conds ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleModelDo) Where(conds ...gen.Condition) *articleModelDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleModelDo) Order(conds ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleModelDo) Distinct(cols ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleModelDo) Omit(cols ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleModelDo) Join(table schema.Tabler, on ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleModelDo) Group(cols ...field.Expr) *articleModelDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleModelDo) Having(conds ...gen.Condition) *articleModelDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleModelDo) Limit(limit int) *articleModelDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleModelDo) Offset(offset int) *articleModelDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleModelDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleModelDo) Unscoped() *articleModelDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleModelDo) Create(values ...*model.ArticleModel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleModelDo) CreateInBatches(values []*model.ArticleModel, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleModelDo) Save(values ...*model.ArticleModel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleModelDo) First() (*model.ArticleModel, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (a articleModelDo) Take() (*model.ArticleModel, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (a articleModelDo) Last() (*model.ArticleModel, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (a articleModelDo) Find() ([]*model.ArticleModel, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleModel), err
}

func (a articleModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModel, err error) {
	buf := make([]*model.ArticleModel, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleModelDo) FindInBatches(result *[]*model.ArticleModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleModelDo) Attrs(attrs ...field.AssignExpr) *articleModelDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleModelDo) Assign(attrs ...field.AssignExpr) *articleModelDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleModelDo) Joins(fields ...field.RelationField) *articleModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleModelDo) Preload(fields ...field.RelationField) *articleModelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleModelDo) FirstOrInit() (*model.ArticleModel, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (a articleModelDo) FirstOrCreate() (*model.ArticleModel, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (a articleModelDo) FindByPage(offset int, limit int) (result []*model.ArticleModel, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleModelDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleModelDo) Delete(models ...*model.ArticleModel) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleModelDo) withDO(do gen.Dao) *articleModelDo {
	a.DO = *do.(*gen.DO)
	return a
}
