// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newArticleModelJsonData(db *gorm.DB, opts ...gen.DOOption) articleModelJsonData {
	_articleModelJsonData := articleModelJsonData{}

	_articleModelJsonData.articleModelJsonDataDo.UseDB(db, opts...)
	_articleModelJsonData.articleModelJsonDataDo.UseModel(&model.ArticleModelJsonData{})

	tableName := _articleModelJsonData.articleModelJsonDataDo.TableName()
	_articleModelJsonData.ALL = field.NewAsterisk(tableName)
	_articleModelJsonData.ID = field.NewUint64(tableName, "id")
	_articleModelJsonData.CreatedAt = field.NewTime(tableName, "created_at")
	_articleModelJsonData.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleModelJsonData.DeletedAt = field.NewField(tableName, "deleted_at")
	_articleModelJsonData.ArticleID = field.NewUint64(tableName, "article_id")
	_articleModelJsonData.ModelID = field.NewUint64(tableName, "model_id")
	_articleModelJsonData.Data = field.NewField(tableName, "data")

	_articleModelJsonData.fillFieldMap()

	return _articleModelJsonData
}

type articleModelJsonData struct {
	articleModelJsonDataDo articleModelJsonDataDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	ArticleID field.Uint64
	ModelID   field.Uint64
	Data      field.Field

	fieldMap map[string]field.Expr
}

func (a articleModelJsonData) Table(newTableName string) *articleModelJsonData {
	a.articleModelJsonDataDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleModelJsonData) As(alias string) *articleModelJsonData {
	a.articleModelJsonDataDo.DO = *(a.articleModelJsonDataDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleModelJsonData) updateTableName(table string) *articleModelJsonData {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.ArticleID = field.NewUint64(table, "article_id")
	a.ModelID = field.NewUint64(table, "model_id")
	a.Data = field.NewField(table, "data")

	a.fillFieldMap()

	return a
}

func (a *articleModelJsonData) WithContext(ctx context.Context) *articleModelJsonDataDo {
	return a.articleModelJsonDataDo.WithContext(ctx)
}

func (a articleModelJsonData) TableName() string { return a.articleModelJsonDataDo.TableName() }

func (a articleModelJsonData) Alias() string { return a.articleModelJsonDataDo.Alias() }

func (a articleModelJsonData) Columns(cols ...field.Expr) gen.Columns {
	return a.articleModelJsonDataDo.Columns(cols...)
}

func (a *articleModelJsonData) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleModelJsonData) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["model_id"] = a.ModelID
	a.fieldMap["data"] = a.Data
}

func (a articleModelJsonData) clone(db *gorm.DB) articleModelJsonData {
	a.articleModelJsonDataDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleModelJsonData) replaceDB(db *gorm.DB) articleModelJsonData {
	a.articleModelJsonDataDo.ReplaceDB(db)
	return a
}

type articleModelJsonDataDo struct{ gen.DO }

func (a articleModelJsonDataDo) Debug() *articleModelJsonDataDo {
	return a.withDO(a.DO.Debug())
}

func (a articleModelJsonDataDo) WithContext(ctx context.Context) *articleModelJsonDataDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleModelJsonDataDo) ReadDB() *articleModelJsonDataDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleModelJsonDataDo) WriteDB() *articleModelJsonDataDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleModelJsonDataDo) Session(config *gorm.Session) *articleModelJsonDataDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleModelJsonDataDo) Clauses(conds ...clause.Expression) *articleModelJsonDataDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleModelJsonDataDo) Returning(value interface{}, columns ...string) *articleModelJsonDataDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleModelJsonDataDo) Not(conds ...gen.Condition) *articleModelJsonDataDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleModelJsonDataDo) Or(conds ...gen.Condition) *articleModelJsonDataDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleModelJsonDataDo) Select(conds ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleModelJsonDataDo) Where(conds ...gen.Condition) *articleModelJsonDataDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleModelJsonDataDo) Order(conds ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleModelJsonDataDo) Distinct(cols ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleModelJsonDataDo) Omit(cols ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleModelJsonDataDo) Join(table schema.Tabler, on ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleModelJsonDataDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleModelJsonDataDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleModelJsonDataDo) Group(cols ...field.Expr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleModelJsonDataDo) Having(conds ...gen.Condition) *articleModelJsonDataDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleModelJsonDataDo) Limit(limit int) *articleModelJsonDataDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleModelJsonDataDo) Offset(offset int) *articleModelJsonDataDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleModelJsonDataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleModelJsonDataDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleModelJsonDataDo) Unscoped() *articleModelJsonDataDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleModelJsonDataDo) Create(values ...*model.ArticleModelJsonData) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleModelJsonDataDo) CreateInBatches(values []*model.ArticleModelJsonData, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleModelJsonDataDo) Save(values ...*model.ArticleModelJsonData) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleModelJsonDataDo) First() (*model.ArticleModelJsonData, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelJsonData), nil
	}
}

func (a articleModelJsonDataDo) Take() (*model.ArticleModelJsonData, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelJsonData), nil
	}
}

func (a articleModelJsonDataDo) Last() (*model.ArticleModelJsonData, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelJsonData), nil
	}
}

func (a articleModelJsonDataDo) Find() ([]*model.ArticleModelJsonData, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleModelJsonData), err
}

func (a articleModelJsonDataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModelJsonData, err error) {
	buf := make([]*model.ArticleModelJsonData, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleModelJsonDataDo) FindInBatches(result *[]*model.ArticleModelJsonData, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleModelJsonDataDo) Attrs(attrs ...field.AssignExpr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleModelJsonDataDo) Assign(attrs ...field.AssignExpr) *articleModelJsonDataDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleModelJsonDataDo) Joins(fields ...field.RelationField) *articleModelJsonDataDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleModelJsonDataDo) Preload(fields ...field.RelationField) *articleModelJsonDataDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleModelJsonDataDo) FirstOrInit() (*model.ArticleModelJsonData, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelJsonData), nil
	}
}

func (a articleModelJsonDataDo) FirstOrCreate() (*model.ArticleModelJsonData, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelJsonData), nil
	}
}

func (a articleModelJsonDataDo) FindByPage(offset int, limit int) (result []*model.ArticleModelJsonData, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleModelJsonDataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleModelJsonDataDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleModelJsonDataDo) Delete(models ...*model.ArticleModelJsonData) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleModelJsonDataDo) withDO(do gen.Dao) *articleModelJsonDataDo {
	a.DO = *do.(*gen.DO)
	return a
}
