// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newArticleModelRelationship(db *gorm.DB, opts ...gen.DOOption) articleModelRelationship {
	_articleModelRelationship := articleModelRelationship{}

	_articleModelRelationship.articleModelRelationshipDo.UseDB(db, opts...)
	_articleModelRelationship.articleModelRelationshipDo.UseModel(&model.ArticleModelRelationship{})

	tableName := _articleModelRelationship.articleModelRelationshipDo.TableName()
	_articleModelRelationship.ALL = field.NewAsterisk(tableName)
	_articleModelRelationship.ID = field.NewUint64(tableName, "id")
	_articleModelRelationship.ArticleId = field.NewUint64(tableName, "article_id")
	_articleModelRelationship.ModelId = field.NewUint64(tableName, "model_id")
	_articleModelRelationship.Data = field.NewString(tableName, "data")

	_articleModelRelationship.fillFieldMap()

	return _articleModelRelationship
}

type articleModelRelationship struct {
	articleModelRelationshipDo articleModelRelationshipDo

	ALL       field.Asterisk
	ID        field.Uint64
	ArticleId field.Uint64
	ModelId   field.Uint64
	Data      field.String

	fieldMap map[string]field.Expr
}

func (a articleModelRelationship) Table(newTableName string) *articleModelRelationship {
	a.articleModelRelationshipDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleModelRelationship) As(alias string) *articleModelRelationship {
	a.articleModelRelationshipDo.DO = *(a.articleModelRelationshipDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleModelRelationship) updateTableName(table string) *articleModelRelationship {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.ArticleId = field.NewUint64(table, "article_id")
	a.ModelId = field.NewUint64(table, "model_id")
	a.Data = field.NewString(table, "data")

	a.fillFieldMap()

	return a
}

func (a *articleModelRelationship) WithContext(ctx context.Context) *articleModelRelationshipDo {
	return a.articleModelRelationshipDo.WithContext(ctx)
}

func (a articleModelRelationship) TableName() string { return a.articleModelRelationshipDo.TableName() }

func (a articleModelRelationship) Alias() string { return a.articleModelRelationshipDo.Alias() }

func (a articleModelRelationship) Columns(cols ...field.Expr) gen.Columns {
	return a.articleModelRelationshipDo.Columns(cols...)
}

func (a *articleModelRelationship) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleModelRelationship) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["id"] = a.ID
	a.fieldMap["article_id"] = a.ArticleId
	a.fieldMap["model_id"] = a.ModelId
	a.fieldMap["data"] = a.Data
}

func (a articleModelRelationship) clone(db *gorm.DB) articleModelRelationship {
	a.articleModelRelationshipDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleModelRelationship) replaceDB(db *gorm.DB) articleModelRelationship {
	a.articleModelRelationshipDo.ReplaceDB(db)
	return a
}

type articleModelRelationshipDo struct{ gen.DO }

func (a articleModelRelationshipDo) Debug() *articleModelRelationshipDo {
	return a.withDO(a.DO.Debug())
}

func (a articleModelRelationshipDo) WithContext(ctx context.Context) *articleModelRelationshipDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleModelRelationshipDo) ReadDB() *articleModelRelationshipDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleModelRelationshipDo) WriteDB() *articleModelRelationshipDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleModelRelationshipDo) Session(config *gorm.Session) *articleModelRelationshipDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleModelRelationshipDo) Clauses(conds ...clause.Expression) *articleModelRelationshipDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleModelRelationshipDo) Returning(value interface{}, columns ...string) *articleModelRelationshipDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleModelRelationshipDo) Not(conds ...gen.Condition) *articleModelRelationshipDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleModelRelationshipDo) Or(conds ...gen.Condition) *articleModelRelationshipDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleModelRelationshipDo) Select(conds ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleModelRelationshipDo) Where(conds ...gen.Condition) *articleModelRelationshipDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleModelRelationshipDo) Order(conds ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleModelRelationshipDo) Distinct(cols ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleModelRelationshipDo) Omit(cols ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleModelRelationshipDo) Join(table schema.Tabler, on ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleModelRelationshipDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleModelRelationshipDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleModelRelationshipDo) Group(cols ...field.Expr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleModelRelationshipDo) Having(conds ...gen.Condition) *articleModelRelationshipDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleModelRelationshipDo) Limit(limit int) *articleModelRelationshipDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleModelRelationshipDo) Offset(offset int) *articleModelRelationshipDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleModelRelationshipDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleModelRelationshipDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleModelRelationshipDo) Unscoped() *articleModelRelationshipDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleModelRelationshipDo) Create(values ...*model.ArticleModelRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleModelRelationshipDo) CreateInBatches(values []*model.ArticleModelRelationship, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleModelRelationshipDo) Save(values ...*model.ArticleModelRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleModelRelationshipDo) First() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleModelRelationshipDo) Take() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleModelRelationshipDo) Last() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleModelRelationshipDo) Find() ([]*model.ArticleModelRelationship, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleModelRelationship), err
}

func (a articleModelRelationshipDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModelRelationship, err error) {
	buf := make([]*model.ArticleModelRelationship, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleModelRelationshipDo) FindInBatches(result *[]*model.ArticleModelRelationship, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleModelRelationshipDo) Attrs(attrs ...field.AssignExpr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleModelRelationshipDo) Assign(attrs ...field.AssignExpr) *articleModelRelationshipDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleModelRelationshipDo) Joins(fields ...field.RelationField) *articleModelRelationshipDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleModelRelationshipDo) Preload(fields ...field.RelationField) *articleModelRelationshipDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleModelRelationshipDo) FirstOrInit() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleModelRelationshipDo) FirstOrCreate() (*model.ArticleModelRelationship, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelRelationship), nil
	}
}

func (a articleModelRelationshipDo) FindByPage(offset int, limit int) (result []*model.ArticleModelRelationship, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleModelRelationshipDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleModelRelationshipDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleModelRelationshipDo) Delete(models ...*model.ArticleModelRelationship) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleModelRelationshipDo) withDO(do gen.Dao) *articleModelRelationshipDo {
	a.DO = *do.(*gen.DO)
	return a
}
