// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newContentModel(db *gorm.DB, opts ...gen.DOOption) contentModel {
	_contentModel := contentModel{}

	_contentModel.contentModelDo.UseDB(db, opts...)
	_contentModel.contentModelDo.UseModel(&model.ArticleModel{})

	tableName := _contentModel.contentModelDo.TableName()
	_contentModel.ALL = field.NewAsterisk(tableName)
	_contentModel.ID = field.NewUint64(tableName, "id")
	_contentModel.CreatedAt = field.NewTime(tableName, "created_at")
	_contentModel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_contentModel.DeletedAt = field.NewField(tableName, "deleted_at")
	_contentModel.Name = field.NewString(tableName, "name")
	_contentModel.Description = field.NewString(tableName, "description")
	_contentModel.Definition = contentModelHasManyDefinition{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Definition", "model.ArticleModelSchema"),
	}

	_contentModel.fillFieldMap()

	return _contentModel
}

type contentModel struct {
	contentModelDo contentModelDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Name        field.String
	Description field.String
	Definition  contentModelHasManyDefinition

	fieldMap map[string]field.Expr
}

func (c contentModel) Table(newTableName string) *contentModel {
	c.contentModelDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contentModel) As(alias string) *contentModel {
	c.contentModelDo.DO = *(c.contentModelDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contentModel) updateTableName(table string) *contentModel {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.Name = field.NewString(table, "name")
	c.Description = field.NewString(table, "description")

	c.fillFieldMap()

	return c
}

func (c *contentModel) WithContext(ctx context.Context) *contentModelDo {
	return c.contentModelDo.WithContext(ctx)
}

func (c contentModel) TableName() string { return c.contentModelDo.TableName() }

func (c contentModel) Alias() string { return c.contentModelDo.Alias() }

func (c contentModel) Columns(cols ...field.Expr) gen.Columns {
	return c.contentModelDo.Columns(cols...)
}

func (c *contentModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contentModel) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["name"] = c.Name
	c.fieldMap["description"] = c.Description

}

func (c contentModel) clone(db *gorm.DB) contentModel {
	c.contentModelDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Definition.db = db.Session(&gorm.Session{Initialized: true})
	c.Definition.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c contentModel) replaceDB(db *gorm.DB) contentModel {
	c.contentModelDo.ReplaceDB(db)
	c.Definition.db = db.Session(&gorm.Session{})
	return c
}

type contentModelHasManyDefinition struct {
	db *gorm.DB

	field.RelationField
}

func (a contentModelHasManyDefinition) Where(conds ...field.Expr) *contentModelHasManyDefinition {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a contentModelHasManyDefinition) WithContext(ctx context.Context) *contentModelHasManyDefinition {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a contentModelHasManyDefinition) Session(session *gorm.Session) *contentModelHasManyDefinition {
	a.db = a.db.Session(session)
	return &a
}

func (a contentModelHasManyDefinition) Model(m *model.ArticleModel) *contentModelHasManyDefinitionTx {
	return &contentModelHasManyDefinitionTx{a.db.Model(m).Association(a.Name())}
}

func (a contentModelHasManyDefinition) Unscoped() *contentModelHasManyDefinition {
	a.db = a.db.Unscoped()
	return &a
}

type contentModelHasManyDefinitionTx struct{ tx *gorm.Association }

func (a contentModelHasManyDefinitionTx) Find() (result []*model.ArticleModelSchema, err error) {
	return result, a.tx.Find(&result)
}

func (a contentModelHasManyDefinitionTx) Append(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a contentModelHasManyDefinitionTx) Replace(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a contentModelHasManyDefinitionTx) Delete(values ...*model.ArticleModelSchema) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a contentModelHasManyDefinitionTx) Clear() error {
	return a.tx.Clear()
}

func (a contentModelHasManyDefinitionTx) Count() int64 {
	return a.tx.Count()
}

func (a contentModelHasManyDefinitionTx) Unscoped() *contentModelHasManyDefinitionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type contentModelDo struct{ gen.DO }

func (c contentModelDo) Debug() *contentModelDo {
	return c.withDO(c.DO.Debug())
}

func (c contentModelDo) WithContext(ctx context.Context) *contentModelDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentModelDo) ReadDB() *contentModelDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentModelDo) WriteDB() *contentModelDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentModelDo) Session(config *gorm.Session) *contentModelDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentModelDo) Clauses(conds ...clause.Expression) *contentModelDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentModelDo) Returning(value interface{}, columns ...string) *contentModelDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentModelDo) Not(conds ...gen.Condition) *contentModelDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentModelDo) Or(conds ...gen.Condition) *contentModelDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentModelDo) Select(conds ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentModelDo) Where(conds ...gen.Condition) *contentModelDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentModelDo) Order(conds ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentModelDo) Distinct(cols ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentModelDo) Omit(cols ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentModelDo) Join(table schema.Tabler, on ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentModelDo) Group(cols ...field.Expr) *contentModelDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentModelDo) Having(conds ...gen.Condition) *contentModelDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentModelDo) Limit(limit int) *contentModelDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentModelDo) Offset(offset int) *contentModelDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contentModelDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentModelDo) Unscoped() *contentModelDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentModelDo) Create(values ...*model.ArticleModel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentModelDo) CreateInBatches(values []*model.ArticleModel, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentModelDo) Save(values ...*model.ArticleModel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentModelDo) First() (*model.ArticleModel, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (c contentModelDo) Take() (*model.ArticleModel, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (c contentModelDo) Last() (*model.ArticleModel, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (c contentModelDo) Find() ([]*model.ArticleModel, error) {
	result, err := c.DO.Find()
	return result.([]*model.ArticleModel), err
}

func (c contentModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModel, err error) {
	buf := make([]*model.ArticleModel, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentModelDo) FindInBatches(result *[]*model.ArticleModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentModelDo) Attrs(attrs ...field.AssignExpr) *contentModelDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentModelDo) Assign(attrs ...field.AssignExpr) *contentModelDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentModelDo) Joins(fields ...field.RelationField) *contentModelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentModelDo) Preload(fields ...field.RelationField) *contentModelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentModelDo) FirstOrInit() (*model.ArticleModel, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (c contentModelDo) FirstOrCreate() (*model.ArticleModel, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModel), nil
	}
}

func (c contentModelDo) FindByPage(offset int, limit int) (result []*model.ArticleModel, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentModelDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentModelDo) Delete(models ...*model.ArticleModel) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentModelDo) withDO(do gen.Dao) *contentModelDo {
	c.DO = *do.(*gen.DO)
	return c
}
