// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newContentModelData(db *gorm.DB, opts ...gen.DOOption) contentModelData {
	_contentModelData := contentModelData{}

	_contentModelData.contentModelDataDo.UseDB(db, opts...)
	_contentModelData.contentModelDataDo.UseModel(&model.ArticleModelData{})

	tableName := _contentModelData.contentModelDataDo.TableName()
	_contentModelData.ALL = field.NewAsterisk(tableName)
	_contentModelData.ID = field.NewUint64(tableName, "id")
	_contentModelData.ContentModelId = field.NewUint64(tableName, "content_model_id")
	_contentModelData.ArticleId = field.NewUint64(tableName, "article_id")
	_contentModelData.Field = field.NewString(tableName, "field")
	_contentModelData.ValueString = field.NewField(tableName, "value_string")
	_contentModelData.ValueNumber = field.NewField(tableName, "value_number")
	_contentModelData.ValueBool = field.NewField(tableName, "value_bool")
	_contentModelData.ValueFloat = field.NewField(tableName, "value_float")
	_contentModelData.ValueTime = field.NewField(tableName, "value_time")

	_contentModelData.fillFieldMap()

	return _contentModelData
}

type contentModelData struct {
	contentModelDataDo contentModelDataDo

	ALL            field.Asterisk
	ID             field.Uint64
	ContentModelId field.Uint64
	ArticleId      field.Uint64
	Field          field.String
	ValueString    field.Field
	ValueNumber    field.Field
	ValueBool      field.Field
	ValueFloat     field.Field
	ValueTime      field.Field

	fieldMap map[string]field.Expr
}

func (c contentModelData) Table(newTableName string) *contentModelData {
	c.contentModelDataDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contentModelData) As(alias string) *contentModelData {
	c.contentModelDataDo.DO = *(c.contentModelDataDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contentModelData) updateTableName(table string) *contentModelData {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.ContentModelId = field.NewUint64(table, "content_model_id")
	c.ArticleId = field.NewUint64(table, "article_id")
	c.Field = field.NewString(table, "field")
	c.ValueString = field.NewField(table, "value_string")
	c.ValueNumber = field.NewField(table, "value_number")
	c.ValueBool = field.NewField(table, "value_bool")
	c.ValueFloat = field.NewField(table, "value_float")
	c.ValueTime = field.NewField(table, "value_time")

	c.fillFieldMap()

	return c
}

func (c *contentModelData) WithContext(ctx context.Context) *contentModelDataDo {
	return c.contentModelDataDo.WithContext(ctx)
}

func (c contentModelData) TableName() string { return c.contentModelDataDo.TableName() }

func (c contentModelData) Alias() string { return c.contentModelDataDo.Alias() }

func (c contentModelData) Columns(cols ...field.Expr) gen.Columns {
	return c.contentModelDataDo.Columns(cols...)
}

func (c *contentModelData) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contentModelData) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["content_model_id"] = c.ContentModelId
	c.fieldMap["article_id"] = c.ArticleId
	c.fieldMap["field"] = c.Field
	c.fieldMap["value_string"] = c.ValueString
	c.fieldMap["value_number"] = c.ValueNumber
	c.fieldMap["value_bool"] = c.ValueBool
	c.fieldMap["value_float"] = c.ValueFloat
	c.fieldMap["value_time"] = c.ValueTime
}

func (c contentModelData) clone(db *gorm.DB) contentModelData {
	c.contentModelDataDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contentModelData) replaceDB(db *gorm.DB) contentModelData {
	c.contentModelDataDo.ReplaceDB(db)
	return c
}

type contentModelDataDo struct{ gen.DO }

func (c contentModelDataDo) Debug() *contentModelDataDo {
	return c.withDO(c.DO.Debug())
}

func (c contentModelDataDo) WithContext(ctx context.Context) *contentModelDataDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentModelDataDo) ReadDB() *contentModelDataDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentModelDataDo) WriteDB() *contentModelDataDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentModelDataDo) Session(config *gorm.Session) *contentModelDataDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentModelDataDo) Clauses(conds ...clause.Expression) *contentModelDataDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentModelDataDo) Returning(value interface{}, columns ...string) *contentModelDataDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentModelDataDo) Not(conds ...gen.Condition) *contentModelDataDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentModelDataDo) Or(conds ...gen.Condition) *contentModelDataDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentModelDataDo) Select(conds ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentModelDataDo) Where(conds ...gen.Condition) *contentModelDataDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentModelDataDo) Order(conds ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentModelDataDo) Distinct(cols ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentModelDataDo) Omit(cols ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentModelDataDo) Join(table schema.Tabler, on ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentModelDataDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentModelDataDo) RightJoin(table schema.Tabler, on ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentModelDataDo) Group(cols ...field.Expr) *contentModelDataDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentModelDataDo) Having(conds ...gen.Condition) *contentModelDataDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentModelDataDo) Limit(limit int) *contentModelDataDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentModelDataDo) Offset(offset int) *contentModelDataDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentModelDataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contentModelDataDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentModelDataDo) Unscoped() *contentModelDataDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentModelDataDo) Create(values ...*model.ArticleModelData) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentModelDataDo) CreateInBatches(values []*model.ArticleModelData, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentModelDataDo) Save(values ...*model.ArticleModelData) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentModelDataDo) First() (*model.ArticleModelData, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (c contentModelDataDo) Take() (*model.ArticleModelData, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (c contentModelDataDo) Last() (*model.ArticleModelData, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (c contentModelDataDo) Find() ([]*model.ArticleModelData, error) {
	result, err := c.DO.Find()
	return result.([]*model.ArticleModelData), err
}

func (c contentModelDataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModelData, err error) {
	buf := make([]*model.ArticleModelData, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentModelDataDo) FindInBatches(result *[]*model.ArticleModelData, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentModelDataDo) Attrs(attrs ...field.AssignExpr) *contentModelDataDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentModelDataDo) Assign(attrs ...field.AssignExpr) *contentModelDataDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentModelDataDo) Joins(fields ...field.RelationField) *contentModelDataDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentModelDataDo) Preload(fields ...field.RelationField) *contentModelDataDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentModelDataDo) FirstOrInit() (*model.ArticleModelData, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (c contentModelDataDo) FirstOrCreate() (*model.ArticleModelData, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelData), nil
	}
}

func (c contentModelDataDo) FindByPage(offset int, limit int) (result []*model.ArticleModelData, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentModelDataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentModelDataDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentModelDataDo) Delete(models ...*model.ArticleModelData) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentModelDataDo) withDO(do gen.Dao) *contentModelDataDo {
	c.DO = *do.(*gen.DO)
	return c
}
