// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newMenuContext(db *gorm.DB, opts ...gen.DOOption) menuContext {
	_menuContext := menuContext{}

	_menuContext.menuContextDo.UseDB(db, opts...)
	_menuContext.menuContextDo.UseModel(&model.MenuContext{})

	tableName := _menuContext.menuContextDo.TableName()
	_menuContext.ALL = field.NewAsterisk(tableName)
	_menuContext.ID = field.NewUint64(tableName, "id")
	_menuContext.Ancestor = field.NewUint64(tableName, "ancestor")
	_menuContext.Descendant = field.NewUint64(tableName, "descendant")
	_menuContext.Distance = field.NewUint64(tableName, "distance")

	_menuContext.fillFieldMap()

	return _menuContext
}

type menuContext struct {
	menuContextDo menuContextDo

	ALL        field.Asterisk
	ID         field.Uint64
	Ancestor   field.Uint64
	Descendant field.Uint64
	Distance   field.Uint64

	fieldMap map[string]field.Expr
}

func (m menuContext) Table(newTableName string) *menuContext {
	m.menuContextDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menuContext) As(alias string) *menuContext {
	m.menuContextDo.DO = *(m.menuContextDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menuContext) updateTableName(table string) *menuContext {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint64(table, "id")
	m.Ancestor = field.NewUint64(table, "ancestor")
	m.Descendant = field.NewUint64(table, "descendant")
	m.Distance = field.NewUint64(table, "distance")

	m.fillFieldMap()

	return m
}

func (m *menuContext) WithContext(ctx context.Context) *menuContextDo {
	return m.menuContextDo.WithContext(ctx)
}

func (m menuContext) TableName() string { return m.menuContextDo.TableName() }

func (m menuContext) Alias() string { return m.menuContextDo.Alias() }

func (m menuContext) Columns(cols ...field.Expr) gen.Columns { return m.menuContextDo.Columns(cols...) }

func (m *menuContext) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menuContext) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["id"] = m.ID
	m.fieldMap["ancestor"] = m.Ancestor
	m.fieldMap["descendant"] = m.Descendant
	m.fieldMap["distance"] = m.Distance
}

func (m menuContext) clone(db *gorm.DB) menuContext {
	m.menuContextDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menuContext) replaceDB(db *gorm.DB) menuContext {
	m.menuContextDo.ReplaceDB(db)
	return m
}

type menuContextDo struct{ gen.DO }

// INSERT INTO @@table (ancestor, descendant, distance)
// SELECT @id, @id, 0, @ancestor
// {{ if ancestor > 0 }}
// UNION ALL
// SELECT ancestor, @id, distance + 1, @ancestor
// FROM @@table
// WHERE descendant = @ancestor
// {{ end }}
func (m menuContextDo) CreateSubtree(id uint64, ancestor uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	params = append(params, id)
	params = append(params, ancestor)
	generateSQL.WriteString("INSERT INTO menu_context (ancestor, descendant, distance) SELECT ?, ?, 0, ? ")
	if ancestor > 0 {
		params = append(params, id)
		params = append(params, ancestor)
		params = append(params, ancestor)
		generateSQL.WriteString("UNION ALL SELECT ancestor, ?, distance + 1, ? FROM menu_context WHERE descendant = ? ")
	}

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE ancestor IN (
// SELECT descendant FROM @@table WHERE ancestor=@ancestor
// ) OR descendant IN (
// SELECT descendant FROM @@table WHERE ancestor=@ancestor
// )
func (m menuContextDo) DropSubtree(ancestor uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, ancestor)
	params = append(params, ancestor)
	generateSQL.WriteString("DELETE FROM menu_context WHERE ancestor IN ( SELECT descendant FROM menu_context WHERE ancestor=? ) OR descendant IN ( SELECT descendant FROM menu_context WHERE ancestor=? ) ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE descendant IN (
// SELECT d FROM ( SELECT descendant AS d FROM @@table WHERE ancestor=@ancestor ) AS DCT
// ) AND ancestor IN (
// SELECT a FROM ( SELECT ancestor AS a FROM @@table WHERE descendant=@ancestor AND ancestor<>@ancestor ) AS ACT
// )
func (m menuContextDo) UnbindRelationships(ancestor uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, ancestor)
	params = append(params, ancestor)
	params = append(params, ancestor)
	generateSQL.WriteString("DELETE FROM menu_context WHERE descendant IN ( SELECT d FROM ( SELECT descendant AS d FROM menu_context WHERE ancestor=? ) AS DCT ) AND ancestor IN ( SELECT a FROM ( SELECT ancestor AS a FROM menu_context WHERE descendant=? AND ancestor<>? ) AS ACT ) ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// INSERT INTO @@table(ancestor, descendant, distance) SELECT A.ancestor, D.descendant, A.distance + D.distance + 1 FROM @@table AS A
// CROSS JOIN @@table AS D WHERE A.descendant = @target AND D.ancestor = @ancestor
func (m menuContextDo) ReBindRelationships(ancestor uint64, target uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, target)
	params = append(params, ancestor)
	generateSQL.WriteString("INSERT INTO menu_context(ancestor, descendant, distance) SELECT A.ancestor, D.descendant, A.distance + D.distance + 1 FROM menu_context AS A CROSS JOIN menu_context AS D WHERE A.descendant = ? AND D.ancestor = ? ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (m menuContextDo) Debug() *menuContextDo {
	return m.withDO(m.DO.Debug())
}

func (m menuContextDo) WithContext(ctx context.Context) *menuContextDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menuContextDo) ReadDB() *menuContextDo {
	return m.Clauses(dbresolver.Read)
}

func (m menuContextDo) WriteDB() *menuContextDo {
	return m.Clauses(dbresolver.Write)
}

func (m menuContextDo) Session(config *gorm.Session) *menuContextDo {
	return m.withDO(m.DO.Session(config))
}

func (m menuContextDo) Clauses(conds ...clause.Expression) *menuContextDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menuContextDo) Returning(value interface{}, columns ...string) *menuContextDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menuContextDo) Not(conds ...gen.Condition) *menuContextDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menuContextDo) Or(conds ...gen.Condition) *menuContextDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menuContextDo) Select(conds ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menuContextDo) Where(conds ...gen.Condition) *menuContextDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menuContextDo) Order(conds ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menuContextDo) Distinct(cols ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menuContextDo) Omit(cols ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menuContextDo) Join(table schema.Tabler, on ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menuContextDo) LeftJoin(table schema.Tabler, on ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menuContextDo) RightJoin(table schema.Tabler, on ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menuContextDo) Group(cols ...field.Expr) *menuContextDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menuContextDo) Having(conds ...gen.Condition) *menuContextDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menuContextDo) Limit(limit int) *menuContextDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menuContextDo) Offset(offset int) *menuContextDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menuContextDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *menuContextDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menuContextDo) Unscoped() *menuContextDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menuContextDo) Create(values ...*model.MenuContext) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menuContextDo) CreateInBatches(values []*model.MenuContext, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).CreateModel(values)
func (m menuContextDo) Save(values ...*model.MenuContext) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menuContextDo) First() (*model.MenuContext, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuContext), nil
	}
}

func (m menuContextDo) Take() (*model.MenuContext, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuContext), nil
	}
}

func (m menuContextDo) Last() (*model.MenuContext, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuContext), nil
	}
}

func (m menuContextDo) Find() ([]*model.MenuContext, error) {
	result, err := m.DO.Find()
	return result.([]*model.MenuContext), err
}

func (m menuContextDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenuContext, err error) {
	buf := make([]*model.MenuContext, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menuContextDo) FindInBatches(result *[]*model.MenuContext, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menuContextDo) Attrs(attrs ...field.AssignExpr) *menuContextDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menuContextDo) Assign(attrs ...field.AssignExpr) *menuContextDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menuContextDo) Joins(fields ...field.RelationField) *menuContextDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menuContextDo) Preload(fields ...field.RelationField) *menuContextDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menuContextDo) FirstOrInit() (*model.MenuContext, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuContext), nil
	}
}

func (m menuContextDo) FirstOrCreate() (*model.MenuContext, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuContext), nil
	}
}

func (m menuContextDo) FindByPage(offset int, limit int) (result []*model.MenuContext, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menuContextDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menuContextDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menuContextDo) Delete(models ...*model.MenuContext) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menuContextDo) withDO(do gen.Dao) *menuContextDo {
	m.DO = *do.(*gen.DO)
	return m
}
