// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/internal/infra/persistence/model"
)

func newUploadRecords(db *gorm.DB, opts ...gen.DOOption) uploadRecords {
	_uploadRecords := uploadRecords{}

	_uploadRecords.uploadRecordsDo.UseDB(db, opts...)
	_uploadRecords.uploadRecordsDo.UseModel(&model.UploadRecords{})

	tableName := _uploadRecords.uploadRecordsDo.TableName()
	_uploadRecords.ALL = field.NewAsterisk(tableName)
	_uploadRecords.ID = field.NewUint64(tableName, "id")
	_uploadRecords.CreatedAt = field.NewTime(tableName, "created_at")
	_uploadRecords.UpdatedAt = field.NewTime(tableName, "updated_at")
	_uploadRecords.DeletedAt = field.NewField(tableName, "deleted_at")
	_uploadRecords.UserID = field.NewUint64(tableName, "user_id")
	_uploadRecords.FileID = field.NewUint64(tableName, "file_id")
	_uploadRecords.Description = field.NewString(tableName, "description")

	_uploadRecords.fillFieldMap()

	return _uploadRecords
}

type uploadRecords struct {
	uploadRecordsDo uploadRecordsDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	UserID      field.Uint64
	FileID      field.Uint64
	Description field.String

	fieldMap map[string]field.Expr
}

func (u uploadRecords) Table(newTableName string) *uploadRecords {
	u.uploadRecordsDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u uploadRecords) As(alias string) *uploadRecords {
	u.uploadRecordsDo.DO = *(u.uploadRecordsDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *uploadRecords) updateTableName(table string) *uploadRecords {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint64(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.UserID = field.NewUint64(table, "user_id")
	u.FileID = field.NewUint64(table, "file_id")
	u.Description = field.NewString(table, "description")

	u.fillFieldMap()

	return u
}

func (u *uploadRecords) WithContext(ctx context.Context) *uploadRecordsDo {
	return u.uploadRecordsDo.WithContext(ctx)
}

func (u uploadRecords) TableName() string { return u.uploadRecordsDo.TableName() }

func (u uploadRecords) Alias() string { return u.uploadRecordsDo.Alias() }

func (u uploadRecords) Columns(cols ...field.Expr) gen.Columns {
	return u.uploadRecordsDo.Columns(cols...)
}

func (u *uploadRecords) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *uploadRecords) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["file_id"] = u.FileID
	u.fieldMap["description"] = u.Description
}

func (u uploadRecords) clone(db *gorm.DB) uploadRecords {
	u.uploadRecordsDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u uploadRecords) replaceDB(db *gorm.DB) uploadRecords {
	u.uploadRecordsDo.ReplaceDB(db)
	return u
}

type uploadRecordsDo struct{ gen.DO }

func (u uploadRecordsDo) Debug() *uploadRecordsDo {
	return u.withDO(u.DO.Debug())
}

func (u uploadRecordsDo) WithContext(ctx context.Context) *uploadRecordsDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u uploadRecordsDo) ReadDB() *uploadRecordsDo {
	return u.Clauses(dbresolver.Read)
}

func (u uploadRecordsDo) WriteDB() *uploadRecordsDo {
	return u.Clauses(dbresolver.Write)
}

func (u uploadRecordsDo) Session(config *gorm.Session) *uploadRecordsDo {
	return u.withDO(u.DO.Session(config))
}

func (u uploadRecordsDo) Clauses(conds ...clause.Expression) *uploadRecordsDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u uploadRecordsDo) Returning(value interface{}, columns ...string) *uploadRecordsDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u uploadRecordsDo) Not(conds ...gen.Condition) *uploadRecordsDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u uploadRecordsDo) Or(conds ...gen.Condition) *uploadRecordsDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u uploadRecordsDo) Select(conds ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u uploadRecordsDo) Where(conds ...gen.Condition) *uploadRecordsDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u uploadRecordsDo) Order(conds ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u uploadRecordsDo) Distinct(cols ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u uploadRecordsDo) Omit(cols ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u uploadRecordsDo) Join(table schema.Tabler, on ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u uploadRecordsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u uploadRecordsDo) RightJoin(table schema.Tabler, on ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u uploadRecordsDo) Group(cols ...field.Expr) *uploadRecordsDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u uploadRecordsDo) Having(conds ...gen.Condition) *uploadRecordsDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u uploadRecordsDo) Limit(limit int) *uploadRecordsDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u uploadRecordsDo) Offset(offset int) *uploadRecordsDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u uploadRecordsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *uploadRecordsDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u uploadRecordsDo) Unscoped() *uploadRecordsDo {
	return u.withDO(u.DO.Unscoped())
}

func (u uploadRecordsDo) Create(values ...*model.UploadRecords) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u uploadRecordsDo) CreateInBatches(values []*model.UploadRecords, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u uploadRecordsDo) Save(values ...*model.UploadRecords) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u uploadRecordsDo) First() (*model.UploadRecords, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadRecords), nil
	}
}

func (u uploadRecordsDo) Take() (*model.UploadRecords, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadRecords), nil
	}
}

func (u uploadRecordsDo) Last() (*model.UploadRecords, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadRecords), nil
	}
}

func (u uploadRecordsDo) Find() ([]*model.UploadRecords, error) {
	result, err := u.DO.Find()
	return result.([]*model.UploadRecords), err
}

func (u uploadRecordsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UploadRecords, err error) {
	buf := make([]*model.UploadRecords, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u uploadRecordsDo) FindInBatches(result *[]*model.UploadRecords, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u uploadRecordsDo) Attrs(attrs ...field.AssignExpr) *uploadRecordsDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u uploadRecordsDo) Assign(attrs ...field.AssignExpr) *uploadRecordsDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u uploadRecordsDo) Joins(fields ...field.RelationField) *uploadRecordsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u uploadRecordsDo) Preload(fields ...field.RelationField) *uploadRecordsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u uploadRecordsDo) FirstOrInit() (*model.UploadRecords, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadRecords), nil
	}
}

func (u uploadRecordsDo) FirstOrCreate() (*model.UploadRecords, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadRecords), nil
	}
}

func (u uploadRecordsDo) FindByPage(offset int, limit int) (result []*model.UploadRecords, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u uploadRecordsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u uploadRecordsDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u uploadRecordsDo) Delete(models ...*model.UploadRecords) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *uploadRecordsDo) withDO(do gen.Dao) *uploadRecordsDo {
	u.DO = *do.(*gen.DO)
	return u
}
