// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/public/model"
)

func newArticlePublish(db *gorm.DB, opts ...gen.DOOption) articlePublish {
	_articlePublish := articlePublish{}

	_articlePublish.articlePublishDo.UseDB(db, opts...)
	_articlePublish.articlePublishDo.UseModel(&model.ArticlePublish{})

	tableName := _articlePublish.articlePublishDo.TableName()
	_articlePublish.ALL = field.NewAsterisk(tableName)
	_articlePublish.ID = field.NewUint64(tableName, "id")
	_articlePublish.CreatedAt = field.NewTime(tableName, "created_at")
	_articlePublish.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articlePublish.DeletedAt = field.NewTime(tableName, "deleted_at")
	_articlePublish.PublishAt = field.NewTime(tableName, "publish_at")
	_articlePublish.ArticleID = field.NewUint64(tableName, "article_id")
	_articlePublish.VersionID = field.NewUint64(tableName, "version_id")
	_articlePublish.PublishType = field.NewInt8(tableName, "publish_type")
	_articlePublish.Remark = field.NewString(tableName, "remark")

	_articlePublish.fillFieldMap()

	return _articlePublish
}

type articlePublish struct {
	articlePublishDo articlePublishDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Time
	PublishAt   field.Time
	ArticleID   field.Uint64
	VersionID   field.Uint64
	PublishType field.Int8
	Remark      field.String

	fieldMap map[string]field.Expr
}

func (a articlePublish) Table(newTableName string) *articlePublish {
	a.articlePublishDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articlePublish) As(alias string) *articlePublish {
	a.articlePublishDo.DO = *(a.articlePublishDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articlePublish) updateTableName(table string) *articlePublish {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewTime(table, "deleted_at")
	a.PublishAt = field.NewTime(table, "publish_at")
	a.ArticleID = field.NewUint64(table, "article_id")
	a.VersionID = field.NewUint64(table, "version_id")
	a.PublishType = field.NewInt8(table, "publish_type")
	a.Remark = field.NewString(table, "remark")

	a.fillFieldMap()

	return a
}

func (a *articlePublish) WithContext(ctx context.Context) *articlePublishDo {
	return a.articlePublishDo.WithContext(ctx)
}

func (a articlePublish) TableName() string { return a.articlePublishDo.TableName() }

func (a articlePublish) Alias() string { return a.articlePublishDo.Alias() }

func (a articlePublish) Columns(cols ...field.Expr) gen.Columns {
	return a.articlePublishDo.Columns(cols...)
}

func (a *articlePublish) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articlePublish) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["publish_at"] = a.PublishAt
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["version_id"] = a.VersionID
	a.fieldMap["publish_type"] = a.PublishType
	a.fieldMap["remark"] = a.Remark
}

func (a articlePublish) clone(db *gorm.DB) articlePublish {
	a.articlePublishDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articlePublish) replaceDB(db *gorm.DB) articlePublish {
	a.articlePublishDo.ReplaceDB(db)
	return a
}

type articlePublishDo struct{ gen.DO }

func (a articlePublishDo) Debug() *articlePublishDo {
	return a.withDO(a.DO.Debug())
}

func (a articlePublishDo) WithContext(ctx context.Context) *articlePublishDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articlePublishDo) ReadDB() *articlePublishDo {
	return a.Clauses(dbresolver.Read)
}

func (a articlePublishDo) WriteDB() *articlePublishDo {
	return a.Clauses(dbresolver.Write)
}

func (a articlePublishDo) Session(config *gorm.Session) *articlePublishDo {
	return a.withDO(a.DO.Session(config))
}

func (a articlePublishDo) Clauses(conds ...clause.Expression) *articlePublishDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articlePublishDo) Returning(value interface{}, columns ...string) *articlePublishDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articlePublishDo) Not(conds ...gen.Condition) *articlePublishDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articlePublishDo) Or(conds ...gen.Condition) *articlePublishDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articlePublishDo) Select(conds ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articlePublishDo) Where(conds ...gen.Condition) *articlePublishDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articlePublishDo) Order(conds ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articlePublishDo) Distinct(cols ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articlePublishDo) Omit(cols ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articlePublishDo) Join(table schema.Tabler, on ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articlePublishDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articlePublishDo) RightJoin(table schema.Tabler, on ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articlePublishDo) Group(cols ...field.Expr) *articlePublishDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articlePublishDo) Having(conds ...gen.Condition) *articlePublishDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articlePublishDo) Limit(limit int) *articlePublishDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articlePublishDo) Offset(offset int) *articlePublishDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articlePublishDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articlePublishDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articlePublishDo) Unscoped() *articlePublishDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articlePublishDo) Create(values ...*model.ArticlePublish) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articlePublishDo) CreateInBatches(values []*model.ArticlePublish, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articlePublishDo) Save(values ...*model.ArticlePublish) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articlePublishDo) First() (*model.ArticlePublish, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticlePublish), nil
	}
}

func (a articlePublishDo) Take() (*model.ArticlePublish, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticlePublish), nil
	}
}

func (a articlePublishDo) Last() (*model.ArticlePublish, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticlePublish), nil
	}
}

func (a articlePublishDo) Find() ([]*model.ArticlePublish, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticlePublish), err
}

func (a articlePublishDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticlePublish, err error) {
	buf := make([]*model.ArticlePublish, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articlePublishDo) FindInBatches(result *[]*model.ArticlePublish, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articlePublishDo) Attrs(attrs ...field.AssignExpr) *articlePublishDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articlePublishDo) Assign(attrs ...field.AssignExpr) *articlePublishDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articlePublishDo) Joins(fields ...field.RelationField) *articlePublishDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articlePublishDo) Preload(fields ...field.RelationField) *articlePublishDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articlePublishDo) FirstOrInit() (*model.ArticlePublish, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticlePublish), nil
	}
}

func (a articlePublishDo) FirstOrCreate() (*model.ArticlePublish, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticlePublish), nil
	}
}

func (a articlePublishDo) FindByPage(offset int, limit int) (result []*model.ArticlePublish, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articlePublishDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articlePublishDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articlePublishDo) Delete(models ...*model.ArticlePublish) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articlePublishDo) withDO(do gen.Dao) *articlePublishDo {
	a.DO = *do.(*gen.DO)
	return a
}
