// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/public/model"
)

func newArticleCategoryRel(db *gorm.DB, opts ...gen.DOOption) articleCategoryRel {
	_articleCategoryRel := articleCategoryRel{}

	_articleCategoryRel.articleCategoryRelDo.UseDB(db, opts...)
	_articleCategoryRel.articleCategoryRelDo.UseModel(&model.ArticleCategoryRel{})

	tableName := _articleCategoryRel.articleCategoryRelDo.TableName()
	_articleCategoryRel.ALL = field.NewAsterisk(tableName)
	_articleCategoryRel.ArticleID = field.NewUint64(tableName, "article_id")
	_articleCategoryRel.CategoryID = field.NewUint64(tableName, "category_id")

	_articleCategoryRel.fillFieldMap()

	return _articleCategoryRel
}

type articleCategoryRel struct {
	articleCategoryRelDo articleCategoryRelDo

	ALL        field.Asterisk
	ArticleID  field.Uint64
	CategoryID field.Uint64

	fieldMap map[string]field.Expr
}

func (a articleCategoryRel) Table(newTableName string) *articleCategoryRel {
	a.articleCategoryRelDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleCategoryRel) As(alias string) *articleCategoryRel {
	a.articleCategoryRelDo.DO = *(a.articleCategoryRelDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleCategoryRel) updateTableName(table string) *articleCategoryRel {
	a.ALL = field.NewAsterisk(table)
	a.ArticleID = field.NewUint64(table, "article_id")
	a.CategoryID = field.NewUint64(table, "category_id")

	a.fillFieldMap()

	return a
}

func (a *articleCategoryRel) WithContext(ctx context.Context) *articleCategoryRelDo {
	return a.articleCategoryRelDo.WithContext(ctx)
}

func (a articleCategoryRel) TableName() string { return a.articleCategoryRelDo.TableName() }

func (a articleCategoryRel) Alias() string { return a.articleCategoryRelDo.Alias() }

func (a articleCategoryRel) Columns(cols ...field.Expr) gen.Columns {
	return a.articleCategoryRelDo.Columns(cols...)
}

func (a *articleCategoryRel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleCategoryRel) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 2)
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["category_id"] = a.CategoryID
}

func (a articleCategoryRel) clone(db *gorm.DB) articleCategoryRel {
	a.articleCategoryRelDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleCategoryRel) replaceDB(db *gorm.DB) articleCategoryRel {
	a.articleCategoryRelDo.ReplaceDB(db)
	return a
}

type articleCategoryRelDo struct{ gen.DO }

func (a articleCategoryRelDo) Debug() *articleCategoryRelDo {
	return a.withDO(a.DO.Debug())
}

func (a articleCategoryRelDo) WithContext(ctx context.Context) *articleCategoryRelDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleCategoryRelDo) ReadDB() *articleCategoryRelDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleCategoryRelDo) WriteDB() *articleCategoryRelDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleCategoryRelDo) Session(config *gorm.Session) *articleCategoryRelDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleCategoryRelDo) Clauses(conds ...clause.Expression) *articleCategoryRelDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleCategoryRelDo) Returning(value interface{}, columns ...string) *articleCategoryRelDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleCategoryRelDo) Not(conds ...gen.Condition) *articleCategoryRelDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleCategoryRelDo) Or(conds ...gen.Condition) *articleCategoryRelDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleCategoryRelDo) Select(conds ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleCategoryRelDo) Where(conds ...gen.Condition) *articleCategoryRelDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleCategoryRelDo) Order(conds ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleCategoryRelDo) Distinct(cols ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleCategoryRelDo) Omit(cols ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleCategoryRelDo) Join(table schema.Tabler, on ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleCategoryRelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleCategoryRelDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleCategoryRelDo) Group(cols ...field.Expr) *articleCategoryRelDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleCategoryRelDo) Having(conds ...gen.Condition) *articleCategoryRelDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleCategoryRelDo) Limit(limit int) *articleCategoryRelDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleCategoryRelDo) Offset(offset int) *articleCategoryRelDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleCategoryRelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleCategoryRelDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleCategoryRelDo) Unscoped() *articleCategoryRelDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleCategoryRelDo) Create(values ...*model.ArticleCategoryRel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleCategoryRelDo) CreateInBatches(values []*model.ArticleCategoryRel, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleCategoryRelDo) Save(values ...*model.ArticleCategoryRel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleCategoryRelDo) First() (*model.ArticleCategoryRel, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleCategoryRel), nil
	}
}

func (a articleCategoryRelDo) Take() (*model.ArticleCategoryRel, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleCategoryRel), nil
	}
}

func (a articleCategoryRelDo) Last() (*model.ArticleCategoryRel, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleCategoryRel), nil
	}
}

func (a articleCategoryRelDo) Find() ([]*model.ArticleCategoryRel, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleCategoryRel), err
}

func (a articleCategoryRelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleCategoryRel, err error) {
	buf := make([]*model.ArticleCategoryRel, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleCategoryRelDo) FindInBatches(result *[]*model.ArticleCategoryRel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleCategoryRelDo) Attrs(attrs ...field.AssignExpr) *articleCategoryRelDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleCategoryRelDo) Assign(attrs ...field.AssignExpr) *articleCategoryRelDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleCategoryRelDo) Joins(fields ...field.RelationField) *articleCategoryRelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleCategoryRelDo) Preload(fields ...field.RelationField) *articleCategoryRelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleCategoryRelDo) FirstOrInit() (*model.ArticleCategoryRel, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleCategoryRel), nil
	}
}

func (a articleCategoryRelDo) FirstOrCreate() (*model.ArticleCategoryRel, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleCategoryRel), nil
	}
}

func (a articleCategoryRelDo) FindByPage(offset int, limit int) (result []*model.ArticleCategoryRel, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleCategoryRelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleCategoryRelDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleCategoryRelDo) Delete(models ...*model.ArticleCategoryRel) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleCategoryRelDo) withDO(do gen.Dao) *articleCategoryRelDo {
	a.DO = *do.(*gen.DO)
	return a
}
