// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/public/model"
)

func newArticleVersion(db *gorm.DB, opts ...gen.DOOption) articleVersion {
	_articleVersion := articleVersion{}

	_articleVersion.articleVersionDo.UseDB(db, opts...)
	_articleVersion.articleVersionDo.UseModel(&model.ArticleVersion{})

	tableName := _articleVersion.articleVersionDo.TableName()
	_articleVersion.ALL = field.NewAsterisk(tableName)
	_articleVersion.ID = field.NewUint64(tableName, "id")
	_articleVersion.CreatedAt = field.NewTime(tableName, "created_at")
	_articleVersion.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleVersion.DeletedAt = field.NewTime(tableName, "deleted_at")
	_articleVersion.ArticleID = field.NewUint64(tableName, "article_id")
	_articleVersion.VersionNo = field.NewUint32(tableName, "version_no")
	_articleVersion.Title = field.NewString(tableName, "title")
	_articleVersion.Content = field.NewString(tableName, "content")
	_articleVersion.Summary = field.NewString(tableName, "summary")
	_articleVersion.ChangeLog = field.NewString(tableName, "change_log")

	_articleVersion.fillFieldMap()

	return _articleVersion
}

type articleVersion struct {
	articleVersionDo articleVersionDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Time
	ArticleID field.Uint64
	VersionNo field.Uint32
	Title     field.String
	Content   field.String
	Summary   field.String
	ChangeLog field.String

	fieldMap map[string]field.Expr
}

func (a articleVersion) Table(newTableName string) *articleVersion {
	a.articleVersionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleVersion) As(alias string) *articleVersion {
	a.articleVersionDo.DO = *(a.articleVersionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleVersion) updateTableName(table string) *articleVersion {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewTime(table, "deleted_at")
	a.ArticleID = field.NewUint64(table, "article_id")
	a.VersionNo = field.NewUint32(table, "version_no")
	a.Title = field.NewString(table, "title")
	a.Content = field.NewString(table, "content")
	a.Summary = field.NewString(table, "summary")
	a.ChangeLog = field.NewString(table, "change_log")

	a.fillFieldMap()

	return a
}

func (a *articleVersion) WithContext(ctx context.Context) *articleVersionDo {
	return a.articleVersionDo.WithContext(ctx)
}

func (a articleVersion) TableName() string { return a.articleVersionDo.TableName() }

func (a articleVersion) Alias() string { return a.articleVersionDo.Alias() }

func (a articleVersion) Columns(cols ...field.Expr) gen.Columns {
	return a.articleVersionDo.Columns(cols...)
}

func (a *articleVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleVersion) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["version_no"] = a.VersionNo
	a.fieldMap["title"] = a.Title
	a.fieldMap["content"] = a.Content
	a.fieldMap["summary"] = a.Summary
	a.fieldMap["change_log"] = a.ChangeLog
}

func (a articleVersion) clone(db *gorm.DB) articleVersion {
	a.articleVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleVersion) replaceDB(db *gorm.DB) articleVersion {
	a.articleVersionDo.ReplaceDB(db)
	return a
}

type articleVersionDo struct{ gen.DO }

func (a articleVersionDo) Debug() *articleVersionDo {
	return a.withDO(a.DO.Debug())
}

func (a articleVersionDo) WithContext(ctx context.Context) *articleVersionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleVersionDo) ReadDB() *articleVersionDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleVersionDo) WriteDB() *articleVersionDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleVersionDo) Session(config *gorm.Session) *articleVersionDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleVersionDo) Clauses(conds ...clause.Expression) *articleVersionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleVersionDo) Returning(value interface{}, columns ...string) *articleVersionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleVersionDo) Not(conds ...gen.Condition) *articleVersionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleVersionDo) Or(conds ...gen.Condition) *articleVersionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleVersionDo) Select(conds ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleVersionDo) Where(conds ...gen.Condition) *articleVersionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleVersionDo) Order(conds ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleVersionDo) Distinct(cols ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleVersionDo) Omit(cols ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleVersionDo) Join(table schema.Tabler, on ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleVersionDo) Group(cols ...field.Expr) *articleVersionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleVersionDo) Having(conds ...gen.Condition) *articleVersionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleVersionDo) Limit(limit int) *articleVersionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleVersionDo) Offset(offset int) *articleVersionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleVersionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleVersionDo) Unscoped() *articleVersionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleVersionDo) Create(values ...*model.ArticleVersion) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleVersionDo) CreateInBatches(values []*model.ArticleVersion, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleVersionDo) Save(values ...*model.ArticleVersion) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleVersionDo) First() (*model.ArticleVersion, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleVersion), nil
	}
}

func (a articleVersionDo) Take() (*model.ArticleVersion, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleVersion), nil
	}
}

func (a articleVersionDo) Last() (*model.ArticleVersion, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleVersion), nil
	}
}

func (a articleVersionDo) Find() ([]*model.ArticleVersion, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleVersion), err
}

func (a articleVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleVersion, err error) {
	buf := make([]*model.ArticleVersion, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleVersionDo) FindInBatches(result *[]*model.ArticleVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleVersionDo) Attrs(attrs ...field.AssignExpr) *articleVersionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleVersionDo) Assign(attrs ...field.AssignExpr) *articleVersionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleVersionDo) Joins(fields ...field.RelationField) *articleVersionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleVersionDo) Preload(fields ...field.RelationField) *articleVersionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleVersionDo) FirstOrInit() (*model.ArticleVersion, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleVersion), nil
	}
}

func (a articleVersionDo) FirstOrCreate() (*model.ArticleVersion, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleVersion), nil
	}
}

func (a articleVersionDo) FindByPage(offset int, limit int) (result []*model.ArticleVersion, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleVersionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleVersionDo) Delete(models ...*model.ArticleVersion) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleVersionDo) withDO(do gen.Dao) *articleVersionDo {
	a.DO = *do.(*gen.DO)
	return a
}
