// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/public/model"
)

func newArticleTagRel(db *gorm.DB, opts ...gen.DOOption) articleTagRel {
	_articleTagRel := articleTagRel{}

	_articleTagRel.articleTagRelDo.UseDB(db, opts...)
	_articleTagRel.articleTagRelDo.UseModel(&model.ArticleTagRel{})

	tableName := _articleTagRel.articleTagRelDo.TableName()
	_articleTagRel.ALL = field.NewAsterisk(tableName)
	_articleTagRel.ArticleID = field.NewUint64(tableName, "article_id")
	_articleTagRel.TagID = field.NewUint64(tableName, "tag_id")

	_articleTagRel.fillFieldMap()

	return _articleTagRel
}

type articleTagRel struct {
	articleTagRelDo articleTagRelDo

	ALL       field.Asterisk
	ArticleID field.Uint64
	TagID     field.Uint64

	fieldMap map[string]field.Expr
}

func (a articleTagRel) Table(newTableName string) *articleTagRel {
	a.articleTagRelDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleTagRel) As(alias string) *articleTagRel {
	a.articleTagRelDo.DO = *(a.articleTagRelDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleTagRel) updateTableName(table string) *articleTagRel {
	a.ALL = field.NewAsterisk(table)
	a.ArticleID = field.NewUint64(table, "article_id")
	a.TagID = field.NewUint64(table, "tag_id")

	a.fillFieldMap()

	return a
}

func (a *articleTagRel) WithContext(ctx context.Context) *articleTagRelDo {
	return a.articleTagRelDo.WithContext(ctx)
}

func (a articleTagRel) TableName() string { return a.articleTagRelDo.TableName() }

func (a articleTagRel) Alias() string { return a.articleTagRelDo.Alias() }

func (a articleTagRel) Columns(cols ...field.Expr) gen.Columns {
	return a.articleTagRelDo.Columns(cols...)
}

func (a *articleTagRel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleTagRel) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 2)
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["tag_id"] = a.TagID
}

func (a articleTagRel) clone(db *gorm.DB) articleTagRel {
	a.articleTagRelDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleTagRel) replaceDB(db *gorm.DB) articleTagRel {
	a.articleTagRelDo.ReplaceDB(db)
	return a
}

type articleTagRelDo struct{ gen.DO }

func (a articleTagRelDo) Debug() *articleTagRelDo {
	return a.withDO(a.DO.Debug())
}

func (a articleTagRelDo) WithContext(ctx context.Context) *articleTagRelDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleTagRelDo) ReadDB() *articleTagRelDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleTagRelDo) WriteDB() *articleTagRelDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleTagRelDo) Session(config *gorm.Session) *articleTagRelDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleTagRelDo) Clauses(conds ...clause.Expression) *articleTagRelDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleTagRelDo) Returning(value interface{}, columns ...string) *articleTagRelDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleTagRelDo) Not(conds ...gen.Condition) *articleTagRelDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleTagRelDo) Or(conds ...gen.Condition) *articleTagRelDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleTagRelDo) Select(conds ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleTagRelDo) Where(conds ...gen.Condition) *articleTagRelDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleTagRelDo) Order(conds ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleTagRelDo) Distinct(cols ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleTagRelDo) Omit(cols ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleTagRelDo) Join(table schema.Tabler, on ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleTagRelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleTagRelDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleTagRelDo) Group(cols ...field.Expr) *articleTagRelDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleTagRelDo) Having(conds ...gen.Condition) *articleTagRelDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleTagRelDo) Limit(limit int) *articleTagRelDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleTagRelDo) Offset(offset int) *articleTagRelDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleTagRelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleTagRelDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleTagRelDo) Unscoped() *articleTagRelDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleTagRelDo) Create(values ...*model.ArticleTagRel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleTagRelDo) CreateInBatches(values []*model.ArticleTagRel, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleTagRelDo) Save(values ...*model.ArticleTagRel) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleTagRelDo) First() (*model.ArticleTagRel, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleTagRel), nil
	}
}

func (a articleTagRelDo) Take() (*model.ArticleTagRel, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleTagRel), nil
	}
}

func (a articleTagRelDo) Last() (*model.ArticleTagRel, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleTagRel), nil
	}
}

func (a articleTagRelDo) Find() ([]*model.ArticleTagRel, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleTagRel), err
}

func (a articleTagRelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleTagRel, err error) {
	buf := make([]*model.ArticleTagRel, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleTagRelDo) FindInBatches(result *[]*model.ArticleTagRel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleTagRelDo) Attrs(attrs ...field.AssignExpr) *articleTagRelDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleTagRelDo) Assign(attrs ...field.AssignExpr) *articleTagRelDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleTagRelDo) Joins(fields ...field.RelationField) *articleTagRelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleTagRelDo) Preload(fields ...field.RelationField) *articleTagRelDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleTagRelDo) FirstOrInit() (*model.ArticleTagRel, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleTagRel), nil
	}
}

func (a articleTagRelDo) FirstOrCreate() (*model.ArticleTagRel, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleTagRel), nil
	}
}

func (a articleTagRelDo) FindByPage(offset int, limit int) (result []*model.ArticleTagRel, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleTagRelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleTagRelDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleTagRelDo) Delete(models ...*model.ArticleTagRel) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleTagRelDo) withDO(do gen.Dao) *articleTagRelDo {
	a.DO = *do.(*gen.DO)
	return a
}
