// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/app/category/model"
)

func newCategoryMeta(db *gorm.DB, opts ...gen.DOOption) categoryMeta {
	_categoryMeta := categoryMeta{}

	_categoryMeta.categoryMetaDo.UseDB(db, opts...)
	_categoryMeta.categoryMetaDo.UseModel(&model.CategoryMeta{})

	tableName := _categoryMeta.categoryMetaDo.TableName()
	_categoryMeta.ALL = field.NewAsterisk(tableName)
	_categoryMeta.ID = field.NewUint64(tableName, "id")
	_categoryMeta.CreatedAt = field.NewTime(tableName, "created_at")
	_categoryMeta.UpdatedAt = field.NewTime(tableName, "updated_at")
	_categoryMeta.DeletedAt = field.NewTime(tableName, "deleted_at")
	_categoryMeta.CategoryID = field.NewUint64(tableName, "category_id")
	_categoryMeta.Title = field.NewString(tableName, "title")
	_categoryMeta.Keywords = field.NewString(tableName, "keywords")
	_categoryMeta.Description = field.NewString(tableName, "description")
	_categoryMeta.Thumb = field.NewString(tableName, "thumb")

	_categoryMeta.fillFieldMap()

	return _categoryMeta
}

type categoryMeta struct {
	categoryMetaDo categoryMetaDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Time
	CategoryID  field.Uint64
	Title       field.String
	Keywords    field.String
	Description field.String
	Thumb       field.String

	fieldMap map[string]field.Expr
}

func (c categoryMeta) Table(newTableName string) *categoryMeta {
	c.categoryMetaDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c categoryMeta) As(alias string) *categoryMeta {
	c.categoryMetaDo.DO = *(c.categoryMetaDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *categoryMeta) updateTableName(table string) *categoryMeta {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewTime(table, "deleted_at")
	c.CategoryID = field.NewUint64(table, "category_id")
	c.Title = field.NewString(table, "title")
	c.Keywords = field.NewString(table, "keywords")
	c.Description = field.NewString(table, "description")
	c.Thumb = field.NewString(table, "thumb")

	c.fillFieldMap()

	return c
}

func (c *categoryMeta) WithContext(ctx context.Context) *categoryMetaDo {
	return c.categoryMetaDo.WithContext(ctx)
}

func (c categoryMeta) TableName() string { return c.categoryMetaDo.TableName() }

func (c categoryMeta) Alias() string { return c.categoryMetaDo.Alias() }

func (c categoryMeta) Columns(cols ...field.Expr) gen.Columns {
	return c.categoryMetaDo.Columns(cols...)
}

func (c *categoryMeta) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *categoryMeta) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["title"] = c.Title
	c.fieldMap["keywords"] = c.Keywords
	c.fieldMap["description"] = c.Description
	c.fieldMap["thumb"] = c.Thumb
}

func (c categoryMeta) clone(db *gorm.DB) categoryMeta {
	c.categoryMetaDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c categoryMeta) replaceDB(db *gorm.DB) categoryMeta {
	c.categoryMetaDo.ReplaceDB(db)
	return c
}

type categoryMetaDo struct{ gen.DO }

func (c categoryMetaDo) Debug() *categoryMetaDo {
	return c.withDO(c.DO.Debug())
}

func (c categoryMetaDo) WithContext(ctx context.Context) *categoryMetaDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categoryMetaDo) ReadDB() *categoryMetaDo {
	return c.Clauses(dbresolver.Read)
}

func (c categoryMetaDo) WriteDB() *categoryMetaDo {
	return c.Clauses(dbresolver.Write)
}

func (c categoryMetaDo) Session(config *gorm.Session) *categoryMetaDo {
	return c.withDO(c.DO.Session(config))
}

func (c categoryMetaDo) Clauses(conds ...clause.Expression) *categoryMetaDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categoryMetaDo) Returning(value interface{}, columns ...string) *categoryMetaDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categoryMetaDo) Not(conds ...gen.Condition) *categoryMetaDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c categoryMetaDo) Or(conds ...gen.Condition) *categoryMetaDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c categoryMetaDo) Select(conds ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c categoryMetaDo) Where(conds ...gen.Condition) *categoryMetaDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c categoryMetaDo) Order(conds ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c categoryMetaDo) Distinct(cols ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categoryMetaDo) Omit(cols ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categoryMetaDo) Join(table schema.Tabler, on ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categoryMetaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categoryMetaDo) RightJoin(table schema.Tabler, on ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categoryMetaDo) Group(cols ...field.Expr) *categoryMetaDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c categoryMetaDo) Having(conds ...gen.Condition) *categoryMetaDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c categoryMetaDo) Limit(limit int) *categoryMetaDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c categoryMetaDo) Offset(offset int) *categoryMetaDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c categoryMetaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *categoryMetaDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categoryMetaDo) Unscoped() *categoryMetaDo {
	return c.withDO(c.DO.Unscoped())
}

func (c categoryMetaDo) Create(values ...*model.CategoryMeta) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categoryMetaDo) CreateInBatches(values []*model.CategoryMeta, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categoryMetaDo) Save(values ...*model.CategoryMeta) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categoryMetaDo) First() (*model.CategoryMeta, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryMeta), nil
	}
}

func (c categoryMetaDo) Take() (*model.CategoryMeta, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryMeta), nil
	}
}

func (c categoryMetaDo) Last() (*model.CategoryMeta, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryMeta), nil
	}
}

func (c categoryMetaDo) Find() ([]*model.CategoryMeta, error) {
	result, err := c.DO.Find()
	return result.([]*model.CategoryMeta), err
}

func (c categoryMetaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CategoryMeta, err error) {
	buf := make([]*model.CategoryMeta, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categoryMetaDo) FindInBatches(result *[]*model.CategoryMeta, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categoryMetaDo) Attrs(attrs ...field.AssignExpr) *categoryMetaDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categoryMetaDo) Assign(attrs ...field.AssignExpr) *categoryMetaDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categoryMetaDo) Joins(fields ...field.RelationField) *categoryMetaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c categoryMetaDo) Preload(fields ...field.RelationField) *categoryMetaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c categoryMetaDo) FirstOrInit() (*model.CategoryMeta, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryMeta), nil
	}
}

func (c categoryMetaDo) FirstOrCreate() (*model.CategoryMeta, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryMeta), nil
	}
}

func (c categoryMetaDo) FindByPage(offset int, limit int) (result []*model.CategoryMeta, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categoryMetaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c categoryMetaDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c categoryMetaDo) Delete(models ...*model.CategoryMeta) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *categoryMetaDo) withDO(do gen.Dao) *categoryMetaDo {
	c.DO = *do.(*gen.DO)
	return c
}
