// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/public/model"
)

func newContentFieldValues(db *gorm.DB, opts ...gen.DOOption) contentFieldValues {
	_contentFieldValues := contentFieldValues{}

	_contentFieldValues.contentFieldValuesDo.UseDB(db, opts...)
	_contentFieldValues.contentFieldValuesDo.UseModel(&model.ContentFieldValues{})

	tableName := _contentFieldValues.contentFieldValuesDo.TableName()
	_contentFieldValues.ALL = field.NewAsterisk(tableName)
	_contentFieldValues.ID = field.NewUint64(tableName, "id")
	_contentFieldValues.CreatedAt = field.NewTime(tableName, "created_at")
	_contentFieldValues.UpdatedAt = field.NewTime(tableName, "updated_at")
	_contentFieldValues.DeletedAt = field.NewTime(tableName, "deleted_at")
	_contentFieldValues.ModelID = field.NewUint64(tableName, "model_id")
	_contentFieldValues.ArticleID = field.NewUint64(tableName, "article_id")
	_contentFieldValues.FieldKey = field.NewString(tableName, "field_key")
	_contentFieldValues.Type = field.NewInt16(tableName, "type")
	_contentFieldValues.StringValue = field.NewString(tableName, "string_value")
	_contentFieldValues.BoolValue = field.NewBool(tableName, "bool_value")
	_contentFieldValues.NumberValue = field.NewField(tableName, "number_value")
	_contentFieldValues.TimeValue = field.NewTime(tableName, "time_value")

	_contentFieldValues.fillFieldMap()

	return _contentFieldValues
}

type contentFieldValues struct {
	contentFieldValuesDo contentFieldValuesDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Time
	ModelID     field.Uint64
	ArticleID   field.Uint64
	FieldKey    field.String
	Type        field.Int16
	StringValue field.String
	BoolValue   field.Bool
	NumberValue field.Field
	TimeValue   field.Time

	fieldMap map[string]field.Expr
}

func (c contentFieldValues) Table(newTableName string) *contentFieldValues {
	c.contentFieldValuesDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contentFieldValues) As(alias string) *contentFieldValues {
	c.contentFieldValuesDo.DO = *(c.contentFieldValuesDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contentFieldValues) updateTableName(table string) *contentFieldValues {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewTime(table, "deleted_at")
	c.ModelID = field.NewUint64(table, "model_id")
	c.ArticleID = field.NewUint64(table, "article_id")
	c.FieldKey = field.NewString(table, "field_key")
	c.Type = field.NewInt16(table, "type")
	c.StringValue = field.NewString(table, "string_value")
	c.BoolValue = field.NewBool(table, "bool_value")
	c.NumberValue = field.NewField(table, "number_value")
	c.TimeValue = field.NewTime(table, "time_value")

	c.fillFieldMap()

	return c
}

func (c *contentFieldValues) WithContext(ctx context.Context) *contentFieldValuesDo {
	return c.contentFieldValuesDo.WithContext(ctx)
}

func (c contentFieldValues) TableName() string { return c.contentFieldValuesDo.TableName() }

func (c contentFieldValues) Alias() string { return c.contentFieldValuesDo.Alias() }

func (c contentFieldValues) Columns(cols ...field.Expr) gen.Columns {
	return c.contentFieldValuesDo.Columns(cols...)
}

func (c *contentFieldValues) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contentFieldValues) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["model_id"] = c.ModelID
	c.fieldMap["article_id"] = c.ArticleID
	c.fieldMap["field_key"] = c.FieldKey
	c.fieldMap["type"] = c.Type
	c.fieldMap["string_value"] = c.StringValue
	c.fieldMap["bool_value"] = c.BoolValue
	c.fieldMap["number_value"] = c.NumberValue
	c.fieldMap["time_value"] = c.TimeValue
}

func (c contentFieldValues) clone(db *gorm.DB) contentFieldValues {
	c.contentFieldValuesDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contentFieldValues) replaceDB(db *gorm.DB) contentFieldValues {
	c.contentFieldValuesDo.ReplaceDB(db)
	return c
}

type contentFieldValuesDo struct{ gen.DO }

func (c contentFieldValuesDo) Debug() *contentFieldValuesDo {
	return c.withDO(c.DO.Debug())
}

func (c contentFieldValuesDo) WithContext(ctx context.Context) *contentFieldValuesDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentFieldValuesDo) ReadDB() *contentFieldValuesDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentFieldValuesDo) WriteDB() *contentFieldValuesDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentFieldValuesDo) Session(config *gorm.Session) *contentFieldValuesDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentFieldValuesDo) Clauses(conds ...clause.Expression) *contentFieldValuesDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentFieldValuesDo) Returning(value interface{}, columns ...string) *contentFieldValuesDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentFieldValuesDo) Not(conds ...gen.Condition) *contentFieldValuesDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentFieldValuesDo) Or(conds ...gen.Condition) *contentFieldValuesDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentFieldValuesDo) Select(conds ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentFieldValuesDo) Where(conds ...gen.Condition) *contentFieldValuesDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentFieldValuesDo) Order(conds ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentFieldValuesDo) Distinct(cols ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentFieldValuesDo) Omit(cols ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentFieldValuesDo) Join(table schema.Tabler, on ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentFieldValuesDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentFieldValuesDo) RightJoin(table schema.Tabler, on ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentFieldValuesDo) Group(cols ...field.Expr) *contentFieldValuesDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentFieldValuesDo) Having(conds ...gen.Condition) *contentFieldValuesDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentFieldValuesDo) Limit(limit int) *contentFieldValuesDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentFieldValuesDo) Offset(offset int) *contentFieldValuesDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentFieldValuesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contentFieldValuesDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentFieldValuesDo) Unscoped() *contentFieldValuesDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentFieldValuesDo) Create(values ...*model.ContentFieldValues) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentFieldValuesDo) CreateInBatches(values []*model.ContentFieldValues, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentFieldValuesDo) Save(values ...*model.ContentFieldValues) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentFieldValuesDo) First() (*model.ContentFieldValues, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentFieldValues), nil
	}
}

func (c contentFieldValuesDo) Take() (*model.ContentFieldValues, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentFieldValues), nil
	}
}

func (c contentFieldValuesDo) Last() (*model.ContentFieldValues, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentFieldValues), nil
	}
}

func (c contentFieldValuesDo) Find() ([]*model.ContentFieldValues, error) {
	result, err := c.DO.Find()
	return result.([]*model.ContentFieldValues), err
}

func (c contentFieldValuesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContentFieldValues, err error) {
	buf := make([]*model.ContentFieldValues, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentFieldValuesDo) FindInBatches(result *[]*model.ContentFieldValues, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentFieldValuesDo) Attrs(attrs ...field.AssignExpr) *contentFieldValuesDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentFieldValuesDo) Assign(attrs ...field.AssignExpr) *contentFieldValuesDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentFieldValuesDo) Joins(fields ...field.RelationField) *contentFieldValuesDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentFieldValuesDo) Preload(fields ...field.RelationField) *contentFieldValuesDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentFieldValuesDo) FirstOrInit() (*model.ContentFieldValues, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentFieldValues), nil
	}
}

func (c contentFieldValuesDo) FirstOrCreate() (*model.ContentFieldValues, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentFieldValues), nil
	}
}

func (c contentFieldValuesDo) FindByPage(offset int, limit int) (result []*model.ContentFieldValues, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentFieldValuesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentFieldValuesDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentFieldValuesDo) Delete(models ...*model.ContentFieldValues) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentFieldValuesDo) withDO(do gen.Dao) *contentFieldValuesDo {
	c.DO = *do.(*gen.DO)
	return c
}
