// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Article:            newArticle(db, opts...),
		ArticleCategoryRel: newArticleCategoryRel(db, opts...),
		ArticleComment:     newArticleComment(db, opts...),
		ArticlePublish:     newArticlePublish(db, opts...),
		ArticleTag:         newArticleTag(db, opts...),
		ArticleTagRel:      newArticleTagRel(db, opts...),
		ArticleVersion:     newArticleVersion(db, opts...),
		Attachment:         newAttachment(db, opts...),
		Base:               newBase(db, opts...),
		Category:           newCategory(db, opts...),
		CategoryContext:    newCategoryContext(db, opts...),
		CategoryMeta:       newCategoryMeta(db, opts...),
		ContentFieldValues: newContentFieldValues(db, opts...),
		ContentType:        newContentType(db, opts...),
		ContentTypeEntries: newContentTypeEntries(db, opts...),
		ContentTypeSchema:  newContentTypeSchema(db, opts...),
		File:               newFile(db, opts...),
		Menu:               newMenu(db, opts...),
		MenuContext:        newMenuContext(db, opts...),
		Permission:         newPermission(db, opts...),
		Role:               newRole(db, opts...),
		Setting:            newSetting(db, opts...),
		SinglePage:         newSinglePage(db, opts...),
		User:               newUser(db, opts...),
		UserProfile:        newUserProfile(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Article            article
	ArticleCategoryRel articleCategoryRel
	ArticleComment     articleComment
	ArticlePublish     articlePublish
	ArticleTag         articleTag
	ArticleTagRel      articleTagRel
	ArticleVersion     articleVersion
	Attachment         attachment
	Base               base
	Category           category
	CategoryContext    categoryContext
	CategoryMeta       categoryMeta
	ContentFieldValues contentFieldValues
	ContentType        contentType
	ContentTypeEntries contentTypeEntries
	ContentTypeSchema  contentTypeSchema
	File               file
	Menu               menu
	MenuContext        menuContext
	Permission         permission
	Role               role
	Setting            setting
	SinglePage         singlePage
	User               user
	UserProfile        userProfile
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Article:            q.Article.clone(db),
		ArticleCategoryRel: q.ArticleCategoryRel.clone(db),
		ArticleComment:     q.ArticleComment.clone(db),
		ArticlePublish:     q.ArticlePublish.clone(db),
		ArticleTag:         q.ArticleTag.clone(db),
		ArticleTagRel:      q.ArticleTagRel.clone(db),
		ArticleVersion:     q.ArticleVersion.clone(db),
		Attachment:         q.Attachment.clone(db),
		Base:               q.Base.clone(db),
		Category:           q.Category.clone(db),
		CategoryContext:    q.CategoryContext.clone(db),
		CategoryMeta:       q.CategoryMeta.clone(db),
		ContentFieldValues: q.ContentFieldValues.clone(db),
		ContentType:        q.ContentType.clone(db),
		ContentTypeEntries: q.ContentTypeEntries.clone(db),
		ContentTypeSchema:  q.ContentTypeSchema.clone(db),
		File:               q.File.clone(db),
		Menu:               q.Menu.clone(db),
		MenuContext:        q.MenuContext.clone(db),
		Permission:         q.Permission.clone(db),
		Role:               q.Role.clone(db),
		Setting:            q.Setting.clone(db),
		SinglePage:         q.SinglePage.clone(db),
		User:               q.User.clone(db),
		UserProfile:        q.UserProfile.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Article:            q.Article.replaceDB(db),
		ArticleCategoryRel: q.ArticleCategoryRel.replaceDB(db),
		ArticleComment:     q.ArticleComment.replaceDB(db),
		ArticlePublish:     q.ArticlePublish.replaceDB(db),
		ArticleTag:         q.ArticleTag.replaceDB(db),
		ArticleTagRel:      q.ArticleTagRel.replaceDB(db),
		ArticleVersion:     q.ArticleVersion.replaceDB(db),
		Attachment:         q.Attachment.replaceDB(db),
		Base:               q.Base.replaceDB(db),
		Category:           q.Category.replaceDB(db),
		CategoryContext:    q.CategoryContext.replaceDB(db),
		CategoryMeta:       q.CategoryMeta.replaceDB(db),
		ContentFieldValues: q.ContentFieldValues.replaceDB(db),
		ContentType:        q.ContentType.replaceDB(db),
		ContentTypeEntries: q.ContentTypeEntries.replaceDB(db),
		ContentTypeSchema:  q.ContentTypeSchema.replaceDB(db),
		File:               q.File.replaceDB(db),
		Menu:               q.Menu.replaceDB(db),
		MenuContext:        q.MenuContext.replaceDB(db),
		Permission:         q.Permission.replaceDB(db),
		Role:               q.Role.replaceDB(db),
		Setting:            q.Setting.replaceDB(db),
		SinglePage:         q.SinglePage.replaceDB(db),
		User:               q.User.replaceDB(db),
		UserProfile:        q.UserProfile.replaceDB(db),
	}
}

type queryCtx struct {
	Article            *articleDo
	ArticleCategoryRel *articleCategoryRelDo
	ArticleComment     *articleCommentDo
	ArticlePublish     *articlePublishDo
	ArticleTag         *articleTagDo
	ArticleTagRel      *articleTagRelDo
	ArticleVersion     *articleVersionDo
	Attachment         *attachmentDo
	Base               *baseDo
	Category           *categoryDo
	CategoryContext    *categoryContextDo
	CategoryMeta       *categoryMetaDo
	ContentFieldValues *contentFieldValuesDo
	ContentType        *contentTypeDo
	ContentTypeEntries *contentTypeEntriesDo
	ContentTypeSchema  *contentTypeSchemaDo
	File               *fileDo
	Menu               *menuDo
	MenuContext        *menuContextDo
	Permission         *permissionDo
	Role               *roleDo
	Setting            *settingDo
	SinglePage         *singlePageDo
	User               *userDo
	UserProfile        *userProfileDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Article:            q.Article.WithContext(ctx),
		ArticleCategoryRel: q.ArticleCategoryRel.WithContext(ctx),
		ArticleComment:     q.ArticleComment.WithContext(ctx),
		ArticlePublish:     q.ArticlePublish.WithContext(ctx),
		ArticleTag:         q.ArticleTag.WithContext(ctx),
		ArticleTagRel:      q.ArticleTagRel.WithContext(ctx),
		ArticleVersion:     q.ArticleVersion.WithContext(ctx),
		Attachment:         q.Attachment.WithContext(ctx),
		Base:               q.Base.WithContext(ctx),
		Category:           q.Category.WithContext(ctx),
		CategoryContext:    q.CategoryContext.WithContext(ctx),
		CategoryMeta:       q.CategoryMeta.WithContext(ctx),
		ContentFieldValues: q.ContentFieldValues.WithContext(ctx),
		ContentType:        q.ContentType.WithContext(ctx),
		ContentTypeEntries: q.ContentTypeEntries.WithContext(ctx),
		ContentTypeSchema:  q.ContentTypeSchema.WithContext(ctx),
		File:               q.File.WithContext(ctx),
		Menu:               q.Menu.WithContext(ctx),
		MenuContext:        q.MenuContext.WithContext(ctx),
		Permission:         q.Permission.WithContext(ctx),
		Role:               q.Role.WithContext(ctx),
		Setting:            q.Setting.WithContext(ctx),
		SinglePage:         q.SinglePage.WithContext(ctx),
		User:               q.User.WithContext(ctx),
		UserProfile:        q.UserProfile.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
