// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	`dpcms/packages/data`
    "gorm.io/gorm"
)

// Injectors from wire.go:

func initDB(c *data.DBConfig) (*gorm.DB, error) {
	db, err := data.NewDB(c)
	if err != nil {
		return nil, err
	}
	return db, nil
}
