// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persistence/gorm/model"
)

func newContentTypeSchema(db *gorm.DB, opts ...gen.DOOption) contentTypeSchema {
	_contentTypeSchema := contentTypeSchema{}

	_contentTypeSchema.contentTypeSchemaDo.UseDB(db, opts...)
	_contentTypeSchema.contentTypeSchemaDo.UseModel(&model.ContentTypeSchema{})

	tableName := _contentTypeSchema.contentTypeSchemaDo.TableName()
	_contentTypeSchema.ALL = field.NewAsterisk(tableName)
	_contentTypeSchema.ID = field.NewUint64(tableName, "id")
	_contentTypeSchema.CreatedAt = field.NewTime(tableName, "created_at")
	_contentTypeSchema.UpdatedAt = field.NewTime(tableName, "updated_at")
	_contentTypeSchema.DeletedAt = field.NewField(tableName, "deleted_at")
	_contentTypeSchema.ContentTypeID = field.NewUint64(tableName, "content_type_id")
	_contentTypeSchema.FieldKey = field.NewString(tableName, "field_key")
	_contentTypeSchema.FieldName = field.NewString(tableName, "field_name")
	_contentTypeSchema.Description = field.NewString(tableName, "description")
	_contentTypeSchema.MinLen = field.NewUint64(tableName, "min_len")
	_contentTypeSchema.MaxLen = field.NewUint64(tableName, "max_len")
	_contentTypeSchema.MinValue = field.NewField(tableName, "min_value")
	_contentTypeSchema.MaxValue = field.NewField(tableName, "max_value")
	_contentTypeSchema.MinTime = field.NewTime(tableName, "min_time")
	_contentTypeSchema.MaxTime = field.NewTime(tableName, "max_time")
	_contentTypeSchema.Pattern = field.NewString(tableName, "pattern")
	_contentTypeSchema.Sequence = field.NewInt64(tableName, "sequence")
	_contentTypeSchema.Type = field.NewInt16(tableName, "type")
	_contentTypeSchema.EnumOptions = field.NewString(tableName, "enum_options")
	_contentTypeSchema.Required = field.NewBool(tableName, "required")
	_contentTypeSchema.Visible = field.NewBool(tableName, "visible")
	_contentTypeSchema.Enable = field.NewBool(tableName, "enable")

	_contentTypeSchema.fillFieldMap()

	return _contentTypeSchema
}

type contentTypeSchema struct {
	contentTypeSchemaDo contentTypeSchemaDo

	ALL           field.Asterisk
	ID            field.Uint64
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field
	ContentTypeID field.Uint64
	FieldKey      field.String
	FieldName     field.String
	Description   field.String
	MinLen        field.Uint64
	MaxLen        field.Uint64
	MinValue      field.Field
	MaxValue      field.Field
	MinTime       field.Time
	MaxTime       field.Time
	Pattern       field.String
	Sequence      field.Int64
	Type          field.Int16
	EnumOptions   field.String
	Required      field.Bool
	Visible       field.Bool
	Enable        field.Bool

	fieldMap map[string]field.Expr
}

func (c contentTypeSchema) Table(newTableName string) *contentTypeSchema {
	c.contentTypeSchemaDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contentTypeSchema) As(alias string) *contentTypeSchema {
	c.contentTypeSchemaDo.DO = *(c.contentTypeSchemaDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contentTypeSchema) updateTableName(table string) *contentTypeSchema {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.ContentTypeID = field.NewUint64(table, "content_type_id")
	c.FieldKey = field.NewString(table, "field_key")
	c.FieldName = field.NewString(table, "field_name")
	c.Description = field.NewString(table, "description")
	c.MinLen = field.NewUint64(table, "min_len")
	c.MaxLen = field.NewUint64(table, "max_len")
	c.MinValue = field.NewField(table, "min_value")
	c.MaxValue = field.NewField(table, "max_value")
	c.MinTime = field.NewTime(table, "min_time")
	c.MaxTime = field.NewTime(table, "max_time")
	c.Pattern = field.NewString(table, "pattern")
	c.Sequence = field.NewInt64(table, "sequence")
	c.Type = field.NewInt16(table, "type")
	c.EnumOptions = field.NewString(table, "enum_options")
	c.Required = field.NewBool(table, "required")
	c.Visible = field.NewBool(table, "visible")
	c.Enable = field.NewBool(table, "enable")

	c.fillFieldMap()

	return c
}

func (c *contentTypeSchema) WithContext(ctx context.Context) *contentTypeSchemaDo {
	return c.contentTypeSchemaDo.WithContext(ctx)
}

func (c contentTypeSchema) TableName() string { return c.contentTypeSchemaDo.TableName() }

func (c contentTypeSchema) Alias() string { return c.contentTypeSchemaDo.Alias() }

func (c contentTypeSchema) Columns(cols ...field.Expr) gen.Columns {
	return c.contentTypeSchemaDo.Columns(cols...)
}

func (c *contentTypeSchema) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contentTypeSchema) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 21)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["content_type_id"] = c.ContentTypeID
	c.fieldMap["field_key"] = c.FieldKey
	c.fieldMap["field_name"] = c.FieldName
	c.fieldMap["description"] = c.Description
	c.fieldMap["min_len"] = c.MinLen
	c.fieldMap["max_len"] = c.MaxLen
	c.fieldMap["min_value"] = c.MinValue
	c.fieldMap["max_value"] = c.MaxValue
	c.fieldMap["min_time"] = c.MinTime
	c.fieldMap["max_time"] = c.MaxTime
	c.fieldMap["pattern"] = c.Pattern
	c.fieldMap["sequence"] = c.Sequence
	c.fieldMap["type"] = c.Type
	c.fieldMap["enum_options"] = c.EnumOptions
	c.fieldMap["required"] = c.Required
	c.fieldMap["visible"] = c.Visible
	c.fieldMap["enable"] = c.Enable
}

func (c contentTypeSchema) clone(db *gorm.DB) contentTypeSchema {
	c.contentTypeSchemaDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contentTypeSchema) replaceDB(db *gorm.DB) contentTypeSchema {
	c.contentTypeSchemaDo.ReplaceDB(db)
	return c
}

type contentTypeSchemaDo struct{ gen.DO }

func (c contentTypeSchemaDo) Debug() *contentTypeSchemaDo {
	return c.withDO(c.DO.Debug())
}

func (c contentTypeSchemaDo) WithContext(ctx context.Context) *contentTypeSchemaDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentTypeSchemaDo) ReadDB() *contentTypeSchemaDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentTypeSchemaDo) WriteDB() *contentTypeSchemaDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentTypeSchemaDo) Session(config *gorm.Session) *contentTypeSchemaDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentTypeSchemaDo) Clauses(conds ...clause.Expression) *contentTypeSchemaDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentTypeSchemaDo) Returning(value interface{}, columns ...string) *contentTypeSchemaDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentTypeSchemaDo) Not(conds ...gen.Condition) *contentTypeSchemaDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentTypeSchemaDo) Or(conds ...gen.Condition) *contentTypeSchemaDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentTypeSchemaDo) Select(conds ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentTypeSchemaDo) Where(conds ...gen.Condition) *contentTypeSchemaDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentTypeSchemaDo) Order(conds ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentTypeSchemaDo) Distinct(cols ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentTypeSchemaDo) Omit(cols ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentTypeSchemaDo) Join(table schema.Tabler, on ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentTypeSchemaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentTypeSchemaDo) RightJoin(table schema.Tabler, on ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentTypeSchemaDo) Group(cols ...field.Expr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentTypeSchemaDo) Having(conds ...gen.Condition) *contentTypeSchemaDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentTypeSchemaDo) Limit(limit int) *contentTypeSchemaDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentTypeSchemaDo) Offset(offset int) *contentTypeSchemaDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentTypeSchemaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contentTypeSchemaDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentTypeSchemaDo) Unscoped() *contentTypeSchemaDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentTypeSchemaDo) Create(values ...*model.ContentTypeSchema) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentTypeSchemaDo) CreateInBatches(values []*model.ContentTypeSchema, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentTypeSchemaDo) Save(values ...*model.ContentTypeSchema) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentTypeSchemaDo) First() (*model.ContentTypeSchema, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeSchema), nil
	}
}

func (c contentTypeSchemaDo) Take() (*model.ContentTypeSchema, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeSchema), nil
	}
}

func (c contentTypeSchemaDo) Last() (*model.ContentTypeSchema, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeSchema), nil
	}
}

func (c contentTypeSchemaDo) Find() ([]*model.ContentTypeSchema, error) {
	result, err := c.DO.Find()
	return result.([]*model.ContentTypeSchema), err
}

func (c contentTypeSchemaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContentTypeSchema, err error) {
	buf := make([]*model.ContentTypeSchema, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentTypeSchemaDo) FindInBatches(result *[]*model.ContentTypeSchema, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentTypeSchemaDo) Attrs(attrs ...field.AssignExpr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentTypeSchemaDo) Assign(attrs ...field.AssignExpr) *contentTypeSchemaDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentTypeSchemaDo) Joins(fields ...field.RelationField) *contentTypeSchemaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentTypeSchemaDo) Preload(fields ...field.RelationField) *contentTypeSchemaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentTypeSchemaDo) FirstOrInit() (*model.ContentTypeSchema, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeSchema), nil
	}
}

func (c contentTypeSchemaDo) FirstOrCreate() (*model.ContentTypeSchema, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeSchema), nil
	}
}

func (c contentTypeSchemaDo) FindByPage(offset int, limit int) (result []*model.ContentTypeSchema, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentTypeSchemaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentTypeSchemaDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentTypeSchemaDo) Delete(models ...*model.ContentTypeSchema) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentTypeSchemaDo) withDO(do gen.Dao) *contentTypeSchemaDo {
	c.DO = *do.(*gen.DO)
	return c
}
