// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persistence/gorm/model"
)

func newContentTypeEntries(db *gorm.DB, opts ...gen.DOOption) contentTypeEntries {
	_contentTypeEntries := contentTypeEntries{}

	_contentTypeEntries.contentTypeEntriesDo.UseDB(db, opts...)
	_contentTypeEntries.contentTypeEntriesDo.UseModel(&model.ContentTypeEntries{})

	tableName := _contentTypeEntries.contentTypeEntriesDo.TableName()
	_contentTypeEntries.ALL = field.NewAsterisk(tableName)
	_contentTypeEntries.ID = field.NewUint64(tableName, "id")
	_contentTypeEntries.CreatedAt = field.NewTime(tableName, "created_at")
	_contentTypeEntries.UpdatedAt = field.NewTime(tableName, "updated_at")
	_contentTypeEntries.DeletedAt = field.NewField(tableName, "deleted_at")
	_contentTypeEntries.ArticleID = field.NewUint64(tableName, "article_id")
	_contentTypeEntries.ContentTypeID = field.NewUint64(tableName, "content_type_id")
	_contentTypeEntries.Data = field.NewField(tableName, "data")

	_contentTypeEntries.fillFieldMap()

	return _contentTypeEntries
}

type contentTypeEntries struct {
	contentTypeEntriesDo contentTypeEntriesDo

	ALL           field.Asterisk
	ID            field.Uint64
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field
	ArticleID     field.Uint64
	ContentTypeID field.Uint64
	Data          field.Field

	fieldMap map[string]field.Expr
}

func (c contentTypeEntries) Table(newTableName string) *contentTypeEntries {
	c.contentTypeEntriesDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contentTypeEntries) As(alias string) *contentTypeEntries {
	c.contentTypeEntriesDo.DO = *(c.contentTypeEntriesDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contentTypeEntries) updateTableName(table string) *contentTypeEntries {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.ArticleID = field.NewUint64(table, "article_id")
	c.ContentTypeID = field.NewUint64(table, "content_type_id")
	c.Data = field.NewField(table, "data")

	c.fillFieldMap()

	return c
}

func (c *contentTypeEntries) WithContext(ctx context.Context) *contentTypeEntriesDo {
	return c.contentTypeEntriesDo.WithContext(ctx)
}

func (c contentTypeEntries) TableName() string { return c.contentTypeEntriesDo.TableName() }

func (c contentTypeEntries) Alias() string { return c.contentTypeEntriesDo.Alias() }

func (c contentTypeEntries) Columns(cols ...field.Expr) gen.Columns {
	return c.contentTypeEntriesDo.Columns(cols...)
}

func (c *contentTypeEntries) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contentTypeEntries) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["article_id"] = c.ArticleID
	c.fieldMap["content_type_id"] = c.ContentTypeID
	c.fieldMap["data"] = c.Data
}

func (c contentTypeEntries) clone(db *gorm.DB) contentTypeEntries {
	c.contentTypeEntriesDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contentTypeEntries) replaceDB(db *gorm.DB) contentTypeEntries {
	c.contentTypeEntriesDo.ReplaceDB(db)
	return c
}

type contentTypeEntriesDo struct{ gen.DO }

func (c contentTypeEntriesDo) Debug() *contentTypeEntriesDo {
	return c.withDO(c.DO.Debug())
}

func (c contentTypeEntriesDo) WithContext(ctx context.Context) *contentTypeEntriesDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentTypeEntriesDo) ReadDB() *contentTypeEntriesDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentTypeEntriesDo) WriteDB() *contentTypeEntriesDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentTypeEntriesDo) Session(config *gorm.Session) *contentTypeEntriesDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentTypeEntriesDo) Clauses(conds ...clause.Expression) *contentTypeEntriesDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentTypeEntriesDo) Returning(value interface{}, columns ...string) *contentTypeEntriesDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentTypeEntriesDo) Not(conds ...gen.Condition) *contentTypeEntriesDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentTypeEntriesDo) Or(conds ...gen.Condition) *contentTypeEntriesDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentTypeEntriesDo) Select(conds ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentTypeEntriesDo) Where(conds ...gen.Condition) *contentTypeEntriesDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentTypeEntriesDo) Order(conds ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentTypeEntriesDo) Distinct(cols ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentTypeEntriesDo) Omit(cols ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentTypeEntriesDo) Join(table schema.Tabler, on ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentTypeEntriesDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentTypeEntriesDo) RightJoin(table schema.Tabler, on ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentTypeEntriesDo) Group(cols ...field.Expr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentTypeEntriesDo) Having(conds ...gen.Condition) *contentTypeEntriesDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentTypeEntriesDo) Limit(limit int) *contentTypeEntriesDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentTypeEntriesDo) Offset(offset int) *contentTypeEntriesDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentTypeEntriesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contentTypeEntriesDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentTypeEntriesDo) Unscoped() *contentTypeEntriesDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentTypeEntriesDo) Create(values ...*model.ContentTypeEntries) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentTypeEntriesDo) CreateInBatches(values []*model.ContentTypeEntries, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentTypeEntriesDo) Save(values ...*model.ContentTypeEntries) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentTypeEntriesDo) First() (*model.ContentTypeEntries, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeEntries), nil
	}
}

func (c contentTypeEntriesDo) Take() (*model.ContentTypeEntries, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeEntries), nil
	}
}

func (c contentTypeEntriesDo) Last() (*model.ContentTypeEntries, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeEntries), nil
	}
}

func (c contentTypeEntriesDo) Find() ([]*model.ContentTypeEntries, error) {
	result, err := c.DO.Find()
	return result.([]*model.ContentTypeEntries), err
}

func (c contentTypeEntriesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContentTypeEntries, err error) {
	buf := make([]*model.ContentTypeEntries, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentTypeEntriesDo) FindInBatches(result *[]*model.ContentTypeEntries, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentTypeEntriesDo) Attrs(attrs ...field.AssignExpr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentTypeEntriesDo) Assign(attrs ...field.AssignExpr) *contentTypeEntriesDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentTypeEntriesDo) Joins(fields ...field.RelationField) *contentTypeEntriesDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentTypeEntriesDo) Preload(fields ...field.RelationField) *contentTypeEntriesDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentTypeEntriesDo) FirstOrInit() (*model.ContentTypeEntries, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeEntries), nil
	}
}

func (c contentTypeEntriesDo) FirstOrCreate() (*model.ContentTypeEntries, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentTypeEntries), nil
	}
}

func (c contentTypeEntriesDo) FindByPage(offset int, limit int) (result []*model.ContentTypeEntries, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentTypeEntriesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentTypeEntriesDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentTypeEntriesDo) Delete(models ...*model.ContentTypeEntries) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentTypeEntriesDo) withDO(do gen.Dao) *contentTypeEntriesDo {
	c.DO = *do.(*gen.DO)
	return c
}
