// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persistence/gorm/model"
)

func newContentType(db *gorm.DB, opts ...gen.DOOption) contentType {
	_contentType := contentType{}

	_contentType.contentTypeDo.UseDB(db, opts...)
	_contentType.contentTypeDo.UseModel(&model.ContentType{})

	tableName := _contentType.contentTypeDo.TableName()
	_contentType.ALL = field.NewAsterisk(tableName)
	_contentType.ID = field.NewUint64(tableName, "id")
	_contentType.CreatedAt = field.NewTime(tableName, "created_at")
	_contentType.UpdatedAt = field.NewTime(tableName, "updated_at")
	_contentType.DeletedAt = field.NewField(tableName, "deleted_at")
	_contentType.Name = field.NewString(tableName, "name")
	_contentType.Description = field.NewString(tableName, "description")

	_contentType.fillFieldMap()

	return _contentType
}

type contentType struct {
	contentTypeDo contentTypeDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Name        field.String
	Description field.String

	fieldMap map[string]field.Expr
}

func (c contentType) Table(newTableName string) *contentType {
	c.contentTypeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contentType) As(alias string) *contentType {
	c.contentTypeDo.DO = *(c.contentTypeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contentType) updateTableName(table string) *contentType {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.Name = field.NewString(table, "name")
	c.Description = field.NewString(table, "description")

	c.fillFieldMap()

	return c
}

func (c *contentType) WithContext(ctx context.Context) *contentTypeDo {
	return c.contentTypeDo.WithContext(ctx)
}

func (c contentType) TableName() string { return c.contentTypeDo.TableName() }

func (c contentType) Alias() string { return c.contentTypeDo.Alias() }

func (c contentType) Columns(cols ...field.Expr) gen.Columns { return c.contentTypeDo.Columns(cols...) }

func (c *contentType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contentType) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["name"] = c.Name
	c.fieldMap["description"] = c.Description
}

func (c contentType) clone(db *gorm.DB) contentType {
	c.contentTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contentType) replaceDB(db *gorm.DB) contentType {
	c.contentTypeDo.ReplaceDB(db)
	return c
}

type contentTypeDo struct{ gen.DO }

func (c contentTypeDo) Debug() *contentTypeDo {
	return c.withDO(c.DO.Debug())
}

func (c contentTypeDo) WithContext(ctx context.Context) *contentTypeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contentTypeDo) ReadDB() *contentTypeDo {
	return c.Clauses(dbresolver.Read)
}

func (c contentTypeDo) WriteDB() *contentTypeDo {
	return c.Clauses(dbresolver.Write)
}

func (c contentTypeDo) Session(config *gorm.Session) *contentTypeDo {
	return c.withDO(c.DO.Session(config))
}

func (c contentTypeDo) Clauses(conds ...clause.Expression) *contentTypeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contentTypeDo) Returning(value interface{}, columns ...string) *contentTypeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contentTypeDo) Not(conds ...gen.Condition) *contentTypeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contentTypeDo) Or(conds ...gen.Condition) *contentTypeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contentTypeDo) Select(conds ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contentTypeDo) Where(conds ...gen.Condition) *contentTypeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contentTypeDo) Order(conds ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contentTypeDo) Distinct(cols ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contentTypeDo) Omit(cols ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contentTypeDo) Join(table schema.Tabler, on ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contentTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contentTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contentTypeDo) Group(cols ...field.Expr) *contentTypeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contentTypeDo) Having(conds ...gen.Condition) *contentTypeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contentTypeDo) Limit(limit int) *contentTypeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contentTypeDo) Offset(offset int) *contentTypeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contentTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *contentTypeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contentTypeDo) Unscoped() *contentTypeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contentTypeDo) Create(values ...*model.ContentType) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contentTypeDo) CreateInBatches(values []*model.ContentType, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contentTypeDo) Save(values ...*model.ContentType) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contentTypeDo) First() (*model.ContentType, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentType), nil
	}
}

func (c contentTypeDo) Take() (*model.ContentType, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentType), nil
	}
}

func (c contentTypeDo) Last() (*model.ContentType, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentType), nil
	}
}

func (c contentTypeDo) Find() ([]*model.ContentType, error) {
	result, err := c.DO.Find()
	return result.([]*model.ContentType), err
}

func (c contentTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContentType, err error) {
	buf := make([]*model.ContentType, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contentTypeDo) FindInBatches(result *[]*model.ContentType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contentTypeDo) Attrs(attrs ...field.AssignExpr) *contentTypeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contentTypeDo) Assign(attrs ...field.AssignExpr) *contentTypeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contentTypeDo) Joins(fields ...field.RelationField) *contentTypeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contentTypeDo) Preload(fields ...field.RelationField) *contentTypeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contentTypeDo) FirstOrInit() (*model.ContentType, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentType), nil
	}
}

func (c contentTypeDo) FirstOrCreate() (*model.ContentType, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContentType), nil
	}
}

func (c contentTypeDo) FindByPage(offset int, limit int) (result []*model.ContentType, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contentTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contentTypeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contentTypeDo) Delete(models ...*model.ContentType) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contentTypeDo) withDO(do gen.Dao) *contentTypeDo {
	c.DO = *do.(*gen.DO)
	return c
}
