// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dpcms/config"
	"dpcms/internal/http/controller"
	"dpcms/internal/http/middleware"
	"dpcms/internal/http/middleware/cors"
	"dpcms/internal/http/middleware/log"
	"dpcms/internal/http/middleware/recovery"
	"dpcms/internal/http/service"
	"dpcms/internal/httpserver"
	"dpcms/internal/infra"
	"dpcms/internal/packages/cache"
	"dpcms/internal/packages/database"
	"dpcms/internal/packages/logger"
	"dpcms/internal/packages/validate"
)

// Injectors from wire.go:

func createHttpServer(cfg *config.Config) (*httpserver.Launcher, error) {
	httpserverConfig := config.GetServerConfig(cfg)
	lumberjackLogger := config.GetLoggerConfig(cfg)
	zapLogger := logger.New(lumberjackLogger)
	recoveryRecovery := recovery.New(zapLogger)
	logLogger := log.New(zapLogger)
	corsConfig := config.GetCORSConfig(cfg)
	corsCORS := cors.New(corsConfig)
	middlewareMiddleware := &middleware.Middleware{
		Recovery: recoveryRecovery,
		Logger:   logLogger,
		CORS:     corsCORS,
	}
	httpserverMiddleware := middleware.NewMiddlewareRegistrar(middlewareMiddleware)
	cacheConfig := config.GetCacheConfig(cfg)
	cacheCache := cache.New(cacheConfig)
	dbConfig := config.GetDBConfig(cfg)
	db, err := database.NewDB(dbConfig)
	if err != nil {
		return nil, err
	}
	infraInfra := &infra.Infra{
		Cache:  cacheCache,
		DB:     db,
		Logger: zapLogger,
	}
	categoryService := service.NewCategoryCategory(infraInfra)
	userService := service.NewUserService(infraInfra)
	tokenService := service.NewTokenService(infraInfra)
	v, err := service.NewRBACService(infraInfra)
	if err != nil {
		return nil, err
	}
	roleService, err := service.NewRoleService(infraInfra, v)
	if err != nil {
		return nil, err
	}
	services := &service.Services{
		Category: categoryService,
		User:     userService,
		Token:    tokenService,
		RBAC:     v,
		Role:     roleService,
	}
	userController := controller.NewUserController(services, infraInfra)
	controllerController := &controller.Controller{
		User: userController,
	}
	routes := controller.NewRouteRegistrar(controllerController)
	structValidator := validate.New()
	launcher, err := httpserver.New(httpserverConfig, httpserverMiddleware, routes, structValidator)
	if err != nil {
		return nil, err
	}
	return launcher, nil
}
