// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dpcms/internal/app/controller"
	"dpcms/internal/app/middleware"
	"dpcms/internal/app/middleware/cors"
	"dpcms/internal/app/middleware/log"
	"dpcms/internal/app/middleware/recovery"
	"dpcms/internal/app/middleware/reqtrace"
	"dpcms/internal/app/service"
	"dpcms/internal/config"
	"dpcms/internal/httpserver"
	"dpcms/internal/infra"
	"dpcms/internal/infra/db"
	"dpcms/internal/infra/hashids"
	"dpcms/internal/infra/logger"
)

// Injectors from wire.go:

func createHttpServer(cfg *config.Config) (*httpserver.Launcher, error) {
	httpserverConfig := config.GetServerConfig(cfg)
	reqTrace := reqtrace.New()
	loggerConfig := config.GetLoggerConfig(cfg)
	loggerLogger := logger.New(loggerConfig)
	recoveryRecovery := recovery.New(loggerLogger)
	loggerMiddleware := log.New(loggerLogger)
	corsConfig := config.GetCORSConfig(cfg)
	corsCORS := cors.New(corsConfig)
	middlewareMiddleware := &middleware.Middleware{
		ReqTrace: reqTrace,
		Recovery: recoveryRecovery,
		Logger:   loggerMiddleware,
		CORS:     corsCORS,
	}
	httpserverMiddleware := middleware.NewMiddlewareRegistrar(middlewareMiddleware)
	dbConfig := config.GetDBConfig(cfg)
	gormDB, err := db.NewDB(dbConfig)
	if err != nil {
		return nil, err
	}
	hashidsConfig := config.GetHashIdsConfig(cfg)
	hashIds, err := hashids.New(hashidsConfig)
	if err != nil {
		return nil, err
	}
	infraInfra := &infra.Infra{
		DB:      gormDB,
		Log:     loggerLogger,
		HashIds: hashIds,
	}
	categoryService := service.NewCategoryCategory(infraInfra)
	userService := service.NewUserService(infraInfra)
	tokenService := service.NewTokenService(cfg, infraInfra)
	rbacService, err := service.NewRBACService(infraInfra)
	if err != nil {
		return nil, err
	}
	roleService, err := service.NewRoleService(infraInfra, rbacService)
	if err != nil {
		return nil, err
	}
	menuService := service.NewMenuService(infraInfra)
	services := &service.Services{
		Category: categoryService,
		User:     userService,
		Token:    tokenService,
		RBAC:     rbacService,
		Role:     roleService,
		Menu:     menuService,
	}
	userController := controller.NewUserController(services, infraInfra)
	menuController := controller.NewMenuController(services)
	categoryController := controller.NewCategoryController(services)
	roleController := controller.NewRoleController(services, infraInfra)
	controllers := &controller.Controllers{
		User:     userController,
		Menu:     menuController,
		Category: categoryController,
		Role:     roleController,
	}
	routes := controller.NewRouteRegistrar(controllers)
	launcher, err := httpserver.New(httpserverConfig, httpserverMiddleware, routes)
	if err != nil {
		return nil, err
	}
	return launcher, nil
}
