// Code generated by gorm.io/query. DO NOT EDIT.
// Code generated by gorm.io/query. DO NOT EDIT.
// Code generated by gorm.io/query. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persist/model"
)

func newArticleModelSchema(db *gorm.DB, opts ...gen.DOOption) articleModelSchema {
	_articleModelSchema := articleModelSchema{}

	_articleModelSchema.articleModelSchemaDo.UseDB(db, opts...)
	_articleModelSchema.articleModelSchemaDo.UseModel(&model.ArticleModelSchema{})

	tableName := _articleModelSchema.articleModelSchemaDo.TableName()
	_articleModelSchema.ALL = field.NewAsterisk(tableName)
	_articleModelSchema.ID = field.NewUint64(tableName, "id")
	_articleModelSchema.CreatedAt = field.NewTime(tableName, "created_at")
	_articleModelSchema.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleModelSchema.DeletedAt = field.NewField(tableName, "deleted_at")
	_articleModelSchema.ModelID = field.NewUint64(tableName, "model_id")
	_articleModelSchema.FieldKey = field.NewString(tableName, "field_key")
	_articleModelSchema.FieldName = field.NewString(tableName, "field_name")
	_articleModelSchema.Description = field.NewString(tableName, "description")
	_articleModelSchema.MinLen = field.NewUint64(tableName, "min_len")
	_articleModelSchema.MaxLen = field.NewUint64(tableName, "max_len")
	_articleModelSchema.MinValue = field.NewField(tableName, "min_value")
	_articleModelSchema.MaxValue = field.NewField(tableName, "max_value")
	_articleModelSchema.MinTime = field.NewField(tableName, "min_time")
	_articleModelSchema.MaxTime = field.NewField(tableName, "max_time")
	_articleModelSchema.Pattern = field.NewString(tableName, "pattern")
	_articleModelSchema.Sequence = field.NewInt64(tableName, "sequence")
	_articleModelSchema.Type = field.NewInt16(tableName, "type")
	_articleModelSchema.EnumOptions = field.NewField(tableName, "enum_options")
	_articleModelSchema.Required = field.NewInt8(tableName, "required")
	_articleModelSchema.Hidden = field.NewInt8(tableName, "hidden")
	_articleModelSchema.Enable = field.NewInt8(tableName, "enable")

	_articleModelSchema.fillFieldMap()

	return _articleModelSchema
}

type articleModelSchema struct {
	articleModelSchemaDo articleModelSchemaDo

	ALL         field.Asterisk
	ID          field.Uint64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	ModelID     field.Uint64
	FieldKey    field.String // '字段唯一标识'
	FieldName   field.String // '字段名称'
	Description field.String // '字段说明'
	MinLen      field.Uint64 // '最小长度'
	MaxLen      field.Uint64 // '最大长度'
	MinValue    field.Field  // '最小值'
	MaxValue    field.Field  // '最大值'
	MinTime     field.Field  // '最小时间'
	MaxTime     field.Field  // '最大时间'
	Pattern     field.String // '正则'
	Sequence    field.Int64  // '字段排序'
	Type        field.Int16  // '字段值类型'
	EnumOptions field.Field  // '字段枚举json'
	Required    field.Int8   // '是否必填'
	Hidden      field.Int8   // '是否隐藏'
	Enable      field.Int8   // '是否启用'

	fieldMap map[string]field.Expr
}

func (a articleModelSchema) Table(newTableName string) *articleModelSchema {
	a.articleModelSchemaDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleModelSchema) As(alias string) *articleModelSchema {
	a.articleModelSchemaDo.DO = *(a.articleModelSchemaDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleModelSchema) updateTableName(table string) *articleModelSchema {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.ModelID = field.NewUint64(table, "model_id")
	a.FieldKey = field.NewString(table, "field_key")
	a.FieldName = field.NewString(table, "field_name")
	a.Description = field.NewString(table, "description")
	a.MinLen = field.NewUint64(table, "min_len")
	a.MaxLen = field.NewUint64(table, "max_len")
	a.MinValue = field.NewField(table, "min_value")
	a.MaxValue = field.NewField(table, "max_value")
	a.MinTime = field.NewField(table, "min_time")
	a.MaxTime = field.NewField(table, "max_time")
	a.Pattern = field.NewString(table, "pattern")
	a.Sequence = field.NewInt64(table, "sequence")
	a.Type = field.NewInt16(table, "type")
	a.EnumOptions = field.NewField(table, "enum_options")
	a.Required = field.NewInt8(table, "required")
	a.Hidden = field.NewInt8(table, "hidden")
	a.Enable = field.NewInt8(table, "enable")

	a.fillFieldMap()

	return a
}

func (a *articleModelSchema) WithContext(ctx context.Context) *articleModelSchemaDo {
	return a.articleModelSchemaDo.WithContext(ctx)
}

func (a articleModelSchema) TableName() string { return a.articleModelSchemaDo.TableName() }

func (a articleModelSchema) Alias() string { return a.articleModelSchemaDo.Alias() }

func (a articleModelSchema) Columns(cols ...field.Expr) gen.Columns {
	return a.articleModelSchemaDo.Columns(cols...)
}

func (a *articleModelSchema) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleModelSchema) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 21)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["model_id"] = a.ModelID
	a.fieldMap["field_key"] = a.FieldKey
	a.fieldMap["field_name"] = a.FieldName
	a.fieldMap["description"] = a.Description
	a.fieldMap["min_len"] = a.MinLen
	a.fieldMap["max_len"] = a.MaxLen
	a.fieldMap["min_value"] = a.MinValue
	a.fieldMap["max_value"] = a.MaxValue
	a.fieldMap["min_time"] = a.MinTime
	a.fieldMap["max_time"] = a.MaxTime
	a.fieldMap["pattern"] = a.Pattern
	a.fieldMap["sequence"] = a.Sequence
	a.fieldMap["type"] = a.Type
	a.fieldMap["enum_options"] = a.EnumOptions
	a.fieldMap["required"] = a.Required
	a.fieldMap["hidden"] = a.Hidden
	a.fieldMap["enable"] = a.Enable
}

func (a articleModelSchema) clone(db *gorm.DB) articleModelSchema {
	a.articleModelSchemaDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleModelSchema) replaceDB(db *gorm.DB) articleModelSchema {
	a.articleModelSchemaDo.ReplaceDB(db)
	return a
}

type articleModelSchemaDo struct{ gen.DO }

func (a articleModelSchemaDo) Debug() *articleModelSchemaDo {
	return a.withDO(a.DO.Debug())
}

func (a articleModelSchemaDo) WithContext(ctx context.Context) *articleModelSchemaDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleModelSchemaDo) ReadDB() *articleModelSchemaDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleModelSchemaDo) WriteDB() *articleModelSchemaDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleModelSchemaDo) Session(config *gorm.Session) *articleModelSchemaDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleModelSchemaDo) Clauses(conds ...clause.Expression) *articleModelSchemaDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleModelSchemaDo) Returning(value interface{}, columns ...string) *articleModelSchemaDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleModelSchemaDo) Not(conds ...gen.Condition) *articleModelSchemaDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleModelSchemaDo) Or(conds ...gen.Condition) *articleModelSchemaDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleModelSchemaDo) Select(conds ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleModelSchemaDo) Where(conds ...gen.Condition) *articleModelSchemaDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleModelSchemaDo) Order(conds ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleModelSchemaDo) Distinct(cols ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleModelSchemaDo) Omit(cols ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleModelSchemaDo) Join(table schema.Tabler, on ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleModelSchemaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleModelSchemaDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleModelSchemaDo) Group(cols ...field.Expr) *articleModelSchemaDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleModelSchemaDo) Having(conds ...gen.Condition) *articleModelSchemaDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleModelSchemaDo) Limit(limit int) *articleModelSchemaDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleModelSchemaDo) Offset(offset int) *articleModelSchemaDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleModelSchemaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleModelSchemaDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleModelSchemaDo) Unscoped() *articleModelSchemaDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleModelSchemaDo) Create(values ...*model.ArticleModelSchema) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleModelSchemaDo) CreateInBatches(values []*model.ArticleModelSchema, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleModelSchemaDo) Save(values ...*model.ArticleModelSchema) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleModelSchemaDo) First() (*model.ArticleModelSchema, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelSchema), nil
	}
}

func (a articleModelSchemaDo) Take() (*model.ArticleModelSchema, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelSchema), nil
	}
}

func (a articleModelSchemaDo) Last() (*model.ArticleModelSchema, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelSchema), nil
	}
}

func (a articleModelSchemaDo) Find() ([]*model.ArticleModelSchema, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleModelSchema), err
}

func (a articleModelSchemaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleModelSchema, err error) {
	buf := make([]*model.ArticleModelSchema, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleModelSchemaDo) FindInBatches(result *[]*model.ArticleModelSchema, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleModelSchemaDo) Attrs(attrs ...field.AssignExpr) *articleModelSchemaDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleModelSchemaDo) Assign(attrs ...field.AssignExpr) *articleModelSchemaDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleModelSchemaDo) Joins(fields ...field.RelationField) *articleModelSchemaDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleModelSchemaDo) Preload(fields ...field.RelationField) *articleModelSchemaDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleModelSchemaDo) FirstOrInit() (*model.ArticleModelSchema, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelSchema), nil
	}
}

func (a articleModelSchemaDo) FirstOrCreate() (*model.ArticleModelSchema, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleModelSchema), nil
	}
}

func (a articleModelSchemaDo) FindByPage(offset int, limit int) (result []*model.ArticleModelSchema, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleModelSchemaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleModelSchemaDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleModelSchemaDo) Delete(models ...*model.ArticleModelSchema) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleModelSchemaDo) withDO(do gen.Dao) *articleModelSchemaDo {
	a.DO = *do.(*gen.DO)
	return a
}
