// Code generated by gorm.io/query. DO NOT EDIT.
// Code generated by gorm.io/query. DO NOT EDIT.
// Code generated by gorm.io/query. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persist/model"
)

func newArticleKeywords(db *gorm.DB, opts ...gen.DOOption) articleKeywords {
	_articleKeywords := articleKeywords{}

	_articleKeywords.articleKeywordsDo.UseDB(db, opts...)
	_articleKeywords.articleKeywordsDo.UseModel(&model.ArticleKeywords{})

	tableName := _articleKeywords.articleKeywordsDo.TableName()
	_articleKeywords.ALL = field.NewAsterisk(tableName)
	_articleKeywords.ID = field.NewUint64(tableName, "id")
	_articleKeywords.CreatedAt = field.NewTime(tableName, "created_at")
	_articleKeywords.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleKeywords.DeletedAt = field.NewField(tableName, "deleted_at")
	_articleKeywords.ArticleID = field.NewUint64(tableName, "article_id")
	_articleKeywords.Keyword = field.NewString(tableName, "keyword")

	_articleKeywords.fillFieldMap()

	return _articleKeywords
}

type articleKeywords struct {
	articleKeywordsDo articleKeywordsDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	ArticleID field.Uint64
	Keyword   field.String

	fieldMap map[string]field.Expr
}

func (a articleKeywords) Table(newTableName string) *articleKeywords {
	a.articleKeywordsDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleKeywords) As(alias string) *articleKeywords {
	a.articleKeywordsDo.DO = *(a.articleKeywordsDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleKeywords) updateTableName(table string) *articleKeywords {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.ArticleID = field.NewUint64(table, "article_id")
	a.Keyword = field.NewString(table, "keyword")

	a.fillFieldMap()

	return a
}

func (a *articleKeywords) WithContext(ctx context.Context) *articleKeywordsDo {
	return a.articleKeywordsDo.WithContext(ctx)
}

func (a articleKeywords) TableName() string { return a.articleKeywordsDo.TableName() }

func (a articleKeywords) Alias() string { return a.articleKeywordsDo.Alias() }

func (a articleKeywords) Columns(cols ...field.Expr) gen.Columns {
	return a.articleKeywordsDo.Columns(cols...)
}

func (a *articleKeywords) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleKeywords) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["keyword"] = a.Keyword
}

func (a articleKeywords) clone(db *gorm.DB) articleKeywords {
	a.articleKeywordsDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleKeywords) replaceDB(db *gorm.DB) articleKeywords {
	a.articleKeywordsDo.ReplaceDB(db)
	return a
}

type articleKeywordsDo struct{ gen.DO }

func (a articleKeywordsDo) Debug() *articleKeywordsDo {
	return a.withDO(a.DO.Debug())
}

func (a articleKeywordsDo) WithContext(ctx context.Context) *articleKeywordsDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleKeywordsDo) ReadDB() *articleKeywordsDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleKeywordsDo) WriteDB() *articleKeywordsDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleKeywordsDo) Session(config *gorm.Session) *articleKeywordsDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleKeywordsDo) Clauses(conds ...clause.Expression) *articleKeywordsDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleKeywordsDo) Returning(value interface{}, columns ...string) *articleKeywordsDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleKeywordsDo) Not(conds ...gen.Condition) *articleKeywordsDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleKeywordsDo) Or(conds ...gen.Condition) *articleKeywordsDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleKeywordsDo) Select(conds ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleKeywordsDo) Where(conds ...gen.Condition) *articleKeywordsDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleKeywordsDo) Order(conds ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleKeywordsDo) Distinct(cols ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleKeywordsDo) Omit(cols ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleKeywordsDo) Join(table schema.Tabler, on ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleKeywordsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleKeywordsDo) RightJoin(table schema.Tabler, on ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleKeywordsDo) Group(cols ...field.Expr) *articleKeywordsDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleKeywordsDo) Having(conds ...gen.Condition) *articleKeywordsDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleKeywordsDo) Limit(limit int) *articleKeywordsDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleKeywordsDo) Offset(offset int) *articleKeywordsDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleKeywordsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *articleKeywordsDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleKeywordsDo) Unscoped() *articleKeywordsDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleKeywordsDo) Create(values ...*model.ArticleKeywords) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleKeywordsDo) CreateInBatches(values []*model.ArticleKeywords, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleKeywordsDo) Save(values ...*model.ArticleKeywords) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleKeywordsDo) First() (*model.ArticleKeywords, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleKeywords), nil
	}
}

func (a articleKeywordsDo) Take() (*model.ArticleKeywords, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleKeywords), nil
	}
}

func (a articleKeywordsDo) Last() (*model.ArticleKeywords, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleKeywords), nil
	}
}

func (a articleKeywordsDo) Find() ([]*model.ArticleKeywords, error) {
	result, err := a.DO.Find()
	return result.([]*model.ArticleKeywords), err
}

func (a articleKeywordsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ArticleKeywords, err error) {
	buf := make([]*model.ArticleKeywords, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleKeywordsDo) FindInBatches(result *[]*model.ArticleKeywords, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleKeywordsDo) Attrs(attrs ...field.AssignExpr) *articleKeywordsDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleKeywordsDo) Assign(attrs ...field.AssignExpr) *articleKeywordsDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleKeywordsDo) Joins(fields ...field.RelationField) *articleKeywordsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleKeywordsDo) Preload(fields ...field.RelationField) *articleKeywordsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleKeywordsDo) FirstOrInit() (*model.ArticleKeywords, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleKeywords), nil
	}
}

func (a articleKeywordsDo) FirstOrCreate() (*model.ArticleKeywords, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ArticleKeywords), nil
	}
}

func (a articleKeywordsDo) FindByPage(offset int, limit int) (result []*model.ArticleKeywords, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleKeywordsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleKeywordsDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleKeywordsDo) Delete(models ...*model.ArticleKeywords) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleKeywordsDo) withDO(do gen.Dao) *articleKeywordsDo {
	a.DO = *do.(*gen.DO)
	return a
}
