// Code generated by gorm.io/query. DO NOT EDIT.
// Code generated by gorm.io/query. DO NOT EDIT.
// Code generated by gorm.io/query. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"cms/internal/infra/persist/model"
)

func newCategoryContext(db *gorm.DB, opts ...gen.DOOption) categoryContext {
	_categoryContext := categoryContext{}

	_categoryContext.categoryContextDo.UseDB(db, opts...)
	_categoryContext.categoryContextDo.UseModel(&model.CategoryContext{})

	tableName := _categoryContext.categoryContextDo.TableName()
	_categoryContext.ALL = field.NewAsterisk(tableName)
	_categoryContext.ID = field.NewUint64(tableName, "id")
	_categoryContext.Ancestor = field.NewUint64(tableName, "ancestor")
	_categoryContext.Descendant = field.NewUint64(tableName, "descendant")
	_categoryContext.Distance = field.NewUint64(tableName, "distance")

	_categoryContext.fillFieldMap()

	return _categoryContext
}

type categoryContext struct {
	categoryContextDo categoryContextDo

	ALL        field.Asterisk
	ID         field.Uint64
	Ancestor   field.Uint64
	Descendant field.Uint64
	Distance   field.Uint64

	fieldMap map[string]field.Expr
}

func (c categoryContext) Table(newTableName string) *categoryContext {
	c.categoryContextDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c categoryContext) As(alias string) *categoryContext {
	c.categoryContextDo.DO = *(c.categoryContextDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *categoryContext) updateTableName(table string) *categoryContext {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint64(table, "id")
	c.Ancestor = field.NewUint64(table, "ancestor")
	c.Descendant = field.NewUint64(table, "descendant")
	c.Distance = field.NewUint64(table, "distance")

	c.fillFieldMap()

	return c
}

func (c *categoryContext) WithContext(ctx context.Context) *categoryContextDo {
	return c.categoryContextDo.WithContext(ctx)
}

func (c categoryContext) TableName() string { return c.categoryContextDo.TableName() }

func (c categoryContext) Alias() string { return c.categoryContextDo.Alias() }

func (c categoryContext) Columns(cols ...field.Expr) gen.Columns {
	return c.categoryContextDo.Columns(cols...)
}

func (c *categoryContext) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *categoryContext) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 4)
	c.fieldMap["id"] = c.ID
	c.fieldMap["ancestor"] = c.Ancestor
	c.fieldMap["descendant"] = c.Descendant
	c.fieldMap["distance"] = c.Distance
}

func (c categoryContext) clone(db *gorm.DB) categoryContext {
	c.categoryContextDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c categoryContext) replaceDB(db *gorm.DB) categoryContext {
	c.categoryContextDo.ReplaceDB(db)
	return c
}

type categoryContextDo struct{ gen.DO }

// INSERT INTO @@table (ancestor, descendant, distance)
// SELECT @id, @id, 0, @ancestor
// {{ if ancestor > 0 }}
// UNION ALL
// SELECT ancestor, @id, distance + 1
// FROM @@table
// WHERE descendant = @ancestor
// {{ end }}
func (c categoryContextDo) CreateSubtree(id uint64, ancestor uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	params = append(params, id)
	params = append(params, ancestor)
	generateSQL.WriteString("INSERT INTO category_context (ancestor, descendant, distance) SELECT ?, ?, 0, ? ")
	if ancestor > 0 {
		params = append(params, id)
		params = append(params, ancestor)
		generateSQL.WriteString("UNION ALL SELECT ancestor, ?, distance + 1 FROM category_context WHERE descendant = ? ")
	}

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE ancestor IN (
// SELECT descendant FROM @@table WHERE ancestor=@ancestor
// ) OR descendant IN (
// SELECT descendant FROM @@table WHERE ancestor=@ancestor
// )
func (c categoryContextDo) DropSubtree(ancestor uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, ancestor)
	params = append(params, ancestor)
	generateSQL.WriteString("DELETE FROM category_context WHERE ancestor IN ( SELECT descendant FROM category_context WHERE ancestor=? ) OR descendant IN ( SELECT descendant FROM category_context WHERE ancestor=? ) ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DELETE FROM @@table WHERE descendant IN (
// SELECT d FROM ( SELECT descendant AS d FROM @@table WHERE ancestor=@ancestor ) AS DCT
// ) AND ancestor IN (
// SELECT a FROM ( SELECT ancestor AS a FROM @@table WHERE descendant=@ancestor AND ancestor<>@ancestor ) AS ACT
// )
func (c categoryContextDo) UnbindRelationships(ancestor uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, ancestor)
	params = append(params, ancestor)
	params = append(params, ancestor)
	generateSQL.WriteString("DELETE FROM category_context WHERE descendant IN ( SELECT d FROM ( SELECT descendant AS d FROM category_context WHERE ancestor=? ) AS DCT ) AND ancestor IN ( SELECT a FROM ( SELECT ancestor AS a FROM category_context WHERE descendant=? AND ancestor<>? ) AS ACT ) ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// INSERT INTO @@table(ancestor, descendant, distance) SELECT A.ancestor, D.descendant, A.distance + D.distance + 1 FROM @@table AS A
// CROSS JOIN @@table AS D WHERE A.descendant = @target AND D.ancestor = @ancestor
func (c categoryContextDo) ReBindRelationships(ancestor uint64, target uint64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, target)
	params = append(params, ancestor)
	generateSQL.WriteString("INSERT INTO category_context(ancestor, descendant, distance) SELECT A.ancestor, D.descendant, A.distance + D.distance + 1 FROM category_context AS A CROSS JOIN category_context AS D WHERE A.descendant = ? AND D.ancestor = ? ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (c categoryContextDo) Debug() *categoryContextDo {
	return c.withDO(c.DO.Debug())
}

func (c categoryContextDo) WithContext(ctx context.Context) *categoryContextDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categoryContextDo) ReadDB() *categoryContextDo {
	return c.Clauses(dbresolver.Read)
}

func (c categoryContextDo) WriteDB() *categoryContextDo {
	return c.Clauses(dbresolver.Write)
}

func (c categoryContextDo) Session(config *gorm.Session) *categoryContextDo {
	return c.withDO(c.DO.Session(config))
}

func (c categoryContextDo) Clauses(conds ...clause.Expression) *categoryContextDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categoryContextDo) Returning(value interface{}, columns ...string) *categoryContextDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categoryContextDo) Not(conds ...gen.Condition) *categoryContextDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c categoryContextDo) Or(conds ...gen.Condition) *categoryContextDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c categoryContextDo) Select(conds ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c categoryContextDo) Where(conds ...gen.Condition) *categoryContextDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c categoryContextDo) Order(conds ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c categoryContextDo) Distinct(cols ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categoryContextDo) Omit(cols ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categoryContextDo) Join(table schema.Tabler, on ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categoryContextDo) LeftJoin(table schema.Tabler, on ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categoryContextDo) RightJoin(table schema.Tabler, on ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categoryContextDo) Group(cols ...field.Expr) *categoryContextDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c categoryContextDo) Having(conds ...gen.Condition) *categoryContextDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c categoryContextDo) Limit(limit int) *categoryContextDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c categoryContextDo) Offset(offset int) *categoryContextDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c categoryContextDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *categoryContextDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categoryContextDo) Unscoped() *categoryContextDo {
	return c.withDO(c.DO.Unscoped())
}

func (c categoryContextDo) Create(values ...*model.CategoryContext) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categoryContextDo) CreateInBatches(values []*model.CategoryContext, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categoryContextDo) Save(values ...*model.CategoryContext) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categoryContextDo) First() (*model.CategoryContext, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryContext), nil
	}
}

func (c categoryContextDo) Take() (*model.CategoryContext, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryContext), nil
	}
}

func (c categoryContextDo) Last() (*model.CategoryContext, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryContext), nil
	}
}

func (c categoryContextDo) Find() ([]*model.CategoryContext, error) {
	result, err := c.DO.Find()
	return result.([]*model.CategoryContext), err
}

func (c categoryContextDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CategoryContext, err error) {
	buf := make([]*model.CategoryContext, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categoryContextDo) FindInBatches(result *[]*model.CategoryContext, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categoryContextDo) Attrs(attrs ...field.AssignExpr) *categoryContextDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categoryContextDo) Assign(attrs ...field.AssignExpr) *categoryContextDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categoryContextDo) Joins(fields ...field.RelationField) *categoryContextDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c categoryContextDo) Preload(fields ...field.RelationField) *categoryContextDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c categoryContextDo) FirstOrInit() (*model.CategoryContext, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryContext), nil
	}
}

func (c categoryContextDo) FirstOrCreate() (*model.CategoryContext, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CategoryContext), nil
	}
}

func (c categoryContextDo) FindByPage(offset int, limit int) (result []*model.CategoryContext, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categoryContextDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c categoryContextDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c categoryContextDo) Delete(models ...*model.CategoryContext) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *categoryContextDo) withDO(do gen.Dao) *categoryContextDo {
	c.DO = *do.(*gen.DO)
	return c
}
