// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dpcms/internal/app/controller"
	"dpcms/internal/app/middleware"
	"dpcms/internal/app/middleware/cors"
	"dpcms/internal/app/middleware/log"
	"dpcms/internal/app/middleware/recovery"
	"dpcms/internal/app/middleware/reqtrace"
	"dpcms/internal/app/service"
	"dpcms/internal/config"
	"dpcms/internal/httpserver"
	"dpcms/internal/infra"
	"dpcms/internal/infra/db"
	"dpcms/internal/infra/hashids"
	"dpcms/internal/infra/logger"
	"dpcms/internal/infra/persistence"
)

import (
	_ "dpcms/docs"
)

// Injectors from wire.go:

func createHttpServer(cfg *config.Config) (*httpserver.Launcher, error) {
	httpserverConfig := config.GetServerConfig(cfg)
	loggerConfig := config.GetLoggerConfig(cfg)
	loggerLogger := logger.New(loggerConfig)
	recoveryRecovery := recovery.New(loggerLogger)
	reqTrace := reqtrace.New()
	loggerMiddleware := log.New(loggerLogger)
	corsConfig := config.GetCORSConfig(cfg)
	corsCORS := cors.New(corsConfig)
	middlewareMiddleware := &middleware.Middleware{
		Recovery: recoveryRecovery,
		ReqTrace: reqTrace,
		Logger:   loggerMiddleware,
		CORS:     corsCORS,
	}
	httpserverMiddleware := middleware.NewMiddlewareRegistrar(middlewareMiddleware)
	dbConfig := config.GetDBConfig(cfg)
	gormDB, err := db.NewDB(dbConfig)
	if err != nil {
		return nil, err
	}
	query := persistence.New(gormDB)
	hashidsConfig := config.GetHashIdsConfig(cfg)
	hashIds, err := hashids.New(hashidsConfig)
	if err != nil {
		return nil, err
	}
	infraInfra := &infra.Infra{
		DB:      gormDB,
		Query:   query,
		Log:     loggerLogger,
		HashIds: hashIds,
	}
	category := service.NewCategoryService(infraInfra)
	user := service.NewUserService(infraInfra)
	token := service.NewTokenService(cfg, infraInfra)
	rbac, err := service.NewRBACService(infraInfra)
	if err != nil {
		return nil, err
	}
	role, err := service.NewRoleService(infraInfra, rbac)
	if err != nil {
		return nil, err
	}
	menu := service.NewMenuService(infraInfra)
	article := service.NewArticle(query)
	articleModel := service.NewArticleModel(query)
	services := &service.Services{
		Category:     category,
		User:         user,
		Token:        token,
		RBAC:         rbac,
		Role:         role,
		Menu:         menu,
		Article:      article,
		ArticleModel: articleModel,
	}
	userController := controller.NewUserController(services, infraInfra)
	menuController := controller.NewMenuController(services)
	categoryController := controller.NewCategoryController(services)
	roleController := controller.NewRoleController(services)
	articleController := controller.NewArticleController(services)
	articleModelController := controller.NewArticleModelController(services)
	controllers := &controller.Controllers{
		User:         userController,
		Menu:         menuController,
		Category:     categoryController,
		Role:         roleController,
		Article:      articleController,
		ArticleModel: articleModelController,
	}
	routes := controller.NewRouteRegistrar(controllers)
	launcher, err := httpserver.New(httpserverConfig, httpserverMiddleware, routes)
	if err != nil {
		return nil, err
	}
	return launcher, nil
}
