// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	adapter6 "dpcms/internal/app/article/adapter"
	controller5 "dpcms/internal/app/article/controller"
	service6 "dpcms/internal/app/article/service"
	adapter7 "dpcms/internal/app/articlemodel/adapter"
	controller6 "dpcms/internal/app/articlemodel/controller"
	service8 "dpcms/internal/app/articlemodel/service"
	adapter4 "dpcms/internal/app/category/adapter"
	controller3 "dpcms/internal/app/category/controller"
	service4 "dpcms/internal/app/category/service"
	adapter3 "dpcms/internal/app/menu/adapter"
	controller2 "dpcms/internal/app/menu/controller"
	service3 "dpcms/internal/app/menu/service"
	auth2 "dpcms/internal/app/permission/auth"
	service7 "dpcms/internal/app/permission/service"
	adapter5 "dpcms/internal/app/role/adapter"
	controller4 "dpcms/internal/app/role/controller"
	service5 "dpcms/internal/app/role/service"
	adapter2 "dpcms/internal/app/token/adapter"
	"dpcms/internal/app/token/auth"
	service2 "dpcms/internal/app/token/service"
	"dpcms/internal/app/user/adapter"
	"dpcms/internal/app/user/controller"
	"dpcms/internal/app/user/service"
	"dpcms/internal/bootstrap"
	"dpcms/internal/config"
	"dpcms/internal/httpserver"
	"dpcms/internal/infra/db"
	"dpcms/internal/infra/logger"
	"dpcms/internal/infra/persistence"
	"dpcms/internal/infra/rbac"
	"dpcms/internal/middleware/authz"
	"dpcms/internal/middleware/cors"
	"dpcms/internal/middleware/log"
	"dpcms/internal/middleware/recovery"
	"dpcms/internal/middleware/reqtrace"
)

import (
	_ "dpcms/docs"
)

// Injectors from wire.go:

func createHttpServer(cfg *config.Config) (*httpserver.Launcher, error) {
	httpserverConfig := config.GetServerConfig(cfg)
	loggerConfig := config.GetLoggerConfig(cfg)
	loggerLogger := logger.New(loggerConfig)
	middleware := recovery.New(loggerLogger)
	reqtraceMiddleware := reqtrace.New()
	logMiddleware := log.New(loggerLogger)
	corsConfig := config.GetCORSConfig(cfg)
	corsMiddleware := cors.New(corsConfig)
	bootstrapMiddleware := &bootstrap.Middleware{
		Recovery: middleware,
		ReqTrace: reqtraceMiddleware,
		Logger:   logMiddleware,
		CORS:     corsMiddleware,
	}
	httpserverMiddleware := bootstrap.NewMiddlewareRegistrar(bootstrapMiddleware)
	dbConfig := config.GetDBConfig(cfg)
	gormDB, err := db.NewDB(dbConfig)
	if err != nil {
		return nil, err
	}
	query := persistence.NewQuery(gormDB)
	txManager := persistence.NewTxManager(query)
	userRepo := adapter.NewUserRepo(query)
	userService := service.NewUserService(txManager, userRepo)
	tokenBlacklistRepo := adapter2.NewTokenBlacklistRepo(query)
	tokenService := service2.NewTokenService(cfg, tokenBlacklistRepo, userRepo)
	tokenParser := auth.NewTokenParser(tokenService)
	roleCasbin, err := rbac.NewRoleCasbin(gormDB)
	if err != nil {
		return nil, err
	}
	permissionChecker := auth2.NewPermissionChecker(roleCasbin)
	builder := authz.NewBuilder(tokenParser, permissionChecker)
	userController := controller.UserController{
		UserSrv:  userService,
		TokenSrv: tokenService,
		Logger:   loggerLogger,
		Auth:     builder,
	}
	menuRepo := adapter3.NewMenuRepo(query)
	menuService := service3.NewMenuService(txManager, menuRepo)
	menuController := controller2.MenuController{
		MenuSrv: menuService,
		Auth:    builder,
	}
	categoryRepo := adapter4.NewCategoryRepo(query)
	categoryService := service4.NewCategoryService(txManager, categoryRepo)
	categoryController := controller3.CategoryController{
		CategorySrv: categoryService,
		Auth:        builder,
	}
	roleRepo := adapter5.NewRoleRepo(query)
	roleService := service5.NewRoleService(txManager, roleCasbin, roleRepo)
	roleController := controller4.RoleController{
		RoleSrv: roleService,
		Auth:    builder,
	}
	articleRepo := adapter6.NewArticleRepo(query)
	articleModelRepo := adapter7.NewArticleModelRepo(query)
	articleService := service6.NewArticleService(txManager, articleRepo, articleModelRepo)
	permissionService := &service7.PermissionService{
		Query: query,
	}
	articleController := controller5.ArticleController{
		ArticleSrv: articleService,
		PermSrv:    permissionService,
		Auth:       builder,
		Casbin:     roleCasbin,
	}
	articleModelService := service8.NewArticleModelService(txManager, articleModelRepo)
	articleModelController := controller6.ArticleModelController{
		ArticleModelSrv: articleModelService,
		Auth:            builder,
	}
	controllers := &bootstrap.Controllers{
		User:         userController,
		Menu:         menuController,
		Category:     categoryController,
		Role:         roleController,
		Article:      articleController,
		ArticleModel: articleModelController,
	}
	routes := bootstrap.NewRouteRegistrar(controllers)
	launcher, err := httpserver.New(httpserverConfig, httpserverMiddleware, routes)
	if err != nil {
		return nil, err
	}
	return launcher, nil
}
