// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	controller5 "cms/internal/app/article"
	adapter8 "cms/internal/app/article/adapter"
    adapter9 "cms/internal/app/contenttype/adapter"
    controller6 "cms/internal/app/contenttype/controller"
    service9 "cms/internal/app/contenttype/service"
	service5 `cms/internal/app/category`
	adapter6 "cms/internal/app/category/adapter"
	adapter10 "cms/internal/app/file/adapter"
	controller7 "cms/internal/app/file/controller"
	service10 "cms/internal/app/file/service"
	adapter5 "cms/internal/app/menu/adapter"
	controller2 "cms/internal/app/menu/controller"
	service4 "cms/internal/app/menu/service"
	adapter4 "cms/internal/app/permission/adapter"
	controller8 "cms/internal/app/permission/controller"
	service6 "cms/internal/app/permission/service"
	adapter7 "cms/internal/app/role/adapter"
	controller4 "cms/internal/app/role/controller"
	service7 "cms/internal/app/role/service"
	"cms/internal/app/setting/adapter"
	"cms/internal/app/setting/service"
	adapter3 "cms/internal/app/token/adapter"
	service3 "cms/internal/app/token/service"
	adapter2 "cms/internal/app/user/adapter"
	"cms/internal/app/user/controller"
	service2 "cms/internal/app/user/service"
	"cms/internal/bootstrap"
	controller9 "cms/internal/bootstrap/controller"
	"cms/internal/bootstrap/filedriver"
	"cms/internal/bootstrap/middleware"
	"cms/internal/config"
	"cms/internal/httpserver"
	"cms/internal/infra/casbin"
	"cms/internal/infra/db"
	"cms/internal/infra/file/driver/local"
	"cms/internal/infra/logger"
	"cms/internal/infra/persistence"
	"cms/internal/lifecycle"
	middleware2 `cms/internal/middleware`
	"cms/internal/middleware/authz"
	`cms/internal/pkg/hashid`
	
	_ `cms/docs`
)

// Injectors from wire.go:

func initApp(cfg *config.Config) (bootstrap.Bootstrap, error) {
	lifecycleLifecycle := lifecycle.New()
	httpserverConfig := config.GetServerConfig(cfg)
	launcher, err := httpserver.New(httpserverConfig)
	if err != nil {
		return bootstrap.Bootstrap{}, err
	}
	loggerConfig := config.GetLoggerConfig(cfg)
	loggerLogger := logger.New(loggerConfig)
	recoveryRecovery := middleware2.New(loggerLogger)
	requestTrace := middleware2.New()
	logLog := middleware2.New(loggerLogger)
	dbConfig := config.GetDBConfig(cfg)
	gormDB, err := db.NewDB(dbConfig)
	if err != nil {
		return bootstrap.Bootstrap{}, err
	}
	query := persistence.NewQuery(gormDB)
	txManager := persistence.NewTransactor(query)
	settingRepo := adapter.NewConfigRepo(query)
	settingService := service.NewSettingService(txManager, settingRepo, loggerLogger, cfg)
	options := adapter.NewCORSOptions(settingService)
	corsCORS := middleware2.New(options)
	httpserverMiddleware := middleware.NewMiddlewareRegistrar(recoveryRecovery, requestTrace, logLog, corsCORS)
	userRepo := adapter2.NewUserRepo(query)
	userService := service2.NewUserService(txManager, userRepo)
	tokenBlacklistRepo := adapter3.NewTokenBlacklistRepo(query)
	tokenService := service3.NewTokenService(cfg, tokenBlacklistRepo, userRepo)
	tokenParser := adapter3.NewTokenParser(tokenService)
	roleCasbin, err := casbin.NewRoleCasbin(gormDB)
	if err != nil {
		return bootstrap.Bootstrap{}, err
	}
	permissionChecker := adapter4.NewPermissionChecker(roleCasbin)
	factory := authz.NewFactory(tokenParser, permissionChecker)
	userController := controller.NewUserController(userService, tokenService, loggerLogger, factory)
	menuRepo := adapter5.NewMenuRepo(query)
	menuService := service4.NewMenuService(txManager, menuRepo)
	menuController := controller2.NewMenuController(menuService, factory)
	categoryRepo := adapter6.NewCategoryRepo(query)
	categoryService := service5.NewCategoryService(txManager, categoryRepo)
	categoryController := service5.NewCategoryController(categoryService, factory)
	roleRepo := adapter7.NewRoleRepo(query)
	permissionRepo := adapter4.NewPermissionRepo(query)
	permissionService := service6.NewPermissionService(permissionRepo)
	roleService := service7.NewRoleService(txManager, roleCasbin, roleRepo, permissionService)
	roleController := controller4.NewRoleController(roleService, factory)
	articleRepo := adapter8.NewArticleRepo(query)
	articleModelRepo := adapter9.NewArticleModelRepo(query)
	articleService := controller5.NewArticleService(txManager, articleRepo, articleModelRepo)
	articleController := controller5.NewArticleController(articleService, permissionService, factory, roleCasbin)
	articleModelService := service9.NewArticleModelService(txManager, articleModelRepo)
	articleModelController := controller6.NewArticleModelController(articleModelService, factory)
	fileRepo := adapter10.NewFileRepo(query)
	fileConfig := config.GetFileConfig(cfg)
	localFactory := local.Factory{}
	fileDrivers := filedriver.FileDrivers{
		Local: localFactory,
	}
	driverRegistry, err := filedriver.NewFileRegistry(fileConfig, fileDrivers)
	if err != nil {
		return bootstrap.Bootstrap{}, err
	}
	fileDriverService := service10.NewFileDriverService(driverRegistry, cfg)
	fileService := service10.NewFileService(txManager, fileRepo, fileDriverService, loggerLogger)
	hashID, err := hashid.New(cfg)
	if err != nil {
		return bootstrap.Bootstrap{}, err
	}
	fileController := controller7.NewFileController(fileService, factory, hashID)
	permissionController := controller8.NewPermissionController(permissionService)
	controllerSet := &controller9.ControllerSet{
		User:         userController,
		Menu:         menuController,
		Category:     categoryController,
		Role:         roleController,
		Article:      articleController,
		ArticleModel: articleModelController,
		File:         fileController,
		Perm:         permissionController,
	}
	route := controller9.NewRouteRegistrar(controllerSet)
	bootstrapBootstrap := bootstrap.New(lifecycleLifecycle, launcher, httpserverMiddleware, route)
	return bootstrapBootstrap, nil
}
