// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Category:        newCategory(db, opts...),
		CategoryContext: newCategoryContext(db, opts...),
		CategorySeo:     newCategorySeo(db, opts...),
		Menu:            newMenu(db, opts...),
		MenuContext:     newMenuContext(db, opts...),
		Role:            newRole(db, opts...),
		TokenBlacklist:  newTokenBlacklist(db, opts...),
		User:            newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Category        category
	CategoryContext categoryContext
	CategorySeo     categorySeo
	Menu            menu
	MenuContext     menuContext
	Role            role
	TokenBlacklist  tokenBlacklist
	User            user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Category:        q.Category.clone(db),
		CategoryContext: q.CategoryContext.clone(db),
		CategorySeo:     q.CategorySeo.clone(db),
		Menu:            q.Menu.clone(db),
		MenuContext:     q.MenuContext.clone(db),
		Role:            q.Role.clone(db),
		TokenBlacklist:  q.TokenBlacklist.clone(db),
		User:            q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Category:        q.Category.replaceDB(db),
		CategoryContext: q.CategoryContext.replaceDB(db),
		CategorySeo:     q.CategorySeo.replaceDB(db),
		Menu:            q.Menu.replaceDB(db),
		MenuContext:     q.MenuContext.replaceDB(db),
		Role:            q.Role.replaceDB(db),
		TokenBlacklist:  q.TokenBlacklist.replaceDB(db),
		User:            q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Category        *categoryDo
	CategoryContext *categoryContextDo
	CategorySeo     *categorySeoDo
	Menu            *menuDo
	MenuContext     *menuContextDo
	Role            *roleDo
	TokenBlacklist  *tokenBlacklistDo
	User            *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Category:        q.Category.WithContext(ctx),
		CategoryContext: q.CategoryContext.WithContext(ctx),
		CategorySeo:     q.CategorySeo.WithContext(ctx),
		Menu:            q.Menu.WithContext(ctx),
		MenuContext:     q.MenuContext.WithContext(ctx),
		Role:            q.Role.WithContext(ctx),
		TokenBlacklist:  q.TokenBlacklist.WithContext(ctx),
		User:            q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
