// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"dpcms/model"
)

func newRoleMenuRelation(db *gorm.DB, opts ...gen.DOOption) roleMenuRelation {
	_roleMenuRelation := roleMenuRelation{}

	_roleMenuRelation.roleMenuRelationDo.UseDB(db, opts...)
	_roleMenuRelation.roleMenuRelationDo.UseModel(&model.RoleMenuRelation{})

	tableName := _roleMenuRelation.roleMenuRelationDo.TableName()
	_roleMenuRelation.ALL = field.NewAsterisk(tableName)
	_roleMenuRelation.ID = field.NewUint(tableName, "id")
	_roleMenuRelation.CreatedAt = field.NewTime(tableName, "created_at")
	_roleMenuRelation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_roleMenuRelation.DeletedAt = field.NewField(tableName, "deleted_at")
	_roleMenuRelation.RoleID = field.NewUint(tableName, "role_id")
	_roleMenuRelation.MenuID = field.NewUint(tableName, "menu_id")

	_roleMenuRelation.fillFieldMap()

	return _roleMenuRelation
}

type roleMenuRelation struct {
	roleMenuRelationDo roleMenuRelationDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	RoleID    field.Uint
	MenuID    field.Uint

	fieldMap map[string]field.Expr
}

func (r roleMenuRelation) Table(newTableName string) *roleMenuRelation {
	r.roleMenuRelationDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roleMenuRelation) As(alias string) *roleMenuRelation {
	r.roleMenuRelationDo.DO = *(r.roleMenuRelationDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roleMenuRelation) updateTableName(table string) *roleMenuRelation {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.RoleID = field.NewUint(table, "role_id")
	r.MenuID = field.NewUint(table, "menu_id")

	r.fillFieldMap()

	return r
}

func (r *roleMenuRelation) WithContext(ctx context.Context) *roleMenuRelationDo {
	return r.roleMenuRelationDo.WithContext(ctx)
}

func (r roleMenuRelation) TableName() string { return r.roleMenuRelationDo.TableName() }

func (r roleMenuRelation) Alias() string { return r.roleMenuRelationDo.Alias() }

func (r roleMenuRelation) Columns(cols ...field.Expr) gen.Columns {
	return r.roleMenuRelationDo.Columns(cols...)
}

func (r *roleMenuRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roleMenuRelation) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["menu_id"] = r.MenuID
}

func (r roleMenuRelation) clone(db *gorm.DB) roleMenuRelation {
	r.roleMenuRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roleMenuRelation) replaceDB(db *gorm.DB) roleMenuRelation {
	r.roleMenuRelationDo.ReplaceDB(db)
	return r
}

type roleMenuRelationDo struct{ gen.DO }

func (r roleMenuRelationDo) Debug() *roleMenuRelationDo {
	return r.withDO(r.DO.Debug())
}

func (r roleMenuRelationDo) WithContext(ctx context.Context) *roleMenuRelationDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roleMenuRelationDo) ReadDB() *roleMenuRelationDo {
	return r.Clauses(dbresolver.Read)
}

func (r roleMenuRelationDo) WriteDB() *roleMenuRelationDo {
	return r.Clauses(dbresolver.Write)
}

func (r roleMenuRelationDo) Session(config *gorm.Session) *roleMenuRelationDo {
	return r.withDO(r.DO.Session(config))
}

func (r roleMenuRelationDo) Clauses(conds ...clause.Expression) *roleMenuRelationDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roleMenuRelationDo) Returning(value interface{}, columns ...string) *roleMenuRelationDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roleMenuRelationDo) Not(conds ...gen.Condition) *roleMenuRelationDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roleMenuRelationDo) Or(conds ...gen.Condition) *roleMenuRelationDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roleMenuRelationDo) Select(conds ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roleMenuRelationDo) Where(conds ...gen.Condition) *roleMenuRelationDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roleMenuRelationDo) Order(conds ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roleMenuRelationDo) Distinct(cols ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roleMenuRelationDo) Omit(cols ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roleMenuRelationDo) Join(table schema.Tabler, on ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roleMenuRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roleMenuRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roleMenuRelationDo) Group(cols ...field.Expr) *roleMenuRelationDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roleMenuRelationDo) Having(conds ...gen.Condition) *roleMenuRelationDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roleMenuRelationDo) Limit(limit int) *roleMenuRelationDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roleMenuRelationDo) Offset(offset int) *roleMenuRelationDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roleMenuRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *roleMenuRelationDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roleMenuRelationDo) Unscoped() *roleMenuRelationDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roleMenuRelationDo) Create(values ...*model.RoleMenuRelation) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roleMenuRelationDo) CreateInBatches(values []*model.RoleMenuRelation, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roleMenuRelationDo) Save(values ...*model.RoleMenuRelation) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roleMenuRelationDo) First() (*model.RoleMenuRelation, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenuRelation), nil
	}
}

func (r roleMenuRelationDo) Take() (*model.RoleMenuRelation, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenuRelation), nil
	}
}

func (r roleMenuRelationDo) Last() (*model.RoleMenuRelation, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenuRelation), nil
	}
}

func (r roleMenuRelationDo) Find() ([]*model.RoleMenuRelation, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoleMenuRelation), err
}

func (r roleMenuRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleMenuRelation, err error) {
	buf := make([]*model.RoleMenuRelation, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roleMenuRelationDo) FindInBatches(result *[]*model.RoleMenuRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roleMenuRelationDo) Attrs(attrs ...field.AssignExpr) *roleMenuRelationDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roleMenuRelationDo) Assign(attrs ...field.AssignExpr) *roleMenuRelationDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roleMenuRelationDo) Joins(fields ...field.RelationField) *roleMenuRelationDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roleMenuRelationDo) Preload(fields ...field.RelationField) *roleMenuRelationDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roleMenuRelationDo) FirstOrInit() (*model.RoleMenuRelation, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenuRelation), nil
	}
}

func (r roleMenuRelationDo) FirstOrCreate() (*model.RoleMenuRelation, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenuRelation), nil
	}
}

func (r roleMenuRelationDo) FindByPage(offset int, limit int) (result []*model.RoleMenuRelation, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roleMenuRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roleMenuRelationDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roleMenuRelationDo) Delete(models ...*model.RoleMenuRelation) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roleMenuRelationDo) withDO(do gen.Dao) *roleMenuRelationDo {
	r.DO = *do.(*gen.DO)
	return r
}
